### ISSUE TITLE
[Pekwm/xfce-openrc] Please clean up profile

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#10]
Aaditya, please clean up the profiles and remove any init.d live services and the desktop entries for thus and cli-installer.
These should be created on the fly or by package.

**Comment by aadityabagga** [comment]
I am not really maintaining pekwm, I think Holmes is also not working on it any more, so maybe you could create an archives folder and move the old and/or unmaintained profiles there.

Regarding init.d files, why do you have a problem if I keep them...

**Comment by udeved** [comment]
Because we don't know otherwise if something does not work. Please remove them.

Hmm, should we eventually move legacy profiles to a separate repo?

**Comment by philmmanjaro** [comment]
It would be best to create a community repository and only maintain our official profiles. On the other side it might not matter if they are in this repo. But for sure we have to clean them up and at least test them once.

**Comment by udeved** [comment]
Having say official, community and openrc profiles separately packaged has a certain appeal as it reduces package size.

What I wondered, if it is doable to basically integrated the shared folder in manjaro-tools and it that would make sense, if we had say a manjaro-tools folder in $USER?

**Comment by Kirek** [comment]
We have git history, with a meaningful commit description like "Removed pekwm profile" I think it will be enough...

**Comment by Kirek** [comment]
@udeved 
I don't understand what you mean with a manjaro-tools folder in $USER.

**Comment by udeved** [comment]
I imagine shared is integrated in manjaro-tools, and on first run, a folder structure in the user home is created and shared content copied. 
user would only have to either clone into that dir the profiles, or copy installed repo profiles to this location.

**Comment by Kirek** [comment]
This doesn't make any sense to me, shared is part of the profiles. Nor automatically creating this structure in the home dir, what's wrong with git clone the iso profiles in whatever place you want?

**Comment by udeved** [comment]
I mean only a future the profile.conf, or currently the initsys files, the rest would remain.
The other would be the uefi binaries I placed there temporarily.
Yes right, no sense moving everything, but the thoght behind is, if we could realize a filesystem overlay for manjaro-tools related files somewhere in $USER where the profiles nicely integrate.
I sort of thinking of a filesystem layout in the user home and if that is doable.

**Comment by philmmanjaro** [comment]
Well, we have git and git stores everything. We just delete the broken stuff and give each deletion a good name as @Kirek  already suggested. This way we can go back to those tags and check that out if needed and adopt to later changes. This way our current release tarballs are smaller and if needed you can still checkout by commit code. So slim it down now and if needed we can restore those parts.

**Comment by philmmanjaro** [comment]
Adding share to manjaro-tools makes no sense. We should focus on config files and all the stuff needed to get a profile share-able. Simply put: if I give you a profile tarball you should be able to compile my install media without having trouble. Each profile might ship a config file telling the minimal dependency of needed manjaro-tools to compile it. This is the way we should go. Any other suggestions or wishes?

**Comment by udeved** [comment]
Agreed, I like smaller size.
Suggestion, make profiles smaller atmons, but let them install at same location, easily done in PKGBUILD.

**Comment by aadityabagga** [comment]
@udeved

Cleaned up profile and sent a pull request.
https://github.com/manjaro/manjaro-tools-iso-profiles/pull/16
