### ISSUE TITLE
tryed building sonar-mate profile getting error

### ISSUE THREAD

**Issue by mhussaincov** [manjaro/manjaro-tools-iso-profiles#100]
when building sonar-mate profile get an error.
i used the script command for output to txt file, here it is.
ERROR:(B[m[1m Profile [/home/majid/git/manjaro-tools-iso-profiles/sonar/mate-sonar] sanity check failed
this happens as soon as it starts the process 
happens with the other profiles in that folder.
note, cloned iso profiles repo before starting the build.

**Comment by Ste74** [comment]
Manjaro tools profile folder now want in the home directory. Post your
Buildiso -p mate-sonar -qv output
Il 09/gen/2016 15:35, "mhussaincov" <notifications@github.com> ha scritto:
>
> when building sonar-mate profile get an error
> i used the script command for output to txt file, here it is
> ERROR:�(B�[m�[1m Profile
[/home/majid/git/manjaro-tools-iso-profiles/sonar/mate-sonar] sanity check
failed

**Comment by philmmanjaro** [comment]
This is a dublicate of #98. Please use at least **manjaro-tools 0.10.0**.

**Comment by mhussaincov** [comment]
hi there,
here is my output
of
sudo buildiso -p mate-sonar -qv sorry for the extra chars.

sudo buildiso -p mate-sonar -qv
[1m[32m==>(B[m[1m manjaro-tools(B[m
[1m[34m  ->(B[m[1m version: 0.9.15(B[m
[1m[34m  ->(B[m[1m manjaro_tools_conf:
/etc/manjaro-tools/manjaro-tools.conf(B[m
[1m[32m==>(B[m[1m PROFILE:(B[m
[1m[34m  ->(B[m[1m sets_dir_iso: /etc/manjaro-tools/iso.d(B[m
[1m[34m  ->(B[m[1m buildsets:
community-minimal|community|default|official(B[m
[1m[34m  ->(B[m[1m buildset_iso: mate-sonar(B[m
[1m[34m  ->(B[m[1m is_buildset: false(B[m
[1m[34m  ->(B[m[1m profile_repo: manjaro-tools-iso-profiles(B[m
[1m[32m==>(B[m[1m OPTIONS:(B[m
[1m[34m  ->(B[m[1m arch: x86_64(B[m
[1m[34m  ->(B[m[1m branch: stable(B[m
[1m[34m  ->(B[m[1m chroots_iso: /var/lib/manjaro-tools/buildiso(B[m
[1m[32m==>(B[m[1m ARGS:(B[m
[1m[34m  ->(B[m[1m clean_first: true(B[m
[1m[34m  ->(B[m[1m images_only: false(B[m
[1m[34m  ->(B[m[1m iso_only: false(B[m
[1m[32m==>(B[m[1m DIST SETTINGS:(B[m
[1m[34m  ->(B[m[1m dist_name: Manjaro(B[m
[1m[34m  ->(B[m[1m dist_release: 16.01(B[m
[1m[34m  ->(B[m[1m dist_codename: Capella(B[m
[1m[32m==>(B[m[1m ISO SETTINGS:(B[m
[1m[34m  ->(B[m[1m iso_label: MJRO1601(B[m
[1m[34m  ->(B[m[1m iso_name: manjaro(B[m
[1m[34m  ->(B[m[1m iso_publisher: Manjaro Linux
<http://www.manjaro.org>(B[m
[1m[34m  ->(B[m[1m iso_app_id: Manjaro Linux Live/Rescue CD(B[m
[1m[34m  ->(B[m[1m iso_compression: xz(B[m
[1m[34m  ->(B[m[1m iso_checksum: md5(B[m
[1m[34m  ->(B[m[1m use_overlayfs: true(B[m

[1m[32m==>(B[m[1m BUILD QUEUE:(B[m
[1m[33m -->(B[m[1m Profile: [mate-sonar](B[m
[1m[31m==> ERROR:(B[m[1m Profile
[/home/majid/git/manjaro-tools-iso-profiles/sonar/mate-sonar] sanity
check failed!(B[m


sorry for the extra chars but there is the output.

hope this helps?

On 09/01/2016, Stefano <notifications@github.com> wrote:
> Manjaro tools profile folder now want in the home directory. Post your
> Buildiso -p mate-sonar -qv output
> Il 09/gen/2016 15:35, "mhussaincov" <notifications@github.com> ha scritto:
>>
>> when building sonar-mate profile get an error
>> i used the script command for output to txt file, here it is
>> ERROR:�(B�[m�[1m Profile
> [/home/majid/git/manjaro-tools-iso-profiles/sonar/mate-sonar] sanity check
> failed
>> this happens as soon as it starts the process
>> happens with the other profiles in that folder
>> note, cloned iso profiles repo before starting the build
>>
>> —
>> Reply to this email directly or view it on GitHub.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/manjaro/manjaro-tools-iso-profiles/issues/100#issuecomment-170244037


-- 
kind regards,
Majid Hussain

**Comment by udeved** [comment]
You need manjaro-tools-0.10.0 for the profiles.

**Comment by mhussaincov** [comment]
okay,
how do I upgrade from current manjaro-tools version?
brantch=stable, should I go unstable?

On 09/01/2016, Majid HUSSAIN <mhussaincov@gmail.com> wrote:
> hi there,
> here is my output
> of
> sudo buildiso -p mate-sonar -qv sorry for the extra chars.
>
> sudo buildiso -p mate-sonar -qv
>  [1m [32m==> (B [m [1m manjaro-tools (B [m
>  [1m [34m  -> (B [m [1m version: 0.9.15 (B [m
>  [1m [34m  -> (B [m [1m manjaro_tools_conf:
> /etc/manjaro-tools/manjaro-tools.conf (B [m
>  [1m [32m==> (B [m [1m PROFILE: (B [m
>  [1m [34m  -> (B [m [1m sets_dir_iso: /etc/manjaro-tools/iso.d (B [m
>  [1m [34m  -> (B [m [1m buildsets:
> community-minimal|community|default|official (B [m
>  [1m [34m  -> (B [m [1m buildset_iso: mate-sonar (B [m
>  [1m [34m  -> (B [m [1m is_buildset: false (B [m
>  [1m [34m  -> (B [m [1m profile_repo: manjaro-tools-iso-profiles (B [m
>  [1m [32m==> (B [m [1m OPTIONS: (B [m
>  [1m [34m  -> (B [m [1m arch: x86_64 (B [m
>  [1m [34m  -> (B [m [1m branch: stable (B [m
>  [1m [34m  -> (B [m [1m chroots_iso: /var/lib/manjaro-tools/buildiso (B [m
>  [1m [32m==> (B [m [1m ARGS: (B [m
>  [1m [34m  -> (B [m [1m clean_first: true (B [m
>  [1m [34m  -> (B [m [1m images_only: false (B [m
>  [1m [34m  -> (B [m [1m iso_only: false (B [m
>  [1m [32m==> (B [m [1m DIST SETTINGS: (B [m
>  [1m [34m  -> (B [m [1m dist_name: Manjaro (B [m
>  [1m [34m  -> (B [m [1m dist_release: 16.01 (B [m
>  [1m [34m  -> (B [m [1m dist_codename: Capella (B [m
>  [1m [32m==> (B [m [1m ISO SETTINGS: (B [m
>  [1m [34m  -> (B [m [1m iso_label: MJRO1601 (B [m
>  [1m [34m  -> (B [m [1m iso_name: manjaro (B [m
>  [1m [34m  -> (B [m [1m iso_publisher: Manjaro Linux
> <http://www.manjaro.org> (B [m
>  [1m [34m  -> (B [m [1m iso_app_id: Manjaro Linux Live/Rescue CD (B [m
>  [1m [34m  -> (B [m [1m iso_compression: xz (B [m
>  [1m [34m  -> (B [m [1m iso_checksum: md5 (B [m
>  [1m [34m  -> (B [m [1m use_overlayfs: true (B [m
>
>  [1m [32m==> (B [m [1m BUILD QUEUE: (B [m
>  [1m [33m --> (B [m [1m Profile: [mate-sonar] (B [m
>  [1m [31m==> ERROR: (B [m [1m Profile
> [/home/majid/git/manjaro-tools-iso-profiles/sonar/mate-sonar] sanity
> check failed! (B [m
>
>
> sorry for the extra chars but there is the output.
>
> hope this helps?
>
> On 09/01/2016, Stefano <notifications@github.com> wrote:
>> Manjaro tools profile folder now want in the home directory. Post your
>> Buildiso -p mate-sonar -qv output
>> Il 09/gen/2016 15:35, "mhussaincov" <notifications@github.com> ha
>> scritto:
>>>
>>> when building sonar-mate profile get an error
>>> i used the script command for output to txt file, here it is
>>> ERROR:�(B�[m�[1m Profile
>> [/home/majid/git/manjaro-tools-iso-profiles/sonar/mate-sonar] sanity
>> check
>> failed
>>> this happens as soon as it starts the process
>>> happens with the other profiles in that folder
>>> note, cloned iso profiles repo before starting the build
>>>
>>> —
>>> Reply to this email directly or view it on GitHub.
>>
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/manjaro/manjaro-tools-iso-profiles/issues/100#issuecomment-170244037
>
>
> --
> kind regards,
> Majid Hussain
>


-- 
kind regards,
Majid Hussain

**Comment by philmmanjaro** [comment]
On Tuesday it will be also in our **stable** branch. For now it is in **testing** and **unstable**. Simply switch to one of these branches and update your system.

**Comment by mhussaincov** [comment]
thank you so much!
going to do that now! :)

On 09/01/2016, Philip Müller <notifications@github.com> wrote:
> On Tuesday it will be also in our **stable** branch. For now it is in
> **testing** and **unstable**. Simply switch to one of these branches and
> update your system.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/manjaro/manjaro-tools-iso-profiles/issues/100#issuecomment-170244972


-- 
kind regards,
Majid Hussain

**Comment by coffeeking** [comment]
hi
I was actually able to successfully build sonar gnome after it was 
murged into the main manjaro iso profiles, however it no longer boots to 
the desktop. So now I'm completely exasperated. What am I or someone 
else doing to mess this thing up. Not that I believe this was 
intentional by anyone. I'm just not at all sure what could be going 
wrong. The packages files look right, all the stuff is even better 
organized than I had it, being in it's own shared folder, all the 
symlinks look properly set up, I don't get it. Is there no way to run 
tests to ensure the built image will boot and error out if not? I 
suppose that's immensely complicated but a guy can dream

Thanks
Kendell clark

**Comment by mhussaincov** [comment]
hi there,
is the display manager running?
is x started on boot?
are the systemd services started?
would takeing a look at community/gnome's profile help?
Majid

On 09/01/2016, coffeeking <notifications@github.com> wrote:
> hi
> I was actually able to successfully build sonar gnome after it was
> murged into the main manjaro iso profiles, however it no longer boots to
> the desktop. So now I'm completely exasperated. What am I or someone
> else doing to mess this thing up. Not that I believe this was
> intentional by anyone. I'm just not at all sure what could be going
> wrong. The packages files look right, all the stuff is even better
> organized than I had it, being in it's own shared folder, all the
> symlinks look properly set up, I don't get it. Is there no way to run
> tests to ensure the built image will boot and error out if not? I
> suppose that's immensely complicated but a guy can dream
>
> Thanks
> Kendell clark
>
>
> On 01/09/2016 08:42 AM, Philip Müller wrote:
>>
>> Closed #100
>> <https://github.com/manjaro/manjaro-tools-iso-profiles/issues/100>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/manjaro/manjaro-tools-iso-profiles/issues/100#event-510210207>.
>>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/manjaro/manjaro-tools-iso-profiles/issues/100#issuecomment-170266341


-- 
kind regards,
Majid Hussain

**Comment by coffeeking** [comment]
hi
I'm not sure about the display manager, or x, or systemd's services. But 
I will most definitely take a look at the community gnome profile. In 
fact, we may simply copy over the community's gnome profile, making sure 
our overlay is in place. The main reason I keep having to ask people for 
help with this is because once I boot the live image, I can't use it 
until it boots enough for orca to start. I have some sight, but all I 
can see is  text on the screen. I don't think it finishes booting enough 
for the getty to show up, meaning I can't log in enough to start 
speakup, the console screen reader to investigate. I've tried booting 
these images in a vm, gnome boxes and virtualbox, but they won't boot 
there either.
I'll keep on top of this and write back in with any problems. Do you 
still need me to execute sudo buildiso -qv -p gnome-sonar output? I was 
going to and completely forgot in the excitement of the murge but I'll 
do that immediately and attach the results if you need it.
Thanks
Kendell clark

**Comment by philmmanjaro** [comment]
@coffeeking: only thing what I see missing is the **gnome-overlay/etc/gdm/custom.conf** file. I'll add that now.

**Comment by philmmanjaro** [comment]
@mhussaincov: I tested now both profiles. They work now. You need the latest git profiles, **manjaro-tools v0.10** and **sonar-isolinux** installed on your system to get it working.
