### ISSUE TITLE
Profile maintainer list

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#101]
Please check the box if your profile is tested.

### official

- [x] xfce -- [philmmanjaro] (https://github.com/philmmanjaro) 
- [x] net  -- [alexandru] (https://github.com/alexandruianu), [philmmanjaro] (https://github.com/philmmanjaro)
- [x] kde -- [Kirek] (https://github.com/Kirek), [philmmanjaro] (https://github.com/philmmanjaro)

### minimal

- [x] lxqt  --  [artoo] (https://github.com/udeved) 
- [x] budgie -- [Ste74] (https://github.com/Ste74) 
- [x] net  -- [excalibur1234] (https://github.com/excalibur1234) 
- [x] kde -- [Kirek] (https://github.com/Kirek), [artoo] (https://github.com/udeved), [philmmanjaro] (https://github.com/philmmanjaro)
- [x] xfce -- [philmmanjaro] (https://github.com/philmmanjaro), [alexandru] (https://github.com/alexandruianu)

### community

- [x] bspwm -- [Chrysostomus] (https://github.com/Chrysostomus) 
- [x] cinnamon -- [oberon2007] (https://github.com/oberon2007)
- [x] gnome -- [Ste74] (https://github.com/Ste74) 
- [ ] lxqt -- [Esclapion] (https://github.com/Esclapion)
- [ ] netbook -- [korrode] (https://github.com/korrode) 
- [x] pantheon -- [Ste74] (https://github.com/Ste74)
- [x] budgie --  [Ste74] (https://github.com/Ste74) 
- [x] deepin --  [oberon2007] (https://github.com/oberon2007)
- [x] fluxbox -- ?
- [x] i3 --  [oberon2007] (https://github.com/oberon2007)
- [ ] mate -- ?
- [ ] openbox --  [holmeslinux] (https://github.com/holmeslinux)
- [ ] lxde -- [korrode] (https://github.com/korrode)  ?
- [ ] jwm -- [holmeslinux] (https://github.com/holmeslinux)

### sonar

- [x] gnome-sonar -- [coffeeking](https://github.com/coffeeking), [philmmanjaro](https://github.com/philmmanjaro), [artoo](https://github.com/udeved) 
- [x] mate-sonar -- [coffeeking](https://github.com/coffeeking), [philmmanjaro](https://github.com/philmmanjaro), [artoo] (https://github.com/udeved) 

### netrunner

- [ ] kde-netrunner -- [netrunner] (https://github.com/netrunner-rolling)

**Comment by udeved** [comment]
Current sizes of the profiles:

~~~
780K    ./netrunner/kde-netrunner
372K    ./netrunner/lxqt-netrunner
1,2M    ./netrunner
32K     ./official/net
540K    ./official/kde
724K    ./official/xfce
1,3M    ./official
148K    ./shared/netrunner
356K    ./shared/sonar
264K    ./shared/manjaro
800K    ./shared
40K     ./minimal/net-minimal
880K    ./minimal/budgie-minimal
512K    ./minimal/kde-minimal
580K    ./minimal/xfce-minimal
356K    ./minimal/lxqt-minimal
2,4M    ./minimal
36K     ./.git/refs
4,0K    ./.git/branches
44K     ./.git/hooks
110M    ./.git/objects
8,0K    ./.git/info
40K     ./.git/logs
110M    ./.git
4,1M    ./sonar/gnome-sonar
4,0M    ./sonar/mate-sonar
8,1M    ./sonar
84K     ./community/gnome
832K    ./community/fluxbox
692K    ./community/netbook
3,5M    ./community/pantheon
20K     ./community/sysmenu
212K    ./community/cinnamon
512K    ./community/lxqt
5,8M    ./community/openbox
7,7M    ./community/mate
584K    ./community/lxde
2,4M    ./community/enlightenment
4,6M    ./community/jwm
292K    ./community/deepin
1,2M    ./community/i3
1,6M    ./community/bspwm
816K    ./community/budgie
31M     ./community
154M    .
154M    insgesamt
~~~

**Comment by Ste74** [comment]
Hi .. for pantheon rework the wallpaper to reduce size .. :) and update profile soon .. just a consideration .. budgie and gnome are more related .. at this time development of pantheon in arch is stopped .. ( seem the dev pantheon working not at same release , example wingpanel working only with release r93 :\ ) .So if nobody disagrees could adopt gnome profile for future versions.

**Comment by udeved** [comment]
Very good Ste :+1:

**Comment by oberon2007** [comment]
Thank you, @udeved - I have removed my name in some places, though ... ;) :laughing: 
@Ste74 did you see [this](https://forum.manjaro.org/index.php?topic=29949.msg248333#msg248333)?
Maybe contact 'cybermails' and/or download his ISO to check it out and maybe collaborate (or not ... ;) )?

**Comment by Ste74** [comment]
@oberon2007 .. no..  not see cybermails post :( ok .. If you think I can send MP for collaboration .. but you thinking?

**Comment by oberon2007** [comment]
I don't know Stefano. I haven't seen anything of this build, not even a screenshot. I just saw that post yesterday ...

**Comment by udeved** [comment]
Rob said on the forums:

>I'm not the Enlightenment profile maintainer any more and i won't be again in future.

>I was hoping Fassil would take over that role, but if he doesn't, then we have no Enlightenment edition, >the whole profile can be deleted for all i care.

**Comment by oberon2007** [comment]
Deleting sounds like a bad idea. It should be kept in any case in an 'unmaintained' folder - outside the iso-profile-packages. But reanimating will be so much easier when someone wants to make a new edition one day. Also it seems good to have an obvious place for profiles that need attention.

**Comment by udeved** [comment]
We have git history, no need for "unmaintained". 
If its unmaintained, we should remove it, if no mainrainer(fassil?) can be found.

**Comment by oberon2007** [comment]
I have removed two unneeded tiny icons in the i3 profile. I don't see a way to make it smaller without losing features... If you have suggestions? Otherwise it will need to stay at 1.2MB.

**Comment by udeved** [comment]
Its ok @oberon2007 

What are we gonna do with backgrounds?
communit-backgrounds package?

I'd like to have the maia background separately packages, and plasma5-maia depend on the background package.

**Comment by udeved** [comment]
If nobody tales care of recently readded OB, I gonna delete it.

**Comment by oberon2007** [comment]
Every edition will need its own package. **i3-**, **fluxbox-** and **deepin-wallpapers** already exist. I have even posted a template PKGBUILD here a while ago for everybody.

**Comment by udeved** [comment]
It be better if we collect the source links.
Stefano would have to tell where the pantheon wallpapers are coming from.

**Comment by oberon2007** [comment]
In the profiles you can even  use a symlink **/usr/share/backgrounds/default_background.jpg** and then change the actually used background in the package by renaming what you want to use.

**Comment by udeved** [comment]
I am all for establishing a no image rule in the profiles and usage of packages instead.

**Comment by udeved** [comment]
Pending deletion:

- [x] enlightenment -- ?
- [x] jwm -- [holmeslinux] (https://github.com/holmeslinux) ?
- [x] openbox --  [holmeslinux] (https://github.com/holmeslinux) ?

**Comment by udeved** [comment]
[uses desktop-settings package]  Profile

### official

- [ ] xfce
- [ ] net
- [ ] kde

### minimal

- [x] lxqt
- [ ] budgie
- [ ] net
- [ ] kde
- [ ] xfce

### community

- [ ] bspwm
- [ ] cinnamon
- [ ] enlightenment
- [ ] gnome
- [ ] jwm
- [ ] lxqt
- [ ] netbook
- [ ] pantheon
- [ ] budgie
- [ ] deepin
- [ ] fluxbox
- [ ] i3
- [ ] lxde
- [ ] mate
- [ ] openbox

### sonar

- [ ] gnome-sonar
- [ ] mate-sonar

### netrunner

- [x] kde-netrunner

**Comment by udeved** [comment]
## * Current sizes of the future skels, from desktop-settings repo:

### official

- [x] 4,0K    ./official/kde
- [x] 408K    ./official/xfce
- [x] 632K    ./official

### minimal

- [x] 196K    ./minimal/lxqt
- [x] 224K    ./minimal/kde
- [x] 264K    ./minimal/xfce
- [x] 688K    ./minima

### community

- [x] 52K     ./community/gnome
- [x] 396K    ./community/fluxbox
- [x] 344K    ./community/netbook
- [x] 804K    ./community/pantheon
- [x] 140K    ./community/cinnamon
- [x] 328K    ./community/lxqt
- [x] 316K    ./community/openbox
- [x] 420K    ./community/mate
- [x] 380K    ./community/lxde
- [x] 596K    ./community/enlightenment
- [ ] 1,7M    ./community/jwm
- [x] 64K     ./community/deepin
- [x] 464K    ./community/i3
- [ ] 1,3M    ./community/bspwm
- [x] 92K     ./community/budgie
- [ ] 7,2M    ./community

**Comment by udeved** [comment]
@oberon2007 

Can you migrate to desktop-settings for your profiles?

**Comment by oberon2007** [comment]
How does this work exactly? I gather that **<profile>-overlay/etc/skel** is now handled there. What happens with the content of **manjaro-tools-iso-profiles**? Do we remove there? Everything else remains there?

**Comment by udeved** [comment]
skels go in desktop-settings and removed in profiles.
There are packages in unstable for testing, just add the right one to your profile.

**Comment by udeved** [comment]
@philmmanjaro 

I packaged for now the contents of overlay/etc/skel per profile.

Next step should be to see, if we perhaps can have a common packages, that provides the (dot).files as base depend.

**Comment by philmmanjaro** [comment]
Ok, lets do it step by step. So far so good ;)

**Comment by udeved** [comment]
ToDO:

- [ ] check why sonar needs special sound login, no package?
- [ ] check where the sonar droid mono fonts comes from

**Comment by udeved** [comment]
@philmmanjaro 

We need to cleanup .git folder, and tell everybody to either rebase or clone at some point.
.git is still massive,and holds big stuff that was deleted.

**Comment by udeved** [comment]
Ihave packaged all removed icons and backgrounds in manjaro-background and manjaro-icons respectively. Please check your background and icons paths.

**Comment by philmmanjaro** [comment]
@udeved: you mean to delete the history and who worked on what? When you clone the git-repo, does it take long or are you only worried on the size .git folder has. Lets check if there is a way to optimize it first.

**Comment by cybermails** [comment]
@Ste74, @oberon2007, @philmmanjaro 
I am willing to adopt the gnome edition with some handholding since I'm brand new to building isos and maintaining profiles. What exactly would I have to do to maintain a profile? Is there a maintainer's guide or wiki available? Any advice is greatly appreciated. Thank you.

**Comment by udeved** [comment]
@philmmanjaro 
Preferrably not losing history, but yeah, we need to remove git objects, many hold images etc...
I already claned up as far as it goes.

You can compared a clone with this reference repo I mirrored to test.
It has naturally not many commits, but its .git folder is this...

~~~
32K     ./.git/refs
4,0K    ./.git/branches
44K     ./.git/hooks
4,8M    ./.git/objects
8,0K    ./.git/info
36K     ./.git/logs
5,1M    ./.git
~~~

So we have roughly 90 MB overhead, that have to be cloned initially.

**Comment by oberon2007** [comment]
Talking of history... The history of the deleted devel branch is lost, isn't it?

**Comment by udeved** [comment]
Nope, its somewhere in the git history when it was merged.

**Comment by philmmanjaro** [comment]
@cybermails: write me an e-mail with time-slots you might have time for a small IRC or Skype session. Then we can talk what is needed. The wiki has some pages but we are currently optimizing the profiles, so they slightly change on daily bases right now. The principle is already the same. It is not rocket science, so  you might have no issues to maintain a profile.

**Comment by philmmanjaro** [comment]
@udeved: we can mirror the current one as backup and then clean the history. In the bigger backup we have it still as reference for year 2015. So we have a new repo we can start fresh and the old to find out what we actually did. Thoughts?

**Comment by udeved** [comment]
New repo would be probably best in my view.
Current one is really messy in .git, and perhaps more difficult to clean than simply starting new one.

I suggest only "iso-profiles" for new repo name.

**Comment by udeved** [comment]
@philmmanjaro 

I misunderstood, you want to squash history, also fine I think.

**Comment by philmmanjaro** [comment]
@udeved: some like that: https://rtyley.github.io/bfg-repo-cleaner/

**Comment by udeved** [comment]
Yes, but I think, this solution needs all others to clone the repo again.

I partially did clean up .git

~~~
git -c gc.reflogExpire=0 -c gc.reflogExpireUnreachable=0 \
  -c gc.rerereresolved=0 -c gc.rerereunresolved=0 \
  -c gc.pruneExpire=now gc "$@"
~~~

**Comment by philmmanjaro** [comment]
and some results. Let me check with this method. I'll report back. A rebase is not needed.

**Comment by udeved** [comment]
http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository/1591174#1591174

**Comment by udeved** [comment]
http://stackoverflow.com/questions/3797907/how-to-remove-unused-objects-from-a-git-repository

related topics. ;)

**Comment by philmmanjaro** [comment]
well, I reduced it to 9MB in total, full log there.

**Comment by udeved** [comment]
Sounds good.

**Comment by philmmanjaro** [comment]
However it seems I've some conflicts:
```
git push
Enter passphrase for key '/home/phil/.ssh/id_rsa': 
Zähle Objekte: 23812, Fertig.
Delta compression using up to 4 threads.
Komprimiere Objekte: 100% (9537/9537), Fertig.
Schreibe Objekte: 100% (23812/23812), 8.61 MiB | 258.00 KiB/s, Fertig.
Total 23812 (delta 11294), reused 23812 (delta 11294)
To git@github.com:manjaro/manjaro-tools-iso-profiles.git
 + 858f61b...9b75772 master -> master (forced update)
 + 2e82e0d...50a0ac6 profiles/15.09 -> profiles/15.09 (forced update)
 + 1d5900e...ae57495 profiles/15.12 -> profiles/15.12 (forced update)
 + 0ae275f...099ba29 0.9.10 -> 0.9.10 (forced update)
 + bfc506d...8b2b505 0.9.11 -> 0.9.11 (forced update)
 + ab07c2e...4954205 0.9.11-2 -> 0.9.11-2 (forced update)
 + 54bf568...ffc5fba 0.9.13.2-1 -> 0.9.13.2-1 (forced update)
 + 0280386...9e85525 0.9.9 -> 0.9.9 (forced update)
 + e4cc6f6...02026b0 15.09 -> 15.09 (forced update)
 + 9010599...ba454fe 15.12 -> 15.12 (forced update)
 + d457829...ba3f947 manjaro-iso-profiles-0.8.11 -> manjaro-iso-profiles-0.8.11 (forced update)
 ! [remote rejected] refs/pull/103/head -> refs/pull/103/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/104/head -> refs/pull/104/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/12/head -> refs/pull/12/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/15/head -> refs/pull/15/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/15/merge -> refs/pull/15/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/16/head -> refs/pull/16/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/16/merge -> refs/pull/16/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/17/head -> refs/pull/17/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/17/merge -> refs/pull/17/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/18/head -> refs/pull/18/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/19/head -> refs/pull/19/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/20/head -> refs/pull/20/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/20/merge -> refs/pull/20/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/23/head -> refs/pull/23/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/23/merge -> refs/pull/23/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/24/head -> refs/pull/24/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/25/head -> refs/pull/25/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/27/head -> refs/pull/27/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/28/head -> refs/pull/28/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/29/head -> refs/pull/29/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/3/head -> refs/pull/3/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/31/head -> refs/pull/31/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/34/head -> refs/pull/34/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/38/head -> refs/pull/38/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/39/head -> refs/pull/39/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/42/head -> refs/pull/42/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/42/merge -> refs/pull/42/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/43/head -> refs/pull/43/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/46/head -> refs/pull/46/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/47/head -> refs/pull/47/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/48/head -> refs/pull/48/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/49/head -> refs/pull/49/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/5/head -> refs/pull/5/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/51/head -> refs/pull/51/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/51/merge -> refs/pull/51/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/52/head -> refs/pull/52/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/53/head -> refs/pull/53/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/58/head -> refs/pull/58/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/59/head -> refs/pull/59/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/6/head -> refs/pull/6/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/60/head -> refs/pull/60/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/64/head -> refs/pull/64/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/65/head -> refs/pull/65/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/65/merge -> refs/pull/65/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/68/head -> refs/pull/68/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/69/head -> refs/pull/69/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/7/head -> refs/pull/7/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/7/merge -> refs/pull/7/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/71/head -> refs/pull/71/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/72/head -> refs/pull/72/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/72/merge -> refs/pull/72/merge (deny updating a hidden ref)
 ! [remote rejected] refs/pull/73/head -> refs/pull/73/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/77/head -> refs/pull/77/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/79/head -> refs/pull/79/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/8/head -> refs/pull/8/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/80/head -> refs/pull/80/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/81/head -> refs/pull/81/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/83/head -> refs/pull/83/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/86/head -> refs/pull/86/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/88/head -> refs/pull/88/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/91/head -> refs/pull/91/head (deny updating a hidden ref)
 ! [remote rejected] refs/pull/93/head -> refs/pull/93/head (deny updating a hidden ref)
error: Fehler beim Versenden einiger Referenzen nach 'git@github.com:manjaro/manjaro-tools-iso-profiles.git'
```

**Comment by udeved** [comment]
$ git gc --aggressive

Try?

**Comment by philmmanjaro** [comment]
Yeah, well it is now down to `6,4M	manjaro-tools-iso-profiles/.git`. Everybody has to checkout it new. Else you upload the history once again. Files are the same.

**Comment by udeved** [comment]
Has it oberon's push in it? He has pushed stuff some minutes ago.

**Comment by udeved** [comment]
All, fine, it was your invisible commit, no oberon.

.git is at 6.6 MB after clone.

**Comment by philmmanjaro** [comment]
@udeved: please compare your local copy with the new checkout in regards of files. They should be the same.

**Comment by udeved** [comment]
At first glance, it looks good...


~~~
diff: manjaro-tools-iso-profiles/community/cinnamon/cinnamon-overlay/usr/share/themes/Adwaita/backgrounds/adwaita-timed.xml: Datei oder Verzeichnis nicht gefunden
diff: iso-profiles/community/cinnamon/cinnamon-overlay/usr/share/themes/Adwaita/backgrounds/adwaita-timed.xml: Datei oder Verzeichnis nicht gefunden
Only in iso-profiles/community/deepin/deepin-overlay/etc: sudoers.d
Only in iso-profiles/community/deepin/deepin-overlay/var/lib/AccountsService/icons: manjaro-circle.png
Only in iso-profiles/community/deepin/deepin-overlay/var/lib/AccountsService/icons: olive-green.png
Files manjaro-tools-iso-profiles/community/deepin/live-overlay/etc/samba/smb.conf and iso-profiles/community/deepin/live-overlay/etc/samba/smb.conf differ
Only in manjaro-tools-iso-profiles/community/deepin/live-overlay/etc/skel/.config/autostart: live-session.desktop
Only in manjaro-tools-iso-profiles/community/deepin/live-overlay/etc/skel/.config/autostart: pulseaudio-ctl.desktop
Only in iso-profiles/community/fluxbox/fluxbox-overlay: root
Files manjaro-tools-iso-profiles/community/fluxbox/live-overlay/etc/issue and iso-profiles/community/fluxbox/live-overlay/etc/issue differ
Files manjaro-tools-iso-profiles/community/fluxbox/live-overlay/etc/samba/smb.conf and iso-profiles/community/fluxbox/live-overlay/etc/samba/smb.conf differ
Only in iso-profiles/community/fluxbox/live-overlay/root: .gtkrc-2.0
Only in iso-profiles/community/fluxbox/live-overlay: usr
Only in manjaro-tools-iso-profiles/community/fluxbox/root-overlay/etc: skel
diff: manjaro-tools-iso-profiles/community/i3/i3-overlay/usr/share/backgrounds/default_background.jpg: Datei oder Verzeichnis nicht gefunden
diff: iso-profiles/community/i3/i3-overlay/usr/share/backgrounds/default_background.jpg: Datei oder Verzeichnis nicht gefunden
Files manjaro-tools-iso-profiles/community/i3/live-overlay/etc/issue and iso-profiles/community/i3/live-overlay/etc/issue differ
Files manjaro-tools-iso-profiles/community/i3/live-overlay/etc/skel/.i3/config and iso-profiles/community/i3/live-overlay/etc/skel/.i3/config differ
Only in iso-profiles/community/i3/live-overlay: root
Only in manjaro-tools-iso-profiles/community/i3/live-overlay/usr: bin
Only in iso-profiles/community/i3/live-overlay/usr: share
Only in manjaro-tools-iso-profiles/community/i3/root-overlay/etc: skel
diff: manjaro-tools-iso-profiles/community/netbook/xfce-overlay/usr/share/xfce4/backdrops/default.jpg: Datei oder Verzeichnis nicht gefunden
diff: iso-profiles/community/netbook/xfce-overlay/usr/share/xfce4/backdrops/default.jpg: Datei oder Verzeichnis nicht gefunden
diff: manjaro-tools-iso-profiles/community/pantheon/pantheon-overlay/usr/share/xfce4/backdrops/default.jpg: Datei oder Verzeichnis nicht gefunden
diff: iso-profiles/community/pantheon/pantheon-overlay/usr/share/xfce4/backdrops/default.jpg: Datei oder Verzeichnis nicht gefunden
Files manjaro-tools-iso-profiles/.git/config and iso-profiles/.git/config differ
Files manjaro-tools-iso-profiles/.git/index and iso-profiles/.git/index differ
Files manjaro-tools-iso-profiles/.git/logs/HEAD and iso-profiles/.git/logs/HEAD differ
Files manjaro-tools-iso-profiles/.git/logs/refs/heads/master and iso-profiles/.git/logs/refs/heads/master differ
Files manjaro-tools-iso-profiles/.git/logs/refs/remotes/origin/HEAD and iso-profiles/.git/logs/refs/remotes/origin/HEAD differ
Only in iso-profiles/.git/objects/pack: pack-a36116afc49f99382c8d0d07f6a76d17c06fb04a.idx
Only in iso-profiles/.git/objects/pack: pack-a36116afc49f99382c8d0d07f6a76d17c06fb04a.pack
Only in manjaro-tools-iso-profiles/.git/objects/pack: pack-cb9ceef993c442098a26b360e3403985391bcd82.idx
Only in manjaro-tools-iso-profiles/.git/objects/pack: pack-cb9ceef993c442098a26b360e3403985391bcd82.pack
Files manjaro-tools-iso-profiles/.git/packed-refs and iso-profiles/.git/packed-refs differ
Only in manjaro-tools-iso-profiles/.git: qgit_cache.dat
Files manjaro-tools-iso-profiles/.git/refs/heads/master and iso-profiles/.git/refs/heads/master differ
diff: manjaro-tools-iso-profiles/minimal/xfce-minimal/xfce-overlay/usr/share/xfce4/backdrops/default.jpg: Datei oder Verzeichnis nicht gefunden
diff: iso-profiles/minimal/xfce-minimal/xfce-overlay/usr/share/xfce4/backdrops/default.jpg: Datei oder Verzeichnis nicht gefunden
diff: manjaro-tools-iso-profiles/official/xfce/xfce-overlay/usr/share/xfce4/backdrops/default.jpg: Datei oder Verzeichnis nicht gefunden
diff: iso-profiles/official/xfce/xfce-overlay/usr/share/xfce4/backdrops/default.jpg: Datei oder Verzeichnis nicht gefunden
diff: manjaro-tools-iso-profiles/sonar/gnome-sonar/gnome-overlay/usr/share/themes/Adwaita/backgrounds/adwaita-timed.xml: Datei oder Verzeichnis nicht gefunden
diff: iso-profiles/sonar/gnome-sonar/gnome-overlay/usr/share/themes/Adwaita/backgrounds/adwaita-timed.xml: Datei oder Verzeichnis nicht gefunden
~~~

**Comment by philmmanjaro** [comment]
@udeved: I recommend to use `diff -Npur <local> <remote> > changes.diff`. You should have only differences in the **.git** folder.

**Comment by udeved** [comment]
If I do this command, I get not only .git changes in the diff.

**Comment by philmmanjaro** [comment]
Then it is fine. No file differences in our git-repo then. We minimized **.git** from 127 MB to 7 MB. Satisfied?

**Comment by udeved** [comment]
Very well. :)

**Comment by oberon2007** [comment]
Since Ringo has stopped maintaining **Cinnamon**, I would be very happy to take over. On the other hand, as I have said before, I prefer to no longer do **Fluxbox**. I've made an announcemen about that in the forum and I hope that one of the other flux-tinkerers will like to do that in the future :)

**Comment by philmmanjaro** [comment]
@oberon2007: totally fine with me.

**Comment by oberon2007** [comment]
OK! :)
