### ISSUE TITLE
nm-applet not appear in budgie panel 

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools-iso-profiles#102]
Hi team .. i need to modifier nm-applet.desktop now in the option i see 
NotShowIn=KDE;GNOME;
well in this configuration the applet in budgie not appear .. 
Possible fork nm-applet-budgie-manjaro ? to remove GNOME key ?

**Comment by oberon2007** [comment]
Can you maybe use a different .desktop file in **~/.config/autostart** ?

**Comment by Ste74** [comment]
Yes i can but this work only in my iso .. if an user install budgie itself in a existing installation the applet not work ...

**Comment by oberon2007** [comment]
yes, I see.

**Comment by philmmanjaro** [comment]
The question is , why shouldn't it been shown on these two IDEs. It is a Gnome application after all.

**Comment by Ste74** [comment]
lol right observation

**Comment by philmmanjaro** [comment]
@Ste74: please read also [this](https://plus.google.com/+Solus-Project/posts/P7fzeQEWEbt):
`Ship our own nm-applet.desktop launcher until we have our own network settings`

**Comment by Ste74** [comment]
Yes but my english is bad .. do slusos mean with this ? In a future budgie desktop provide a nm-applet for all ?

**Comment by philmmanjaro** [comment]
**v10.2** fixed it already. It ships its own nm-applet.desktop already. Please check your **budgie-desktop** file with **pacman -Ql**.

**Comment by Ste74** [comment]
![virtualbox_budgie_09_01_2016_19_13_53](https://cloud.githubusercontent.com/assets/11218234/12217583/3c89ac76-b705-11e5-904d-b3dad40b86b1.png)
is strange i build the last ..

**Comment by ikeydoherty** [comment]
Perhaps we can start cross-referencing our Budgie issues here? :)

**Comment by Ste74** [comment]
Hi @ikeydoherty, you are welcome :)

**Comment by philmmanjaro** [comment]
Hi @ikeydoherty, already fixed with `--sysconfdir=/etc`.

**Comment by ikeydoherty** [comment]
Ack :)
