### ISSUE TITLE
wallpaper packages update problem

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#106]
Have you considered the fact that there is this little problem with delivering the wallpapers in a package:
Let say you add the package **profile-wallpapers** to your profile, containing pictures A, B and C.
People probably like your wallpapers and keep using them.
But now for you new release you or the next maintainer of that edition decides to use pictures D, E and F in the updated package... and when the package gets updated people's wallpapers will suddenly be removed from their systems ;) That will not be very popular!

**Comment by oberon2007** [comment]
You will either have to keep old wallpapers forever or find a new name for the package for every release ... ?

**Comment by udeved** [comment]
Uhm I would assume people who collect wallpapers keep them in their $HOME?
Basically, its up to the maintainer, I just packaged the wallpapers, a package of acceptable ~1.5 MB.
If we continue with asking, we gonna ask forever to optimize a profile. Now its done.

**Comment by oberon2007** [comment]
The question is what 'optimized' means. Your goal seems to be that the iso-profile repo is kept as small in size as possible (I don't really understand why). Should we not also look for an optimized way to maintain the profiles and to provide them to the users? To me it looks like it is getting a lot more complicated for the maintainers, especially for those who are not packaging themselves, and if we have situations where people suddenly lose the wallpaper they are currently using, this is not really ideal I think ... ;)

**Comment by udeved** [comment]
Perhaps a motivation for them to learn packaging.
The profiles repo was massive, and still has a massive 117 MB .git dir.
When there is a build server available, things should become easier.

The other option was to separate community profiles in a separate repo, but its really a pain in the a** to upload community profile package, which contains stuff, that should be provided by packages anyway.
