### ISSUE TITLE
workflow with new structure

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#107]
The new situation makes me quite unhappy from a maintainer's point of view.
Playing around with config and trying out stuff in a workflow of consecutive testbuilds has become really awkward with the /skel folder been transformed into a package.
For the development experiments I have to recreate an overlay /skel (I can certainly not update the package every few hours). But every time I want to push changes I will have to remove the folder again and copy it over to the other repo in order for the package to be up-to-date. :-/
The other unpleasant thing is config for the live environment, which I definitely need in i3 for slightly different /skel for a variety of config reasons. But that one is still in the profiles repo. So I have two places now with almost the same but slightly different stuff.

**Comment by ringo32** [comment]
what would i say about :) some are fan some are not.. dont think you need to repack every time if you play with it ? flexibility is on low level indeed..

**Comment by udeved** [comment]
I actually don't really care, it can't go on like this, we get in another year a totally big unusable repo, it grows worse and worse, something had to be done about it.

**Comment by udeved** [comment]
If you are that unhappy, nothing prevents you to fork the repo, and grow it big with your profiles until unusable when cloning, but please not in a common repo that is supposed to be used by many users, which we may want to directly clone for profile generation whatever we plan.

**Comment by Esclapion** [comment]
Until now, I thought this repo was more for maintainers than for users.

**Comment by udeved** [comment]
Well, aim would be to open up iso building to community, but this requires that community builds profile against packages. They probably rad enough the moment they read "use git" If they then have to pull 120 MB repo, its already over before it started.
We need more help, we can draft it in community.

**Comment by Esclapion** [comment]
How many time to pull 120 MB ? For me, < 30"

**Comment by udeved** [comment]
Yes, sure, still initial pull of 90 MB overhead, which has been accumulated with images in git history.
However, pulling a profiles package now is fast, and buildiso also works with installed profiles package and no git repo..

**Comment by udeved** [comment]
I don't get why nobody gets behind the advantage of using skel packages.
You can develop skel packages on your running system and you don't have to build iso everytime you change something in skel.
Create new test user on your system and test it directly. makepkg is fully sufficient to build and install the skel package. This reduces the need to build iso just for the sake of testing some DE settings stuff.
Its much quicker development now.
The disadvantage of using files in overlay is, that these files are not accounted for by any package, and if some pakage provides these files, changes to the file in overlay are lost if there is a package update. So overlay is good for some purposes, but its better to deploy files with packages in most cases.

**Comment by udeved** [comment]
Further, @oberon2007 , if you want to have skel in the profile for whatever reason, symlink them and put the symlink to gitignore, You workflow is uhm, suboptimal.

**Comment by oberon2007** [comment]
That's a good idea. Didn't think about gitignore :)
Apart from that I see your points. It's maybe just about getting used to someting different now ... ... ;)

**Comment by udeved** [comment]
In fact nothing changed, we just package the skels. 
How you develop your skel is up to you, and if you want to build iso to test skel, or develop and test skel on your system. :)

**Comment by oberon2007** [comment]
Exactly. My way of thinking and working needs to change. :laughing:
I'll adjust to it, it's fine. :)

**Comment by Esclapion** [comment]
With a link, OK. But if we must build a package (who will do that and when ?) to do a modification, it's impracticable.
Anyway, we have two git branches to manage instead of one, it's absolutely not simpler.

**Comment by udeved** [comment]
It is simpler in the long run.
We got one repo for the profiles, and one for skels, which makes them reusable.
Plus quicker development of skels, since you can test them on the system.
Building the packages is really not the problem.

**Comment by udeved** [comment]
Basically, there is absolutely no need to have skel symlinks in the profile, but if you want them do it, just don't push them, or else your build fails eventually due to filesystem conflicts.

**Comment by Esclapion** [comment]
"Building the packages is really not the problem". I asked who and when ?

For the moment, it seems to me a very slow cycle.

**Comment by udeved** [comment]
I told you yesterday, that we gonna have a build server. ;)

**Comment by udeved** [comment]
https://github.com/manjaro/desktop-settings/issues/2

I don't see why people can't run 
    makepkg -sri

to test their package locally with a new user, instead of building the iso in much more time.

**Comment by ringo32** [comment]
wat would it be if a manjaro user want too make a costumized iso ?  as ajstyle showed have to make my own mate-setting, so i dont have to use the repo..

**Comment by udeved** [comment]
fork desktop-settings, or directly work in the manjaro repo. Would be best for packaging.

**Comment by philmmanjaro** [comment]
Hi guys, to clear some up about skel. Put whatever dot file needed into the live overlay. It will never make it on the installed system anyway. Manjaro tools should support that. Desktop settings are designed to be used for the user. 

In the beginning we have for sure more commits and everybody needs first to adopt. We need rules everybody can follow, simple like that.

**Comment by holmeslinux** [comment]
hello guys, i have many doubts with the new structure. from what i understand i will have to always build the package [b]manjaro-jwm-settings[/b]. creating this package? i do not know do this! 

however, i would like to learning how to create...

someone could explain?

vlw fwi, Holmes :)

**Comment by coffeeking** [comment]
hi
I'll settle for my mate profile booting to the desktop. I'm just about 
ready to rip lightdm out of there and replace it with gdm, if only to 
test it. The gnome profile now boots, but there's no speech. I'm trying 
to figure that one out now. Why must there always be something that goes 
wrong ... *sigh*
Don't mind me, just ran out of coffee. Going to get more before I tackle 
this one.
Thanks
Kendell clark
