### ISSUE TITLE
[root-overlay|etc/skel] conflicts with desktop-settings

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#108]
Since we still have some skel files in **root-overlay** some **desktop-settings** packages conflict now.

**Comment by philmmanjaro** [comment]
See also: https://github.com/manjaro/desktop-settings/issues/4

**Comment by philmmanjaro** [comment]
dbd8ed7ae83ac8fbffb6f625901600092b14b5ad

**Comment by udeved** [comment]
https://github.com/manjaro/desktop-settings/commit/cf57c2217b609a7ed31e3ea8939f6eafdb293975
