### ISSUE TITLE
Xfce needs updated wallpapers

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#109]
The **xfce4-artwork** (debian) package dates from April 2011 and the pictures are neither special, nor classic nor beautiful nor of good quality... ;)
Why don't we collect some of the cool wallpapers that keep popping up in the forum, or use the newer ones by UgoYak (numix-reborn), or ask the community for their opinion? or a competition?
For my feeling it would also be nice to find a replacement for the default manjaro-xfce-wallpaper. We have seen it for a long time now, don't you think? ;)

**Comment by udeved** [comment]
Good idea, I suggest a pure image repo we can use for packaging backgrounds.
So we can remove the temporary artwork folder in desktop-settings

**Comment by philmmanjaro** [comment]
I'm always open for new wallpapers or designs. Lets start a wallpaper contest and we will see what will win. We did that one year ago and got UgoYak's nice work ;) Using git for collecting wallpapers might not be so good. Maybe we store them on sf.net or some picture platform, but git is also possible. Depends. Thoughts?

**Comment by udeved** [comment]
A filesysrver is always best for this. pics out of vcs. 
I was just pointing out, the artwork folder in desktop-settings should be resolved and deleted when we found new places for icons and backgrounds.

@oberon2007 

Can you please look at the awoken OB stuff in artwork? Do we need this? Is this not already packaged? Do you know?

**Comment by oberon2007** [comment]
@Holmes took and adapted some icons from the AwOken icon theme for oblogout. So, thei're not part of the original theme. If OB wants to use the **oblogout-manjaro** package I can include them there, if Holmes prefers the traditional **oblogout** package, I don't know. It would be possible to package them with **awoken-icon-theme** or with **awoken-icon-theme-light** (they are both my packages anyway) but I doubt that Holmes wants to install the whole icon theme...

**Comment by oberon2007** [comment]
If desired I could also package just 'AwOken White' alone together with the oblogout-theme...
