### ISSUE TITLE
Add infinality-bundle patch in budgie and gnome

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools-iso-profiles#110]
Hi Team , i dislike the rendering font in gnome and budgie edition . I can add the Infinality-bundle or for some reason it is better than not?

**Comment by oberon2007** [comment]
Why is infinality-bundle not even in the AUR? Is there a copyright issue with it?

**Comment by philmmanjaro** [comment]
Yep, don't use it or publish it in any form. If distributed please remove it from your ISO.

**Comment by Ste74** [comment]
Oh .. you mean for MS font .. when i submit that i have thinking only for rendering and not for the pkg contain...
