### ISSUE TITLE
Remove all symlinks in profiles

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#111]
Task: Remove all symlinks in profiles, and let manjaro-tools read from iso-profiles-base package install location instead.

**Comment by oberon2007** [comment]
Can you explain what still needs to be done here? I'm afraid I don't understand...

**Comment by udeved** [comment]
Its a note, that ideally, we simply hide the symlinked stuff, by removing it and reading it from always installed iso-profiles-base package.
