### ISSUE TITLE
.desktop files in /usr/share/applications

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#112]
@udeved you have deleted some .desktop files from fluxbox and deepin profiles. They are needed. What to do? I need two other ones for Cinnamon aswell...!

**Comment by philmmanjaro** [comment]
Can you point me to the git-commits?

**Comment by oberon2007** [comment]
I just realized that all the /usr dirs are gone ... ;) Will try to find it.

**Comment by udeved** [comment]
There is always a backup...
https://github.com/manjaro/manjaro-tools-iso-profiles/tree/profiles/15.12

**Comment by udeved** [comment]
Do you mean this one?
https://github.com/manjaro/desktop-settings/tree/master/community/fluxbox/skel/.local/share/applications

**Comment by oberon2007** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles/commit/8d911ca21c8068888ae5bd5858389ebf7d5dc1ca

**Comment by oberon2007** [comment]
I have just tried in cinnamon to move the .desktop files to **.local/share**. The menu doesn't find them there ...

**Comment by philmmanjaro** [comment]
If needed in this [tarball](https://github.com/manjaro/manjaro-tools-iso-profiles/archive/062096b1358d1a96bebc1f5d5fd461c928247249.zip) you find your missing files. And yes, not every launcher or menu works with **.local/share**.

**Comment by philmmanjaro** [comment]
@oberon2007: however it should work with Cinnamon, though. Check [this](http://www.linuxmintusers.de/index.php?topic=9131.0).

**Comment by oberon2007** [comment]
So where should I re-add them? Or shall we have the install scripts move them to **/usr/share**?

**Comment by udeved** [comment]
its should work with xdg comliant DEs.

**Comment by oberon2007** [comment]
well. it doesn't. maybe restart or relog is needed ... ... :-/

**Comment by udeved** [comment]
Yes, add a launchers folder in your fluxbox, I'll make the pkgbuild work with it.

**Comment by oberon2007** [comment]
ok. sounds good :)

**Comment by udeved** [comment]
I am pretty sure cinnamon is xdg compliant.
I mean, the sort of gnome guys invented the xdg thingy.

**Comment by udeved** [comment]
@oberon2007 

Why do you bring back unlocalized Desktop/*.desktop?

Its handled by script.
https://github.com/manjaro/desktop-settings/tree/master/shared/live

**Comment by philmmanjaro** [comment]
@udeved: since we have now multible repositories and a really fast development speed currently, it would be nice to have the exact commits pointed to to have it easier to relate on the issue.

**Comment by udeved** [comment]
All fine, file got deleted again.

@philmmanjaro 

Full view on script might tell more than 2 or 3 commits, I think.

**Comment by philmmanjaro** [comment]
@udeved: I don't meant the script, however I meant the commit you had referenced to made by @oberon2007 .

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles/commit/3b6ce1a4c9cbb4a00d51ca307b97a56fc9335258

All fine, should have been removed in same commit.


I mande iso-profiles-base depends of manjaro-tools-iso package in preparation for 0.10.1

**Comment by udeved** [comment]
On topic xdg, lxqt has a nice overview.

http://s18.postimg.org/rdccj1im1/xdg.png

**Comment by udeved** [comment]
I'd be interesting to have a 
    printenv

 output overview for each DE/WM

**Comment by udeved** [comment]
Lets have a list of DE which do not read ~/.local/share/applications
