### ISSUE TITLE
/live/skel/Desktop

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#113]
At the moment neither the **live-script** nor .desktop files in **desktop-settings/.../live/skel/Desktop** seem to create any Desktop entries in the live environment. (manjaro-tools reverted to commit https://github.com/manjaro/manjaro-tools/commit/74dd93f4c18354b612c0ab8df9e29a6419751db5 for the current [issue](https://github.com/manjaro/manjaro-tools/commit/4cd0f34c69b151d52b7973c405fcacb5d59ea271#commitcomment-15583702) with user creation)
![desktop](https://cloud.githubusercontent.com/assets/11800714/12481509/074e5860-c04a-11e5-9049-7ff1dca2e752.png)

**Comment by oberon2007** [comment]
Obviously the live/skel folder is not being copied over at all. There is another config for nemo that I have placed there and it is not present in the live user.

**Comment by oberon2007** [comment]
Oh. I see. The PKGBUILD for desktop-settings is not ready obviously ;)
Anyway the live scripts doesn't seem to do its job of creating the desktop-links :)

**Comment by oberon2007** [comment]
Ok. I just realize that we now have a **manjaro-live-skel** package, I didn't get that. But then, how can I add any custom config to that? Looks llike things are right now I'll have to build a different live package?

**Comment by oberon2007** [comment]
And still, this brings me back to the original issue there. manjaro-live-skel is installed in the ISO I just built and no desktop items were created! ;)

**Comment by oberon2007** [comment]
I just ran the desktop-items entry in autostart manually. Obviously for some reason it was not autostarted by cinnamon...

**Comment by udeved** [comment]
1st question.
Why is there a need to customize the live skel for cinnamon?

2nd:
Why does fluxbox menugen need separate live skel? It looks like the same as OB menugen.

**Comment by oberon2007** [comment]
I'm concentrating on Cinnamon right now.
Even if we fix the autostart for the desktop-items in Cinnamon, I think the reult is an ugly and crowded desktop. The icons are randomly scattered (you can fix the placement of the items with a config file for nemo in /.config/nemo 
My solution would have been a single extra icon for manjaro-welcome with a nice custom icon that looks good with the rest. The installers can be launched from there. Users guide I'm not sure if I would absolutely want that on the desktop, too, but, maybe. In any case it's a limitation if there is no way to customize the desktop for different flavors I think.
Right now it looks like this:
![crowded](https://cloud.githubusercontent.com/assets/11800714/12482272/0659c836-c04f-11e5-9fea-7aad8a223b3a.png)
The trash icon is in the middle of everything else, some icons are not available, icon-names are not nice.
I'd prefer it a lot to look like this:
![cleaner](https://cloud.githubusercontent.com/assets/11800714/12482276/10113a4e-c04f-11e5-85a9-7ee283cf624b.png)

**Comment by oberon2007** [comment]
fluxbox:
The installers. You want them in the live-environment and not in the final install.
```
diff -rupN live/skel/.config/fbmenugen/schema.pl skel/.config/fbmenugen/schema.pl 
--- live/skel/.config/fbmenugen/schema.pl	2016-01-21 15:11:16.939763788 +0100
+++ skel/.config/fbmenugen/schema.pl	2016-01-12 17:55:34.791185474 +0100
@@ -28,12 +28,6 @@
 require "$ENV{HOME}/.config/fbmenugen/config.pl";
 
 our $SCHEMA = [
-{item =>	['sudo calamares',		'Install Manjaro (Calamares)','calamares']},
-{item =>	['sudo thus',			'Install Manjaro (Thus)','thus']},
-{item =>	['sudo lxterminal -e setup',	'Install Manjaro (CLI)',]},
-
-{sep => 'undef'},
-
 {item =>	['lxterminal',			'Terminal',		'terminal']},
 {item =>	['pcmanfm',			'File Manager',		'file-manager']},
 {item =>	['gksu pcmanfm',		'Root File Manager',	'root-file-manager']},
@@ -82,10 +76,6 @@ our $SCHEMA = [
   {raw => q([restart] (Restart))},
 {end_cat => undef},
 
-# Time Settings (GUI)
-# TimeSet (CLI)
-# menu_de neu!!
-
 {sep => 'undef'},
 
 {item =>	['oblogout_blur',		'Exit',			'shutdown/restart']}
```

**Comment by oberon2007** [comment]
autostart in Cinnamon is still a mystery: **manjaro-welcome** is autostarted fine, but not the **live-session** script.

**Comment by udeved** [comment]
Well, its a live session, items are simply symlinked to desktop. 
Why don't you customize the layout in DE> layer?

I mean, why do you need to customize live session? I don't understand.
live session has installers additionally, nothing else.

**Comment by udeved** [comment]
Regarding fluxbox, I think the menugen is not really understood. Where is the config.pl?

Look at my lxqt profiles, OB menugen is run in DE layer, and inherited by live layer.
In live layer, it generates installer entries too, because the launchers exist.

**Comment by oberon2007** [comment]
So that means I have no way to get rid of the desktop items produced by the live-script?

**Comment by oberon2007** [comment]
I'm not maintaining fluxbox for now. It's too much. :)

**Comment by udeved** [comment]
I asked why you need to customize live session skel for cinnamon. 
I don't understand the reason.

**Comment by oberon2007** [comment]
I want to achieve this: https://github.com/manjaro/manjaro-tools-iso-profiles/issues/113#issuecomment-173576533
If I can do that without customizing live session skel please tell me how.

**Comment by udeved** [comment]
So why a live/etc/skel/.config/nemo?

Why not DE/etc/skel/.config/nemo ?

I don't understand why it has to be in live layer.

**Comment by oberon2007** [comment]
The config file lists all the desktop items present. they will not be the same in both cases.

**Comment by udeved** [comment]
Seriously, aligning desktop items is the problem?
Argh!

![live] (http://s13.postimg.org/eydaxynpj/live.png)

**Comment by oberon2007** [comment]
Look at the screeshot I posted! It's a mess!

**Comment by udeved** [comment]
Your screenshot says, you don't have the items installed that are missing icons.

**Comment by oberon2007** [comment]
The other one! That one shows what will happen when the script actually works.

**Comment by oberon2007** [comment]
I am not stupid, @udeved !
Icon-theme-maia is installed. i said that the order and placement of the icons is a mess.
I don't want all that items on the desktop.
I want to be able to use a desktop item for manjaro-welcome with a customized icon. I can only do that when I am able to add a custom .desktop file with a specific icon-path.
I'll figure it out. I will just create my own desktop-settings package - or leave it altogether.
It sucks that you have to fight for every singly customization you want to make.
The system is getting totally stiff now and it's getting extremely hard to customize anything.

**Comment by oberon2007** [comment]
of course thus and calamares are installed! how could they not be??

**Comment by oberon2007** [comment]
cinnamon obviously doesn't display the icons when they are links and not real .desktop files. It's just not the same in any DE as in lxqt.

**Comment by udeved** [comment]
Cinnamon obviously does something different to xdg complaint DE such as kde or lxqt.

Nobody said your are stupid, I just can't believe all the fuzz about item alignment in a live session.

**Comment by oberon2007** [comment]
You are not reading what I wrote! It's not about alignment.

**Comment by udeved** [comment]
I understood that item links are not created in cinnamon live, because I just built cinnamon.
So what? Will be fixed. :)

However, I still don't get why you have a need to customize live session skel.

**Comment by oberon2007** [comment]
1. too many items
2. items in random order
3. not possible to customize icons. (manjaro-welcome will be displayed as a questionmark when it is a real .desktop file)

**Comment by udeved** [comment]
Why do you need to customize icons for live session?

**Comment by udeved** [comment]
We got to stop deplyoing package fixes on iso.
If welcome does not show an icon by default, then it should be fixed in welcome package.

**Comment by udeved** [comment]
~~~
[Desktop Entry]
Terminal=false
Type=Application
Categories=GNOME;GTK;System;
StartupNotify=false
Name=Manjaro Welcome
Exec=manjaro-welcome
Icon=gtk-info
Comment=The Manjaro Welcome utility.
Comment[pl]=Witamy w Manjaro Linux !
Name[de_DE.UTF-8]=Manjaro Welcome
Name[pl]=Witamy w Manjaro
~~~

I think this is only started in gnome?
I think maia icons provide gtl-info.

**Comment by udeved** [comment]
Btw, Bernhard, do you know Meld package?
I allows you to easily diff files or folders.
Comes in handy to compare eg skel with live/skel. ;)

**Comment by udeved** [comment]
I think I know whats going on.

![cinnamon-live] (http://s29.postimg.org/ce8uepe9j/cinnamon_live.png)

The items are autostarted, it rather an issue of displaying the items.

I think a special cinnamon live 100_manjaro-live.gschema.override would solve it, providing a list of items. Perhaps this can be reused by other gtk3 based DE.

**Comment by ringo32** [comment]
dpms is for the blackscreen, but live is also a gschema for block the screensaver lock, .. symlink works under cinnnamon desktop, but if the starter not is marked as Start icon wil not show, i dont know if it to do on X-Cinnamon session in starter , but on the symlink icons normally can work. if not marked  to start then icon dont show.

**Comment by udeved** [comment]
I think we just need cinnamon-live.skel with launchers.
For some reason, autostart works the standard way, but cinnamon additionally needs the lauchers set in dconf.

**Comment by ringo32** [comment]
but desklets in dconf is a desklet applications of cinnamon , what has that to do on  live-session.desktop ?

**Comment by udeved** [comment]
So where are desktop items enabled in dconf schema?
Obviously, it needs special dconf override.

**Comment by ringo32** [comment]
if you see manjaro-documentation gives a correct icon , if oberon do right click and preferences and enable the startup or something the icon will show

normally

**Comment by udeved** [comment]
Yes, but thats stored in dconf.
We just have to figure out right id and key

**Comment by udeved** [comment]
And if we need special cinnamon live schema package, if id is not org.cinnamon but org.gnome
https://github.com/manjaro/packages-extra/commit/2d88d672910dac4811ee75843b2d2053762f2360

**Comment by udeved** [comment]
kde environment xdg vars:

~~~
$ printenv | grep XDG
XDG_VTNR=7
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/devtux
XDG_SESSION_COOKIE=manjaro-openrc-1453392212.991819-1425008362
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_TYPE=x11
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=plasma
XDG_DATA_DIRS=/usr/share:/usr/share:/usr/local/share
XDG_CURRENT_DESKTOP=KDE
~~~

cinnamon
~~~
$ printenv | grep XDG
XDG_VTNR=7
XDG_SESSION_ID=c1
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/manjaro
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_TYPE=x11
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=cinnamon
XDG_RUNTIME_DIR=/run/user/1000
XDG_CURRENT_DESKTOP=X-Cinnamon
~~~
Cinnamon doesn't have XDG_DATA_DIRS exported it seems.
Hence desktop lauchers in .local/share are not found
