### ISSUE TITLE
manjaro-base-skel force installed to every ISO?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#115]
Is there now really no way to not have that package installed on an ISO? That makes it impossible to customize **.bashrc**.
Why can we not simply add the **manjaro-base-skel** package to the profiles that want to use it?
Like that the profiles that need a custom .bashrc can still add it in their desktop-settings package.

**Comment by philmmanjaro** [comment]
Yes, this should be optional. Maybe Sonar needs a different base-skel package ...

**Comment by philmmanjaro** [comment]
Is there any package depending on **manjaro-base-skel** or how is it forced now to be installed?

**Comment by oberon2007** [comment]
Nothing seems to depend on it. But it's not on i3-profile package list and still gets installed. Does manjaro-tools do that??

**Comment by philmmanjaro** [comment]
Check the log when it was installed or wait for @artoo to comment on this matter ...

**Comment by udeved** [comment]
Packages-Desktop...
but then again, custom bashrc is no good solution is general, since we don't build bash.
I don't really like we modify a foreign package provided file.

**Comment by oberon2007** [comment]
Then I don't understand really why you want to install **.bashrc** with **manjaro-base-skel** at all, if it is installed by bash anyway?
Anyway, if manjaro-base-skel stays what it is, why not simply move it from Packages-Desktop to Xfce- and KDE-profiles? Then it will be installed for those two and is out of the way for all the others. Is there a problem with that? Why does it need to be in Packages-Desktop for all profiles?

**Comment by udeved** [comment]
We basically colorize bash with the base-skel package.
Ideally, we would deploy this bashrc with package bash ourselves.

I already mentioned, I wouldn't currently go for a manjaro bash package.
Make a diff of bashrc in bash package and base-skel package. 

Generally, I don't see why bashrc needs to be customized on the install media any further, that couldn't be moved in a different dotfile.
I have already no clue why some stuff is in there, except for the color stuff I added.

**Comment by oberon2007** [comment]
Let me ask again: Can you please move base-skel package to the profiles that need it? What is your problem with that? Why does it need to be in Packages-Desktop? Are you blocking customization of other profiles' .bashrc on purpose now?

**Comment by oberon2007** [comment]
I keep wondering here if it is not bad practice in the **bash** package altogether to overwrite .bashrc in /etc/skel. No other package seems to do a similar thing or we should have file conflicts all the time with the config of this or that packages, too, right!? Should it not at least have .bashrc in the backup array?

**Comment by Ste74** [comment]
I understand point of view of artoo and your oberon and why not create a pkgs forked bash created with diff patch and put him in all wm ? Example bash-i3-manjaro , bash-bspwm-manjaro . I not see the pkgbuild for bash in arch tree but if you add provide=('bash') i think it work or not ?

**Comment by udeved** [comment]
Ste, this would work, and it would be the proper solution.
But, I don't recommend to have so many bash packages just for bashrc.
Building bash ourselves is risky, if something breaks with bash, or its depends, eg readline, you effectively have a broken cli. So your system has broken terminal.
We could also put eg colorization in /etc/bash.bashrc, so it was systemwide, but here we got same problem, this file belongs to package bash.

No @oberon2007 , its fine that arch does that with bash, its more that you try to square a circle.
bashrc in §HOME, should just provide essentials, the rest is user business.
Note, some settings in bashrc may negatively effect scripts you run.

**Comment by Chrysostomus** [comment]
For bspwm edition, I can live without custom bashrc. But I really need custom .bash_profile, because it is used instead of a display manager (automatic startx on login). For bspwm edition, I see following alternatives:
- create a package that echos a single line to /etc/skel/.bash_login to enable automatic startx on login. Such package would have general use as well.
- use zsh instead of bash as default shell. Zsh owns nothing in the skel, so having custom files for it is not a problem. Unfortunately, I don't know how to do this.
- find some other way to have automatic startx on login. Suggestions are welcome.

**Comment by udeved** [comment]
Please look at the referenced commit. ;)
https://github.com/manjaro/desktop-settings/commit/e8a2d190449b3e2887170ebccfcc74a7526adba8

**Comment by oberon2007** [comment]
Awesome, thanks! :)

**Comment by udeved** [comment]
https://wiki.gentoo.org/wiki/Xorg/Guide
https://wiki.gentoo.org/wiki/X_without_Display_Manager

**Comment by udeved** [comment]
Its not my business, but guys, I would suggest to reconsider the globbing settings.
This may impact scripts negatively, depending on the script.

**Comment by Chrysostomus** [comment]
Thanks!

**Comment by udeved** [comment]
So extensions will inherit base-skel settings.

Please remove you old .bashrc when finished adopting, and we can rebuild the packages. :)

**Comment by udeved** [comment]
@philmmanjaro 

In the mid-long-term perspective, we should consider building bash that provides the base-skel files.
We now still have the problem that it is not update safe, we can't guarantee atm that it will always work.

**Comment by philmmanjaro** [comment]
@udeved: let me check what is needed. As of now I don't see issues which are worring me much ...
