### ISSUE TITLE
File Packages-Root (## bmenu)

### ISSUE THREAD

**Issue by holmeslinux** [manjaro/manjaro-tools-iso-profiles#119]
hi guys good night! i realized that the file **Packages-Root** has the following packages:

**## bmenu
bmenu
brandr
mhwd-tui**

they are necessary?

vlw fwi, Holmes :)

**Comment by udeved** [comment]
Right, I am also unsure about Packages-Root.
Perhaps profiles should add them if needed.

**Comment by holmeslinux** [comment]
yes, each profile adds if necessary...

vlw fwi, Holmes :)

**Comment by Chrysostomus** [comment]
I think they were added when I suggested adding them to net edition. I think profiles are better place for them.

**Comment by philmmanjaro** [comment]
Yep, we should move them out of it.
