### ISSUE TITLE
Talking to Israel Dahl - Torios Linux

### ISSUE THREAD

**Issue by holmeslinux** [manjaro/manjaro-tools-iso-profiles#120]
hi guys, today i spoke with Israel Dahl's Toros Linux, a distro base-Ubuntu with JWM, and he told me a few things interestings:

***
sudo mksquashfs "${CHROOTDIR}" "${LIVEdir}"/live/filesystem.squashfs -comp xz -Xbcj x86 -Xdict-size 25% -noappend -e boot

Yes, but you might make it smaller using xz compression for your squashfs.  I cut quite a bit off of ToriOS Debian.  It was 800+MiB and now it fits on a CD

default mksquashfs is gzip, and xz is much smaller

yes... so how do you make the ISO?  We make a chroot and build the ISO inside a chroot, and then make a squashfs of ToriOS

https://github.com/Israel-/ISOmaker
This is where I have the scripts for the ISOmaker
adapted from https://help.ubuntu.com/community/LiveCDCustomizationFromScratch

Our installer is much different from others... we decompress a tarball onto a drive.... it is all offline installation, no need for internet.  Our target is for very old computers, so we need the CD size too
***

what he called most attention was about the size of the iso!

good, i do not know if it is possible to decrease the size of the iso!

vlw fwi, Holmes :)

**Comment by philmmanjaro** [comment]
I really don't get your question. We are using `iso_compression=xz` since ages.

**Comment by holmeslinux** [comment]
i did not know that already we use xz! 
thx philm...

vlw fwi, Holmes :)
