### ISSUE TITLE
manjaro-iso-profile-base-16.02rc2 dependence cycle

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools-iso-profiles#121]
What is this ? I use git version .. ?

**Comment by philmmanjaro** [comment]
This was already fixed with https://github.com/manjaro/packages-extra/commit/18613f398c0773dab0962f5889038919aeacc6d8 and now adjusted again with https://github.com/manjaro/packages-extra/commit/9146caca739b2787d731301cab9c692224671f80.

**Comment by Ste74** [comment]
Thank you  ;-)
