### ISSUE TITLE
New Branch:Unstable

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#13]
I started an unstable branch.
Will do the same for manjaro-tools.

@philmmanjaro 

Should we take the opportunity and switch over to the 3 branch boxit repo naming?

**Comment by Kirek** [comment]
new git branch you mean?

**Comment by udeved** [comment]
yes, new git branch.
Phil and I talked about naming git branch also the 3 names boxit branches.

**Comment by philmmanjaro** [comment]
Well, this is not needed. We should name branches along the feature you're trying to add. Then create a pull request for discussion and delete that branch later on. Normally that is the way to go.

**Comment by udeved** [comment]
I'd agree if this was OOP project. ;)

Anyway, unstable can be deleted once merged in devel.

**Comment by philmmanjaro** [comment]
We will see what will work best. Lets play it the current way first. Simply go for it. We can change it always later on ...
