### ISSUE TITLE
How many iso profiles does manjaro really need?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#130]
https://github.com/manjaro/manjaro-tools-iso-profiles/pull/129

**Comment by philmmanjaro** [comment]
I don't know. How many are there and how many of them are not maintained?

**Comment by philmmanjaro** [comment]
The given profiles, did we all test them on functionality yet? If not we should do that and fix them if needed, before doing anything else.

**Comment by udeved** [comment]
The feedback wasn't very intensive unfortunately.

https://github.com/manjaro/manjaro-tools-iso-profiles/issues/101

**Comment by oberon2007** [comment]
Well, there's movement now ;)

**Comment by udeved** [comment]
Ringo just asked to drop mate profile, and he merges sonar-mate.

So should mate be deleted?

What about mate-gtk3? Would it make sense to use gtk3 in mate profile?

**Comment by Ste74** [comment]
I don't know the state of gtk3 in mate .. last week i try to build a mate sonar and it build fine ..
