### ISSUE TITLE
Profile migration to 'iso-profiles'

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#132]
Please check the box if your profile is fully tested and adopted to **manjaro-tools 0.11 series**. We are about to migrate it to [iso-profiles](https://github.com/manjaro/iso-profiles). All profiles not tested will be dropped.

### official

- [ ] xfce -- [philmmanjaro] (https://github.com/philmmanjaro)
- [x] kde -- [Kirek] (https://github.com/Kirek), [philmmanjaro] (https://github.com/philmmanjaro)
- [ ] net  -- [alexandru] (https://github.com/alexandruianu), [philmmanjaro] (https://github.com/philmmanjaro)

### minimal

- [x] budgie -- [Ste74] (https://github.com/Ste74)
- [x] kde -- [Kirek] (https://github.com/Kirek), [artoo] (https://github.com/udeved), [philmmanjaro] (https://github.com/philmmanjaro)
- [x] lxqt  --  [artoo] (https://github.com/udeved) 
- [x] net  -- [excalibur1234] (https://github.com/excalibur1234) 
- [x] xfce -- [philmmanjaro] (https://github.com/philmmanjaro), [alexandru] (https://github.com/alexandruianu)

### community

- [x] bspwm -- [Chrysostomus] (https://github.com/Chrysostomus)
- [x] budgie --  [Ste74] (https://github.com/Ste74)
- [x] cinnamon -- [oberon2007] (https://github.com/oberon2007)
- [x] deepin --  [oberon2007] (https://github.com/oberon2007)
- [x] fluxbox --  [napcok] (https://github.com/napcok)
- [x] gnome -- [Ste74] (https://github.com/Ste74)
- [x] i3 --  [oberon2007] (https://github.com/oberon2007)
- [x] jwm -- [holmeslinux] (http://github.com/holmeslinux)
- [ ] lxde -- [korrode] (https://github.com/korrode)  ?
- [ ] lxqt -- [Esclapion] (https://github.com/Esclapion)
- [ ] mate -- ?
- [ ] netbook -- [korrode] (https://github.com/korrode)
- [ ] openbox --  [holmeslinux] (https://github.com/holmeslinux) ?
- [x] pantheon -- [Ste74] (https://github.com/Ste74)

### sonar

- [ ] gnome-sonar -- [coffeeking](https://github.com/coffeeking), [philmmanjaro](https://github.com/philmmanjaro), [artoo](https://github.com/udeved) 
- [ ] mate-sonar -- [coffeeking](https://github.com/coffeeking), [philmmanjaro](https://github.com/philmmanjaro), [artoo] (https://github.com/udeved) 

### netrunner

- [ ] kde-netrunner -- [netrunner] (https://github.com/netrunner-rolling)

**Comment by Ste74** [comment]
Gnome test in this day .. budgie and pantheon checked and signed ok .

**Comment by mhussaincov** [comment]
heya,
I hope you don't think me rude by asking this,
hows about sonar?
thanks for your responces in advance! :)
Majid Hussain

**Comment by philmmanjaro** [comment]
@mhussaincov: sonar should be fine. We released just **16.03** hours ago. Announcement is in the making.

**Comment by Chrysostomus** [comment]
Testing bspwm profile is in progress. I have been trying to build it for several days. It builds, but has some weird issues (svg icons in gtk apps are broken, need manual intervention to fix). Is there some kind of list of the changes made that could help troubleshooting the issues?

**Comment by Chrysostomus** [comment]
Bspwm is now tested

**Comment by excalibur1234** [comment]
it looks like manjaro net-minimal works without any adjustments.

**Comment by udeved** [comment]
Right @excalibur1234 
net editions don't have /etc/skel for user account settings.

**Comment by Ste74** [comment]
Well just now build gnome minimal iso . All fine , 4 extra exstensions enable at startup , vertex maia and icon maia ok :)

**Comment by oberon2007** [comment]
Just built @napcok 's updated **fluxbox** profile. Builds and boots fine :+1:

**Comment by oberon2007** [comment]
**jwm** profile is working now :+1:
