### ISSUE TITLE
vm.swappiness default too low to avoid system becoming unresponsive.

### ISSUE THREAD

**Issue by parawizard** [manjaro/manjaro-tools-iso-profiles#133]
Hello Manjaro,

I have recently started using Manjaro and I had a problem with troubleshooting why my machine was getting into a completely unresponsive state. It ended up being the default swappiness setting in Manjaro.

vm.swappiness 1 should only be used now in place of vm.swappiness 0 really. With it set to one you will only swap at the very last moment and in my case it just swapped continuously so hard that it locked my systems, i7/intel SSD until I either managed to free some ram (takes minutes to type one command) or I hard powered off my system.

From what I can tell arch and Ubuntu uses a default of 60. I am sure that if you were looking to make Manjaro performance snappier you could use a more conservative default value say of 10. 

I understand that some people might not have any problems with 4GB of ram and never would actually fill it up completely but I am sure lots of people do. Lots of varying behavoir, use cases, applications and the like out there. Personally I will easily fill up 16GB or 32GB at work. 

Being that you audience of choice is people that are most likely either coming from a Debian based Distro. Or they are starting out with Manjaro (instead of Arch). It could be very frustrating from a new user who doesn't understand anything about memory usage or swap. Especially frustrating in this situation is that it is very difficult to troubleshoot while it is happening and there are no warnings like in other operating systems such as OSX or Windows. These Operating systems will gladly tell you that you have exhausted your memory. 

This is the only area where I could find a 100-manjaro.conf file that matches mine exactly. I do not understand quite yet how you build up the distro or what portion of the installer might set this setting. If I have posted this in the wrong section please let me know.

Regards,

Bryan

**Comment by hatifnatt** [comment]
Exactly same issue, it take about a week to realize what is the root cause of system became totally locked up and HDD activity led lights steadily. Friend with Arch Linux running on notebook with 2GB of RAM, 5400 RPM HDD and 1.8 old Centrino CPU never have this problem, he only have "lags" time to time, but my PC with 4GB RAM and Core i3 can be totally locked up for a tens of minutes until I kill some process in text console.

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools/commit/9995f8346259181dd221b5af0b1d6724f99f9e71

**Comment by oberon2007** [comment]
We also need to remove **/shared/manjaro/root-overlay/etc/sysctl.d/100-manjaro.conf**. Or change it there instead...

**Comment by oberon2007** [comment]
Ah. sorry. I've seen that you removed it there!

**Comment by oberon2007** [comment]
Uhm. No, you haven't :laughing:

**Comment by oberon2007** [comment]
The **100-manjaro.conf** file we currently deploy in the profile apparently has been overriding the script anyway. On a current ISO I get
```
cat /etc/sysctl.d/100-manjaro.conf 
vm.swappiness = 1
```

**Comment by oberon2007** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles/commit/329df0bab1bc1e491a7ff58c3c0cdee7745c66c4
swappiness will now default to 60

**Comment by korrode** [comment]
Don't go all the way back to 60.
10 sounds like a reasonable step to see if it addresses the issues raised by the users here.

**Comment by udeved** [comment]
I am going to address it in CAL.

I cleaned up and moved code from buildiso to live session repo.
iso will only be configured for live session, and CAL will configure the target install. @korrode

**Comment by korrode** [comment]
@parawizard @hatifnatt 

Can you please test vm.swapiness set to 2 and let us know if it makes the system behave reasonably, if not, try 5, then 10, etc.

**Comment by parawizard** [comment]
I may not understand vm.swappiness very well but it looks like for Manjaro you want to balance between too aggressive swapping that could slow down some systems with slow swap verses not swapping enough and having the system lock or OOM Killer start murdering peoples processes. 

Kernel default is 60. It is what I run as well. I mean setting something not so extreme but more in favor of less aggressive swapping could be like 10-20. 1 is just very extreme as it actually represents the kernels previous behavior if vm.swappiness was set to 0

**Comment by korrode** [comment]
> 1 is just very extreme as it actually represents the kernels previous behavior if vm.swappiness was set to 0

Yes, it was set that way intentionally quite some time ago now because Manjaro targets interactive desktops and laptops. There's been no complaints (that i know of) until now.

**Comment by parawizard** [comment]
Well being an experienced user and professional it took awhile to figure it out myself. Only after moving to Arch and having an epiphany that it was the swappiness setting... I should have realized sooner considering my experience with some production systems. Anecdotally, a friend of mine had the same issues and switched distros as well and was happy when I told him about it. 

On desktops and laptops you are not competing with other virtual machines or anything that could be cannibalizing disk IO for swap. So with such a low swap setting you have to have enough RAM for whatever the users are running. As the workload is unknown and the users amount of ram are going to vary system to system, something balanced seems to make sense to me? 

 For me just using chrome with enough tabs on a system with 4GB and a SSD would turn the system into a slideshow at vm.swappiness of 1. If I knew I was never going to use 4GB of ram then I wouldn't have a problem with that setting as I would never have any need to swap. though this scenario likely only would come from systems that have a sole/specific task or set of cron tasks. With my current laptop I will use up to 16GB of ram depending on if I am building pkgs, chromium, running VMs and with many multiple browsers with tabs open. I would be running into the same problem with a swappiness set to 1 even with 4 times my previous amount of ram.

Anyway no worries. Glad to see people having a look at this. I think Manjaro is good distro and always like to see it improved.

**Comment by oberon2007** [comment]
@parawizard so what would you suggest as a reasonable value to make sense for a default? 10? 30?

**Comment by parawizard** [comment]
10 would probably be reasonable if leaning towards less swap.

**Comment by hatifnatt** [comment]
Currently I'm using system with ```vm.swappiness = 10``` I have some lags but overall system works well and have no lockups. I can't check with values which can cause lockup with high probability, because it's my office working machine and I can loose some information in case of lockup.  I can check with 10 - 60 and may be even with 5 if you can give me some value to measure. I think "overall system responsiveness" can't be a good measure I need some numbers to write them in log / graph.
