### ISSUE TITLE
svg icons are broken in bspwm profile

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/manjaro-tools-iso-profiles#134]
Svg icons are not displayed in gtk apps. Issue can be fixed for the live session by reinstalling librsvg or by running 

`sudo usr/bin/gdk-pixbuf-query-loaders --update-cache` 
which is apparently part of install script of librsvg.
 
I can make hacks that somehow fix the issue, but I would rather like to solve it for real. I use Menda-Circle icon theme, but problem manifests with all svg icons.

Is there something crucial change I missed in latest updates of manjaro-tools?

**Comment by Chrysostomus** [comment]
More about the issue in this thread: https://forum.manjaro.org/index.php?topic=31744.0

**Comment by udeved** [comment]
This is most probably not an issue with buildiso, as it only pulls in packages.
Its either a packages issue, or your profiles has something wrong, or not adopted some package change.

**Comment by Chrysostomus** [comment]
Yeah, I'm guessing the third. That's why I opened issue there instead of manjaro-tools repo. I was hoping somebody could point me to a change I would have needed to adopt. At least the shared folders are up to date. 

If it is a package issue, then it is probably librsvg.

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools/issues/200

**Comment by Chrysostomus** [comment]
I'm not sure I understand relevance of the reference. Could you elaborate? 

I "fixed" this for the live-session by adding aforementioned command to autostart of the live user, but the same method will not work for installed system, since the command requires sudo rights and regular user cannot execute sudo commands without password. Any tips on how to overcome this? 

On a second thought, I think it is unlikely to be package issue, since there have not been other reports of the same problem. So it is very likely to be a profile issue.

**Comment by Chrysostomus** [comment]
Tried building with different host system, and the issue was magically fixed. So not a bug in profile, just some weirdness on host system.
