### ISSUE TITLE
New user is created with bash as default shell

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/manjaro-tools-iso-profiles#135]
I have a custom /etc/default/useradd file in bspwm profile, intented to ensure that user accounts are created with zsh as the default shell (https://github.com/manjaro/manjaro-tools-iso-profiles/blob/master/community/bspwm/bspwm-overlay/etc/default/useradd). This works for live session, but not for installed system. Any tips on how to achieve this on installed system?

**Comment by philmmanjaro** [comment]
Currently our installers default to **bash**.

Calamares
```
int ec = CalamaresUtils::System::instance()->
targetEnvCall( { "useradd",
"-m",
"-s",
"/bin/bash",
"-U",
"-G",
defaultGroups,
m_userName } );
```

Thus:
```
chroot_run(['useradd', '-m', '-s', '/bin/bash', '-U', '-G', default_groups, username])
```

**Comment by Chrysostomus** [comment]
Thanks!
