### ISSUE TITLE
[profile] verify and validate sonar profiles

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#14]
Helping out our blind developers over at Sonar Linux we might check time to time to validate and verify their profiles to be compatible to our changes on **manjaro-tools**: https://gitlab.com/sonarlinux/sonarprofiles

Also it would be best to contact them directly on Mumble if changes are needed:
Server: mumble.sonargnulinux.com
Port: 31277

**Comment by Kirek** [comment]
Lets see if I have time to look at them this weekend
