### ISSUE TITLE
NetworkManager and OpenRC

### ISSUE THREAD

**Issue by GoldenKeyRiver** [manjaro/manjaro-tools-iso-profiles#141]
On default is wrong version of networkmanager, on OpenRC should works networkmanager-openrc package.

**Comment by oberon2007** [comment]
Which profile are you talking about?

**Comment by GoldenKeyRiver** [comment]
Deepin

**Comment by oberon2007** [comment]
I see. Deepin hasn't been prepared to work with OpenRC at all. I could not make it work for several reasons...

**Comment by GoldenKeyRiver** [comment]
It's several problems like poweroff command, but the rest is fast working.

**Comment by oberon2007** [comment]
How about audio? How do you get pulseaudio to autostart?

**Comment by GoldenKeyRiver** [comment]
I had sound after installation, but is something strange with pulseaudio.
ALSA isn't enable in rc-update. 
Consolekit is running. 

When I use "pulseaudio --start" from my user all is working. 

I added start up to my fish shell config.

**Comment by oberon2007** [comment]
There is **pulseaudio-openrc**! Are you using that?

**Comment by GoldenKeyRiver** [comment]
No, I'm not using that. I don't want to start pulseaudio for whole system. 
I added fish to ~/.config/autostart 

All is working, and with pulseaudio menu of Deepin is faster.

In default of Manjaro Deepin is gufw, but with system isn't installed ufw package.

**Comment by udeved** [comment]
What DE are you using?
Pulseaudio works without any additional steps on kde for example.

**Comment by GoldenKeyRiver** [comment]
Deepin, I had problem with polish keymap, and I added "setxkbmap pl" to config.fish.

Now all is working perfect, I can't repair problem with system shut down. 

Thank you for show me where are bugs.
