### ISSUE TITLE
trash not working on current xfce-profile

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#142]
Just built an xfce-minimal. **gvfs** is installed, but:

![xfce-trash](https://cloud.githubusercontent.com/assets/11800714/13901097/7dabac46-ee18-11e5-908b-94fdafd3504b.png)

I ran the script that I use in Deepin to fix the same issue
```
userid=$(id -u $USER)

if [ ! -d "/.Trash-$userid" ]; then
  sudo mkdir -p /.Trash-$userid/{expunged,files,info}
  sudo chown -R $userid /.Trash-$userid
fi
```
This fixes it.
For some reason **thunar** appears not to be able to create those dirs. I thought they should be creaated by **gvfs** but obviously they are not...

**Comment by oberon2007** [comment]
Here was our diskussion a while ago about the same problem in Deepin: https://forum.manjaro.org/index.php?topic=27881.0

**Comment by oberon2007** [comment]
Just verified the same issue with a downloaded 16.06-pre1 ISO.

**Comment by oberon2007** [comment]
Best I can think of as a temporary workaround: https://github.com/manjaro/packages-community/commit/e9d77065e24cbbd1d39dba3d4c3494b1c10f5303
Anyone has a better idea? @Kirek @udeved ?
I'm aware that the install script is dirty because it produces an un-tracked file. But in case the directories would be successfully created by **thunar** or **gvfs** they'd also be untracked, anyway...
Problem is that installing something at **/** the normal way with pacman is apparently not possible - or I haven't figured out how to in any case.
In any case I think this issue needs fixing...
An alternative would be to leave the install script and add the **fix-trash** script to autostart on the ISOs

**Comment by oberon2007** [comment]
Maybe a better place would be to add that to the livecd script for now? Adding it in **.skel/.config/autostart** doesn't make much sense, because then it will end up in the settings package and a newly created user without administrative right cannot even run the script...

**Comment by udeved** [comment]
Nope, we must not constantly try to fix packages on iso.
Definitely no. lets find the true issue.

**Comment by oberon2007** [comment]
Sure! In essence **gvfs** used to provide trash functionality but since recently it fails doing that for all **nautilus**, **nemo** and now **thunar**, too. **Pcmanfm** I think still doesn't have that problem for whatever reason.
Is it possible that trash is expected at a different location now than it used to be?
In any case somehow the directories need to be created, be it by 3rd party or by a package or service we provide ourselves...

**Comment by Kirek** [comment]
I the trash is located in ~/.local/share/Trash in kde systems, if I install thunar there, it uses that directory.

**Comment by oberon2007** [comment]
As you see in my dirty script, it is now obviously needed in **/.Trash-$(id -u $USER)**

**Comment by oberon2007** [comment]
![knife](https://cloud.githubusercontent.com/assets/11800714/13904346/9d6d63aa-ee9d-11e5-8e7a-bc0ed92342cc.jpg)

**Comment by oberon2007** [comment]
The problem with this seems to be that it needs to be created by root but owned by user...

**Comment by oberon2007** [comment]
And @Kirek when dir is not present, does **thunar** create it at .local for you?

**Comment by udeved** [comment]
Berhard, please post output of 

    printenv

**Comment by udeved** [comment]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by oberon2007** [comment]
```
[manjaro@manjaro ~]$ printenv
XDG_VTNR=7
SSH_AGENT_PID=1183
XDG_SESSION_ID=c1
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/manjaro
QT_STYLE_OVERRIDE=gtk
GLADE_PIXMAP_PATH=:
TERM=xterm
SHELL=/bin/bash
XDG_MENU_PREFIX=xfce-
GTK2_RC_FILES=/home/manjaro/.gtkrc-2.0
WINDOWID=60817412
GTK_MODULES=canberra-gtk-module
USER=manjaro
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.pdf=00;32:*.ps=00;32:*.txt=00;32:*.patch=00;32:*.diff=00;32:*.log=00;32:*.tex=00;32:*.doc=00;32:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
GLADE_MODULE_PATH=:
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
SSH_AUTH_SOCK=/tmp/ssh-IfEamHgQq82W/agent.1182
SESSION_MANAGER=local/manjaro:@/tmp/.ICE-unix/1176,unix/manjaro:/tmp/.ICE-unix/1176
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
XDG_CONFIG_DIRS=/etc/xdg
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
MAIL=/var/spool/mail/manjaro
DESKTOP_SESSION=xfce
XDG_SESSION_TYPE=x11
PWD=/home/manjaro
LANG=en_US.UTF-8
GDMSESSION=xfce
XDG_SEAT=seat0
HOME=/home/manjaro
SHLVL=2
YAOURT_COLORS=nb=1:pkg=1:ver=1;32:lver=1;45:installed=1;42:grp=1;34:od=1;41;5:votes=1;44:dsc=0:other=1;35
XDG_SESSION_DESKTOP=xfce
LOGNAME=manjaro
XDG_DATA_DIRS=/usr/local/share:/usr/share
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
BROWSER=/usr/bin/xdg-open
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0.0
GLADE_CATALOG_PATH=:
XDG_CURRENT_DESKTOP=XFCE
COLORTERM=xfce4-terminal
XAUTHORITY=/home/manjaro/.Xauthority
_=/usr/bin/printenv
```

**Comment by oberon2007** [comment]
```
[manjaro@manjaro ~]$ $XDG_DATA_HOME/Trash
bash: /Trash: No such file or directory
```

**Comment by oberon2007** [comment]
https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html

**Comment by Kirek** [comment]
I mate, it uses ~/.local/share/Trash, if you install thunar, remove .local and delete a file in thunar, it creates that directory as well.
I'm downloading the xfce pre edition now to see what it creates or not.

**Comment by Kirek** [comment]
Basically the linked specs say the same, $XDG_DATA_HOME/Trash -> ~/.local/share/Trash
Maybe is some misconfiguration, what happens with a xfce iso created without any desktop-settings ?

**Comment by oberon2007** [comment]
@Kirek That's the ISO I'm on right now. No dirs are created...

**Comment by Kirek** [comment]
Did you reproduce this after installation? Because in pre1 live I can reproduce this problem, but not after installation. I won't be surprised if this has something to do with using overlays for the live...

**Comment by udeved** [comment]
Could it be just a permission problem?

**Comment by Kirek** [comment]
Removed .local in the iso and no luck, you do the same in the installed system and it just creates the Trash dir and everything is fine

**Comment by oberon2007** [comment]
Permission problem somehow doesn't seem likely if .local would be the attempted destination, which is owned by the user.
The environment theory sound more convincing to me.
Especially: Manually creating .local/share/Trash does not make trash work in live while creating /.Trash-1000 does help.
Looks more like the env var for Trash in live is not set correctly, while in the final install it is.
Maybe the installers set the variable while the tools don't?

**Comment by oberon2007** [comment]
How about this theory:
**thunar** tries to create the dirs and reads **$XDG_DATA_HOME/Trash**. If this is pointing to / in live, thunar is not permitted to create the dirs there and fails. If created manually at / in live, thunar finds the dirs in this location and uses them.
In the install the variable points to **.local/share** and all is well for the dirs to be created and used by the filebrowsers.
Does that make sense?

**Comment by oberon2007** [comment]
Logging in as root and deleting a file with thunar creates a **/.Trash-0** and moves the deleted files there. At the same time the default Xfce includes a desktop entry 'Trash' pointing to **/root/.local/share/Trash** which remains empty of course. When I move the content of /.Trash-0 to /root/.local/share/Trash the desktop icon shows a full-trash icon :laughing: 
So in this case user root has permission to create trash at / and does so.
I think this confirms that Trash variable in live is just set to the wrong destination or it defaults to / because it's not set at all.

**Comment by Kirek** [comment]
No. When you create a /.Trash or /.Trash-$uid directory, it takes precedence from $XDG_DATA_HOME/Trash-

$XDG_DATA_HOME is not defined (thats why $XDG_DATA_HOME/Trash == seems to point at /Trash), but when it's not defined in the env, by default is ~/.local/share, and thats what Thunar does, but something is fucked up in ~/.local in the live, and I'm pretty sure it has something to do with overlayfs...

**Comment by Kirek** [comment]
Okay, forget all this. Try removing a directory (empty or not), it works, its send the stuff in .local/share/Trash

**Comment by Kirek** [comment]
https://bugs.launchpad.net/ubuntu/+source/glib2.0/+bug/1391811

**Comment by oberon2007** [comment]
Wow!

**Comment by Kirek** [comment]
Upstream bug:
https://bugzilla.gnome.org/show_bug.cgi?id=748248

I don't think creating a package is the right solution as this is only needed in the live.
We should just modify the live script to create the /.Trash-$uid directory to workaround this issue.

**Comment by oberon2007** [comment]
Absolutely! :-)

**Comment by oberon2007** [comment]
Just frustrating to see how old these issues are... Beh. :wink:

**Comment by udeved** [comment]
Seems to be a gtk problem, pcmanfm-qt doesn't complain.
So please don't fix this for all DE, and do it specific.

**Comment by oberon2007** [comment]
@udeved , are you sure you can trash desktop items like for example **manjaro-welcome**? The issue applies only to certain items!

**Comment by udeved** [comment]
Are you talking about the items we copy to the Desktop?
Then thats logical, because they are root owned.

**Comment by oberon2007** [comment]
No, please check! They are owned by manjaro:manjaro!
Or try creating a new item on the desktop as user and then trash it. Will not work here.

**Comment by oberon2007** [comment]
```
[manjaro@manjaro ~]$ ls -ll Desktop/
total 16
lrwxrwxrwx 1 manjaro manjaro   45 Mar 20 17:08 'Beginner User Guide.pdf' -> /usr/share/doc/livecd/Beginner_User_Guide.pdf
-rwxr-xr-x 1 manjaro manjaro  234 Mar 20 17:08 calamares.desktop
-rwxr-xr-x 1 manjaro manjaro 3065 Mar 20 17:08 hexchat.desktop
-rwxr-xr-x 1 manjaro manjaro  294 Mar 20 17:08 manjaro-welcome.desktop
-rwxr-xr-x 1 manjaro manjaro  243 Mar 20 17:08 thus.desktop
```

**Comment by udeved** [comment]
I created empty file in lxqt live session, and it was deleted without complaint.

**Comment by oberon2007** [comment]
Deleted or moved to trash?

**Comment by udeved** [comment]
trashed, damn it.

**Comment by udeved** [comment]
I appears logic to me, that it is in fact gtk troggered, due to the referenced glib bug.
qt doesn't use glib this way.
We need to test this for kde.

Anyway, I don't quite see a point to investigate much effort in it, since its live session.
Trash in live session is kind of useless, data is lost anyway on shutdown.

**Comment by oberon2007** [comment]
It's just not a good impression in a test environment when trash is not we working. We just should make it work.
I don't see on the other hand what the harm would be to simply create **/.Trash-1000** in the live environment on all ISOs. But if that's a problem for you then of course it needs to be done differently.

**Comment by udeved** [comment]
I am saying, we need to test this.
We dont know what DEs are effected, simple as that.
lxqt isn't, no errors on sending file to trash.

**Comment by udeved** [comment]
I am saying that adding a fix, which may only indeed fix (how many?) gtk DE, is no good approach in general.
I just don't like fixing stuff that may only be needed specifically, not generally. 
While I don't expect this fix to negatively impact qt apps, do we know for sure?
Do you see what I am saying?

**Comment by oberon2007** [comment]
It doesn't work on Xfce, Cinnamon, Deepin and ... here's lxqt-minimal-openrc-16.03:
![lxqt](https://cloud.githubusercontent.com/assets/11800714/13907384/3332c93a-eeed-11e5-97bb-a180c06aebde.png)

**Comment by udeved** [comment]
Thats desktop items you try to delete.
I tried with empty file, it worked.

**Comment by udeved** [comment]
Kind of crazy, first we have a little fuzz to get these items on the localized desktop, and now we try to delete them.

**Comment by oberon2007** [comment]
:stuck_out_tongue_winking_eye:

**Comment by udeved** [comment]
Its not something that gives me sleepless nights, seriously.
If someone wants to fix it, go forward.
