### ISSUE TITLE
lightdm-gtk-greeter cursor-theme

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#143]
The greeter screen defaults to the xcursor theme set in **/usr/share/icons/default/index.theme**
This file is owned by **libxcursor** and defaults to Adwaita. But since **libxcursor** package backs up that file, setting the cursor theme there seems ok.
In the xfce profile there is this line in **/etc/lightdm/lightdm-gtk-greeter.conf**:
```
cursor-name = Menda-Cursor
```
This option however is not used in the greeter's [example .config](http://bazaar.launchpad.net/~lightdm-gtk-greeter-team/lightdm-gtk-greeter/trunk/view/head:/data/lightdm-gtk-greeter.conf) and doesn't seem to work...
I just found that there is actually a [patch](https://answers.launchpad.net/lightdm-gtk-greeter/+question/268888) available for setting the cursor theme in the greeter conf that has not been implemented upstream, yet.
At the moment we already have another patch (a11y) for **lightdm-gtk-greeter** in overlay. So we could also add that cursor patch theoretically. But i guess it will be better to stick to the index.theme solution until upstream provides the settings feature. Right?
In any case I have parked the patch with the PKGBUILD in case we decide to use it ...

**Comment by philmmanjaro** [comment]
Simply apply the patch and we see what will happen. Higher the revision of **lightdm-gtk-greeter** package to do so and uncomment the patch line.

**Comment by oberon2007** [comment]
hm. not working, yet... I will see what I can find in the greeter code. maybe the conf needs to be different, but it's like the author of the patch instructs...

**Comment by oberon2007** [comment]
It was just the comment in the greeter conf that made the setting invadid. Working now :+1:
