### ISSUE TITLE
Profile updates for v0.11.6

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#152]
Please check the box if your profile is fully tested and adopted to **manjaro-tools 0.11.6 point release**. There were changes made in regard of UEFI, dostools and [others](https://github.com/manjaro/manjaro-tools/releases/tag/0.11.6). All community maintainers should adopt to the changes made to our official profiles.

### official

- [x] xfce -- [philmmanjaro] (https://github.com/philmmanjaro)
- [x] kde -- [Kirek] (https://github.com/Kirek), [philmmanjaro] (https://github.com/philmmanjaro)
- [x] net  -- [alexandru] (https://github.com/alexandruianu), [philmmanjaro] (https://github.com/philmmanjaro)

### minimal

- [x] budgie -- [Ste74] (https://github.com/Ste74)
- [x] kde -- [Kirek] (https://github.com/Kirek), [artoo] (https://github.com/udeved), [philmmanjaro] (https://github.com/philmmanjaro)
- [ ] lxqt  --  [artoo] (https://github.com/udeved) 
- [x] net  -- [excalibur1234] (https://github.com/excalibur1234) 
- [x] xfce -- [philmmanjaro] (https://github.com/philmmanjaro), [alexandru] (https://github.com/alexandruianu)

### community

- [ ] bspwm -- [Chrysostomus] (https://github.com/Chrysostomus)
- [x] budgie --  [Ste74] (https://github.com/Ste74)
- [x] cinnamon -- [oberon2007] (https://github.com/oberon2007)
- [x] deepin --  [oberon2007] (https://github.com/oberon2007)
- [ ] fluxbox --  [napcok] (https://github.com/napcok)
- [x] gnome -- [Ste74] (https://github.com/Ste74)
- [x] i3 --  [oberon2007] (https://github.com/oberon2007)
- [ ] jwm -- [holmeslinux] (http://github.com/holmeslinux)
- [ ] lxde -- [korrode] (https://github.com/korrode)  ?
- [x] lxqt -- [Esclapion] (https://github.com/Esclapion)
- [x] mate -- [philmmanjaro] (https://github.com/philmmanjaro)
- [ ] netbook -- [korrode] (https://github.com/korrode)
- [ ] openbox --  [holmeslinux] (https://github.com/holmeslinux) ?
- [ ] pantheon -- [Ste74] (https://github.com/Ste74)

### sonar

- [x] gnome-sonar -- [coffeeking](https://github.com/coffeeking), [philmmanjaro](https://github.com/philmmanjaro), [artoo](https://github.com/udeved) 
- [x] mate-sonar -- [coffeeking](https://github.com/coffeeking), [philmmanjaro](https://github.com/philmmanjaro), [artoo] (https://github.com/udeved) 

### netrunner

- [ ] kde-netrunner -- [netrunner] (https://github.com/netrunner-rolling)

**Comment by coffeeking** [comment]
hi
I've been working on sonar mate for the past few hours. I've
standardized the vast majority of our profiles. Everything is now in
either packages-desktop or the root overlay. The only things that are in
the gnome and mate overlays are files that are specific to gnome or
mate, and there aren't many of those.  Packages mate and packages gnome
now contain just the packages specific to gnome and mate, not much more
than the gnome and mate and mate extra groups. Everything else is in
packages-desktop. Mate boots, as long as I use gdm. Lightdm will not
work no matter what I try. Gnome I'll test as soon as I wake up for the
day, I'm just about to sleep. Uefi is fixed again, it was briefly broken
when efitools first showed up. Has support for secure boot been
improved? I emailed the sonar list saying it was possible secure boot
would work out of the box but I didn't know for sure.
Thanks
Kendell Clark


Philip Müller wrote:

**Comment by philmmanjaro** [comment]
@coffeeking: Secure boot is not yet implemented. It might be possible but then we have to use different image files from **efitools** to support it. As of now it is the plain old unsecured way.

**Comment by Ste74** [comment]
Budgie is ok .. will see other only a thing : calamares appareance only for me ?
![virtualbox_pantheon_16_05_2016_21_39_30](https://cloud.githubusercontent.com/assets/11218234/15301619/ece00a12-1bae-11e6-8c43-c741951e10ba.png)

**Comment by philmmanjaro** [comment]
Switch to a light theme and tell me what the error messages are.

**Comment by philmmanjaro** [comment]
@Ste74: you have to plug-in your laptop and start calamares either with `sudo calamares` or `pkgexec calamares`.

**Comment by Ste74** [comment]
:wink: @philmmanjaro  yeha .. i started calamares in a terminal but with manjaro user .. now whit sudouser
![virtualbox_pantheon_16_05_2016_21_53_15](https://cloud.githubusercontent.com/assets/11218234/15301964/a3f13dce-1bb0-11e6-9421-746f1301388f.png)

**Comment by philmmanjaro** [comment]
Ok, then you see what the issue still is. Your laptop is still not plugged into with a power cord. If you still want to skip that setting you have to edit the welcome.conf.

**Comment by Ste74** [comment]
I know that :wink: my question is only for the white box :smile: .. installed and all fine

**Comment by philmmanjaro** [comment]
@Ste74: It is a theme issue. Please open an issue to the proper bugtracker as you already gone way oftopic on this one here.
