### ISSUE TITLE
How are we gonna deploy iso profiles?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#154]
If we go distributing the install media on two separtae locations, official and community, are we gonna split the profiles too?

**Comment by philmmanjaro** [comment]
We first have to create the project at **sourceforge-net** to have even the option to do so. To distribute the ISOs you'll need to have the access rights at SF first. However it wouldn't make much sense to split them in git, rather set the community project as target for the upload. If you split the git-repo it is harder for the community to follow up the official profile changes. Else we have to force them to use forks which will even scare some of them. So lets discuss our options with them and decide as a team.

**Comment by udeved** [comment]
Ok, yes, it will need changes in deployiso and we dynamically set upload account by edition.

**Comment by philmmanjaro** [comment]
If we make it configurable the community maintainers can even use **deployiso** for their own projects. Names can change. If we hardcode it it wouldn't make muche sense to do so. Then we have to edit the given code whenever we change the SF project or even switch the host totally.

**Comment by udeved** [comment]
Ok, so we leave it as is then, also fine.

Can you create the community account?

If we have two accounts, we gonna take out the $edition subfolder on server?

**Comment by Ste74** [comment]
The problem is the time left os shell (3 hours ?) in more case is not sufficient to upload an iso... if i understand right why not split the deployiso ? first step upload in user repo ( time unlimited) after merge in community ..
