### ISSUE TITLE
oblogout

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#158]
Can we please have oblogout packaged instead of being cluttered over several profiles in the overlay/usr?

**Comment by oberon2007** [comment]
Actually we already have a nice package [oblogout manjaro](https://github.com/manjaro/packages-community/tree/master/oblogout-manjaro) :wink:

**Comment by oberon2007** [comment]
If someone needs other icons or commands configured, this can be placed in **/etc/oblogout.conf**. It will be respected by the package (it's in ``backup`` array.)

**Comment by udeved** [comment]
I don't understand then, why bspwm and jwm still have oblogout stuff in the profile.
