### ISSUE TITLE
duplicate libxvmc

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#160]
**libxvmc/lib32-libxvmc** are listed in Packages-Mhwd{,-minimal} aswell as Packages-Live, therefor they get reinstalled during build. I guess we can remove them either from Live or in both Mhwd and Mhwd-minimal. I'm just not sure were it will be best to keep them ;)

**Comment by philmmanjaro** [comment]
You're wrong. **mhwd** creates a repository but don't install any of the listed packages. It is correct as it is.

**Comment by oberon2007** [comment]
I keep seeing this:
```
==> Prepare [Live installation] (live-image)
 --> overlayfs mount: [/var/lib/manjaro-tools/buildiso/deepin/x86_64/live-image]
 --> mirror: http://mirror.netzspielplatz.de/manjaro/packages/stable/$repo/$arch
==> Creating install root at /var/lib/manjaro-tools/buildiso/deepin/x86_64/live-image
  -> Installing packages to /var/lib/manjaro-tools/buildiso/deepin/x86_64/live-image
:: Synchronizing package databases...
downloading core.db...
downloading extra.db...
downloading community.db...
downloading multilib.db...
warning: libxvmc-1.0.9-1 is up to date -- reinstalling
```

**Comment by oberon2007** [comment]
It gets installed in image_custome before.

**Comment by oberon2007** [comment]
So it seems to be a dependency of one of the deepin packages, I see ...

**Comment by philmmanjaro** [comment]
Only when **xinelib** or **mplayer** gets installed. It is not regular.

**Comment by oberon2007** [comment]
Yes. I got it. **smplayer** is on my list and it requires **mplayer** :wink:

**Comment by philmmanjaro** [comment]
Also it is a really large page **128.0 kB** ...

**Comment by oberon2007** [comment]
Pfoah!

**Comment by oberon2007** [comment]
:no_mouth:
