### ISSUE TITLE
libinput replacing synaptics

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#162]
Is the replacement of synaptics driver with libinput a bit pre-mature, maybe?
On the forum there are some reports still from people having to reinstall synaptics for their hardware to work properly.
With Deepin I have run into this problem: https://github.com/linuxdeepin/developer-center/issues/57
and the only way right now for me to have a working input-settings-widget in the control panel is to comment out **xf86-input-libinput** in Packages-Desktop locally on my branch and install **xf86-input-synaptics** - that's a bit ugly :wink: 
I'm not sure what would be a feasible option for now... Move **xf86-input-libinput** to some profiles only? Or wait with the transition a little longer since apparently there are still issues also with other desktops?

**Comment by philmmanjaro** [comment]
yeah, it is always a pro and con. always depending on hardware.
