### ISSUE TITLE
[xfce] consider replacing guayadeque / or configure autoplay ?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#163]
I didn't have time to play around with this or look for a reason, but apparently **guayadeque** is not working as expected in the xfce profile:
https://www.youtube.com/watch?v=7SAgVQpRoWI
https://www.youtube.com/watch?v=CvSL3bj7Cj8

**Comment by Kirek** [comment]
It seems the original developer of guayadeque has come back https://github.com/anonbeat/guayadeque, maybe that problem is gone in the git version.

Or if we replace guayadeque, I really like lollypop https://gnumdk.github.io/lollypop-web/

**Comment by Ste74** [comment]
I use lollypop in gnome and budgie and work very well. Is small but whit
more function.

Il 25/giu/2016 06:10, "Ramon Buldó" <notifications@github.com> ha scritto:
