### ISSUE TITLE
why HandleLidSwitch=ignore ? need to leave it unset (default is suspend) or explicitly set to suspend

### ISSUE THREAD

**Issue by c0b** [manjaro/manjaro-tools-iso-profiles#164]
filed manjaro/manjaroiso#48 but I just see that repo says deprecated, I'm not sure which one is the latest maintained

https://github.com/manjaro/manjaroiso/commit/8840750c11361bc363bc2edfcff7021f6c3fb704#commitcomment-18059391

Could you tell why set `HandleLidSwitch=ignore` ?? this has caused a problem of when run iso on laptop, close the laptop doesn't suspend

from `man 5 logind.conf` the default `HandleLidSwitch` is `suspend`

the same code found at https://github.com/manjaro/manjaro-tools-iso-profiles/commit/a17435c#diff-e9089c3dca62c9b90c42e6ecb1fc7747R24 as well

**Comment by Ste74** [comment]
I can talk about budgie but you can try on xfce ( i assume you use xfce )
If you see my commit i enable this
HandleLidSwitchDocked=suspend and for me work well .. i don't remember where in arch forum found the solution but it is . If you confirm after enable it weorking for you is possible talking to adopt in xfce

**Comment by philmmanjaro** [comment]
Please refer to our [old forum](https://old.forum.manjaro.org/index.php?topic=614.0). You can use **palemoon-bin** package to have an easy access to it by adding a ignore rule for our outdated https encryption.

**Comment by c0b** [comment]
I'm talking about the manjaro iso: the latest "Manjaro Gnome Edition 16.06" from front page (http://manjaro.github.io)

> https://old.forum.manjaro.org/index.php?topic=614.0

that old forum thread might be true in year 2012 but I hope now it can be changed back (to `HandleLidSwitch=suspend` ) and that should more of a XFCE specific issue? and fix can be in XFCE4-power-manager I think

In the Gnome edition 16.06 ISO file I see `HandleLidSwitch=ignore` that caused when running liveiso mode on laptop, close lid doesn't suspend, have to click from menu to suspend it that works;

yesterday I found from this http://unix.stackexchange.com/a/52645 answer I tried to comment out that line then `systemctl restart systemd-logind` on the live mode then close lid to suspend also works since then on;

**Let me elaborate this scenario a bit more** why I choose to run the live mode from iso and never install to a hard drive:

Since recent two years (2014- ) we see the USB drive size really boomed a lot I can get a 128GB usb drive really cheap, I put a lot of different iso files (multiple different Linux flavors) on this USB drive, and manually configured grub.conf with https://wiki.archlinux.org/index.php/Multiboot_USB_drive I take this USB drive with me to boot up every computer with Linux for people to try different flavor of Linux; I have Ubuntu, Fedora, Mint, ElementryOS, Gentoo, Kali Linux and Sabayon; all in live iso only; never installed to a hard drive

I have my own little piece of Shell script to copy isos to a hard drive copy grub.cfg and run grub-install, I call this bootstrap, I can use this usb drive to boot a computer and run this script to bootstrap a computer's hard drive to this multi flavor Linux, then the computer becomes bootable, I can boot up this computer to bootstrap more usb drives, more usb drives share to people to bootstrap more computers, like that; I see this bootstrap process a superior way than a traditional install-to-hard-drive process.

1. it takes less time to run bootstrap, (or traditional install process)
2. it takes less storage to contain a Linux: a typical 1~2GB live iso would need more than 10GB root partition if need to install; many modern laptop computer has 128GB or 256GB SSD, I don't want to waste a dedicated partition as Linux root partition;
3. for modern Laptops have 16GB memory or above, this mode load tmpfs on top of overlay, keep all running processes in memory is a even faster way than from SSD; for less than 4GB it's hard to run this mode, but we'll foresee new computers with even more memory;
4. Upgrade even better, when Ubuntu 16.10 comes out, I just download the new iso to hard drive, configure a menuentry in grub.cfg and reboot into it;
5. With some shell script do bind mouting of a user's true home directory, all user's /home is persistent cross multiple reboot; this is done by additional initrd, but unfortunately different scripts for different Linux flavors;

I hope Manjaro can support this running mode better, so far Ubuntu is the only one can flawlessly run on a laptop for months till 6 months later download a new iso for upgrade. With Manjaro there are some flaws like this one laptop doesn't suspend on close lid, for the iso out of box. Workaround is there, but I hope Manjaro iso can also run flawlessly, out of box without need of any workarounds.

**Comment by philmmanjaro** [comment]
Well, the **Gnome ISO** is not supported from our end. We only do spins for **XFCE** and **KDE**. When not told otherwise we will keep those settings as default. Please check with the maintainer of the ISO to see if a modification can be tested or ask him on how to spin that ISO for your own.

**Comment by Ste74** [comment]
Ok , now is more clearer . Test the solution .

**Comment by c0b** [comment]
> Well, the Gnome ISO is not supported from our end.

**Comment by udeved** [comment]
You got to live with it that gnome is only a community project, and kde and xfce being the officially supported DEs.
It unrealistic to expect a change that negatively impacts the officially supported DEs in favour of unsupported DE.

**Comment by c0b** [comment]
so where are the repos for The Manjaro Community ?

and where can I file the bug for Manjaro's XFCE and KDE's power-manager ? maybe you can borrow some ideas from how Ubuntu XFCE / KDE fixed the issue?
things should be fixed in the root cause, and then the workaround here in `systemd-logind.conf` can be removed; then all other Manjaro distro / Manjaro Community projects will benefit.

**Comment by udeved** [comment]
The root cause is gnome and systemd, enough said.
However, I don't care for these, I provide systemd alternative.

xfce and kde packages are upstream arch packages.

**Comment by Ste74** [comment]
In this days  i m busy, when i m free ceck this if really need for gnome
and not issue detected to a particolar hardware set. At this moment in pur
forum nobody  report this so let me see but only for gnome.

Il 01/lug/2016 08:52, "udeved" <notifications@github.com> ha scritto:

The root cause is gnome and systemd, enough said.
However, I don't care for these, I provide systemd alternative.

xfce and kde packages are upstream arch packages.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/manjaro/manjaro-tools-iso-profiles/issues/164#issuecomment-229868593>,
or mute the thread
<https://github.com/notifications/unsubscribe/AKstOrgq-tbkBeXpIevOd8p_UV2f-Y5Rks5qRLkxgaJpZM4JBDJc>
.

**Comment by udeved** [comment]
Take you time Ste :)
If it is a necessary fix, you will do whats needed on gnome, I am sure.

**Comment by Ste74** [comment]
Close via https://github.com/manjaro/manjaro-tools-iso-profiles/commit/e7139d7fc274ff7b9d8c6d0ac522090c8c202e78 but for next release i think switch to lightdm .

**Comment by c0b** [comment]
I see, changes in e7139d7 is very good, just leave systemd config as default, I see these days most of Linux distros (if not all of them) have switched to systemd which is required by Gnome; I'm not sure how does lightdm will change power-manager?

https://github.com/manjaro/manjaro-tools-iso-profiles/commit/e7139d7#diff-387a8a66eb5dc0a8d128168777830d63

wonder after e7139d7 merged for how long will there be another updated iso ? /cc @Ste74 do we have nightly or daily builds, something comparable to [Ubuntu daily iso images](http://cdimages.ubuntu.com/ubuntu-gnome/daily-live/) ?

**Comment by Ste74** [comment]
You can easy build an iso with our tools `manjaro-tools` . If you have manjaro installed you can install via pacman or gui interface for pacman the manjaro-tools pkgs.. after that clone our profile in your home and simply do `buildiso -p gnome` (-h option you can see the option ) . Manjaro is a rolling release so the new isos are generated almost 3 month cycle only for do an support up to date and with the new update into installer . This for the official edition ( xfce , net and kde ) . The community edition follow this cycle . Normally before a next stable release ( ie build with stable repo ) more iso ( community and official ) are generated in dev version or rc version ( ie build with unstable or testing repo ) .

**Comment by Ste74** [comment]
> I see, changes in e7139d7 is very good, just leave systemd config as default, I see these days most of Linux distros (if not all of them) have switched to systemd which is required by Gnome; I'm not sure how does lightdm will change power-manager?
Yes gnome and systemd are good friend :wink: Gnome and openrc  no . In my laptop after your report have installed my version ( i use in a desktop ) so with gdm my laptop won't suspend with lid . I ahve try any solution and search in the web for a common solution but i not find anything . I also encounterd a strange freeze of system ( random not related at nothing ) so only for try i have switch in lightdm . Change a parameter in a logind.conf and lid work and also the freeze disappear in my pov  gdm have problem in my hardware . Lightdm is more configurable,light and fast at work :smile:

**Comment by c0b** [comment]
> You can easy build an iso with our tools manjaro-tools

that's good so far; I mean, ideally, that can be done by some tools like Jenkins let it run every night and provide fresh iso for QA testers, I would like to dedicate some time test the bleeding edge version; But if current Manjaro community doesn't have such server resources that is fine, something like Ubuntu daily images must be consuming a lot of server bandwidth and storage space (I guess) not every community can afford.

**Comment by udeved** [comment]
Keep in mind, manjaro and ubuntu don't compare in any way.
We are only few people in team, ubuntu has a millionaire behind.

**Comment by c0b** [comment]
http://distrowatch.com/dwres.php?resource=popularity

however on DistroWatch popularity ranking: *Manjaro is the one right after Ubuntu and Fedora*; that's how I got to know Manjaro and the ranking of Manjaro is steadily increasing in last 12 months
