### ISSUE TITLE
[Request] Boot-repair iso

### ISSUE THREAD

**Issue by Salamandar** [manjaro/manjaro-tools-iso-profiles#165]
Well, actual isos are "big" (>1go, libreoffice and all) so slow to dl/burn to usb.
I suggest a 
* "small" minimal iso
* I would use Cinnamon as desktop, but a minimal desktop would be better
* All boot/partition/backup/driver useful tools already installed
Any suggestions ?

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles/tree/master/minimal
