### ISSUE TITLE
budgie-minimal ?

### ISSUE THREAD

**Issue by fassily** [manjaro/manjaro-tools-iso-profiles#166]
'LLo,
It disapeared here in /manjaro-tools-iso-profiles/minimal since a month ago (last time i've played with..) ?

**Comment by Ste74** [comment]
Hi fassil , Ok lets go .. clone the repo in your github account , copy the gnome minimal stuff and rename all gnome-minimal ( folder and file ) in budgie-minimal , then copy the budgie-minimal packages list file it ( overwrite the gnome-minial list ) . After create a pull request, i will see and merge :smile:

**Comment by Ste74** [comment]
Close via https://github.com/manjaro/manjaro-tools-iso-profiles/commit/103a58a51d9fbac8ac8ad473570e4a18fe8e6387 :wink:
