### ISSUE TITLE
Live User Profile is not in bumblebee group

### ISSUE THREAD

**Issue by FadeMind** [manjaro/manjaro-tools-iso-profiles#171]
I launched Live USB boot **manjaro-kde-16.08-x86_64.iso**. 
Manjaro Live session USER is not in **bumblebee** group at all.

**Comment by philmmanjaro** [comment]
Reopen this Issue on our new bug-tracker:

Profile-Settings: https://bugs.manjaro.org/index.php?project=4
Manjaro-Tools: https://bugs.manjaro.org/index.php?project=2
