### ISSUE TITLE
[xfce-minimal] open systemd service issues

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#2]
keyboardctl:
<pre>keyboardctl.service - Setup keyboard layout
   Loaded: loaded (/usr/lib/systemd/system/keyboardctl.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2015-01-11 12:05:20 UTC; 1min 50s ago
     Docs: man:keyboardctl
  Process: 210 ExecStart=/usr/bin/keyboardctl --setup (code=exited, status=1/FAILURE)
 Main PID: 210 (code=exited, status=1/FAILURE)

Jan 11 12:05:19 manjaro keyboardctl[210]: LANG = "en_US.utf8"
Jan 11 12:05:19 manjaro keyboardctl[210]: are supported and installed on your system.
Jan 11 12:05:19 manjaro keyboardctl[210]: perl: warning: Falling back to the standard locale ("C").
Jan 11 12:05:20 manjaro keyboardctl[210]: Use of uninitialized value $acm in -f at /usr/sbin/ckbcomp line 3201.
Jan 11 12:05:20 manjaro keyboardctl[210]: /usr/sbin/ckbcomp: no ACM for ANSI_X3.4-1968 exists
Jan 11 12:05:20 manjaro keyboardctl[210]: error: failed to create keyboard map (ckbcomp). Abording...
Jan 11 12:05:20 manjaro systemd[1]: keyboardctl.service: main process exited, code=exited, status=1/FAILURE
Jan 11 12:05:20 manjaro systemd[1]: Failed to start Setup keyboard layout.
Jan 11 12:05:20 manjaro systemd[1]: Unit keyboardctl.service entered failed state.
Jan 11 12:05:20 manjaro systemd[1]: keyboardctl.service failed.</pre>

ntpd:
<pre>ntpd.service - Network Time Service
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sun 2015-01-11 12:05:35 UTC; 5min ago
  Process: 527 ExecStart=/usr/bin/ntpd -g -u ntp:ntp (code=exited, status=0/SUCCESS)
 Main PID: 528 (code=exited, status=255)

Jan 11 12:05:34 manjaro systemd[1]: ntpd.service: main process exited, code=exited, status=255/n/a
Jan 11 12:05:34 manjaro systemd[1]: Unit ntpd.service entered failed state.
Jan 11 12:05:34 manjaro systemd[1]: ntpd.service failed.
Jan 11 12:05:35 manjaro systemd[1]: start request repeated too quickly for ntpd.service
Jan 11 12:05:35 manjaro systemd[1]: Failed to start Network Time Service.
Jan 11 12:05:35 manjaro systemd[1]: Unit ntpd.service entered failed state.
Jan 11 12:05:35 manjaro systemd[1]: ntpd.service failed.
</pre>

**Comment by aadityabagga** [comment]
I used to get the problem with keyboardctl too when I was using it with OpenRC:
https://forum.manjaro.org/index.php?topic=17389.msg161102#msg161102

```
* Starting keyboardctl ...
Use of uninitialized value $acm in -f at /usr/bin/ckbcomp line 3201.
/usr/bin/ckbcomp: no ACM for ANSI_X3.4-1968 exists
error: failed to create keyboard map (ckbcomp). Abording...
 [ !! ]
 * ERROR: keyboardctl failed to start
```

**Comment by udeved** [comment]
I am not quite sure what to do about it, and if something to do about it in manjaro-tools.
I recall kirek said he want to remove keyboardctl.

Keyboardctl on openrc is pretty useless.

**Comment by manjaro** [comment]
keyboardctl is depreciated. These errors are not critical and can be ignored. I just posted them to be documented.

**Comment by udeved** [comment]
Phil, as for ntp, did you add ntp to the start_systemd array in manjaro-tools.conf?

**Comment by manjaro** [comment]
Maybe not. Have to check that also for keyboardctl.

**Comment by udeved** [comment]
What is strange, shouldn't ntp be started without adding it as runlevel?
The bootup seem trying to start them.

**Comment by manjaro** [comment]
You're right. Needed to be added to start_systemd array. ntp has to be ntpd.

**Comment by manjaro** [comment]
Actually fixed with https://github.com/manjaro/manjaro-tools/commit/7b61ab137e5950c5972d47dea3c82366976e1ac7
