### ISSUE TITLE
[systemd219] tmpfiles-setup fails

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#26]
Since systemd219 we have a fail on tmpfiles-setup. Maybe we have to check our livecd-overlay.

<pre>[manjaro@manjaro Desktop]$ systemctl status systemd-tmpfiles-setup
● systemd-tmpfiles-setup.service - Create Volatile Files and Directories
   Loaded: loaded (/usr/lib/systemd/system/systemd-tmpfiles-setup.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2015-04-21 19:01:13 UTC; 1min 32s ago
     Docs: man:tmpfiles.d(5)
           man:systemd-tmpfiles(8)
  Process: 213 ExecStart=/usr/bin/systemd-tmpfiles --create --remove --boot --exclude-prefix=/dev (code=exited, status=1/FAILURE)
 Main PID: 213 (code=exited, status=1/FAILURE)
</pre>

**Comment by Kirek** [comment]
Working fine here, output of?
sudo journalctl -u systemd-tmpfiles-setup -r

**Comment by philmmanjaro** [comment]
**xfce-minimal** todays build

<pre>
-- Logs begin at Tue 2015-04-21 20:56:35 UTC, end at Tue 2015-04-21 20:58:49 UTC. --
Apr 21 20:56:37 manjaro systemd[1]: systemd-tmpfiles-setup.service failed.
Apr 21 20:56:37 manjaro systemd[1]: Unit systemd-tmpfiles-setup.service entered failed state.
Apr 21 20:56:37 manjaro systemd[1]: Failed to start Create Volatile Files and Directories.
Apr 21 20:56:37 manjaro systemd[1]: systemd-tmpfiles-setup.service: main process exited, code=exited
Apr 21 20:56:37 manjaro systemd[1]: Starting Create Volatile Files and Directories...
</pre>

**Comment by ryanvade** [comment]
Same.  Seems related: 
https://github.com/manjaro/manjaro-tools/issues/101

**Comment by Kirek** [comment]
This is because squasfsh file system doesn't support ACLs, this failure can be ignored in the live-cd.
