### ISSUE TITLE
[shared] Packages lists

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#30]
What do you thinnk about revising the packages lists and reduce them to a level we can maintain while having some sort of standardized lists?
It would go along with new sed tags, for example a possible Packages file could look like this:

~~~
## The actual 'base' group, minus netctl
bash
bzip2
coreutils
>openrc cronie-openrc
>systemd cronie
>openrc cryptsetup-openrc
>systemd cryptsetup
>openrc device-mapper-openrc
>systemd device-mapper
>openrc dhcpcd-openrc
>systemd dhcpcd
diffutils
e2fsprogs
file
filesystem
findutils
gawk
gcc-libs
>multilib gcc-libs-multilib
gettext
glibc
grep
gzip
inetutils
iproute2
iputils
jfsutils
less
licenses
logrotate
>openrc lvm2-openrc
>systemd lvm2
man-db
man-pages
manjaro-hotfixes
manjaro-system
>openrc mdadm-openrc
>systemd mdadm
mhwd
mhwd-db
nano
pacman
pciutils
pcmciautils
perl
procps-ng
psmisc
reiserfsprogs
s-nail
sed
shadow
sysfsutils
>openrc eudev-base
>openrc syslog-ng-openrc
>systemd syslog-ng
tar
texinfo
usbutils
util-linux
which
xfsprogs

## Base Packages
linux-firmware
lsb-release
>openrc haveged-openrc
>systemd haveged
manjaro-firmware
manjaro-release
memtest86+
>multilib lib32-mesa  # Optional dependency for mhwd

## Kernel
KERNEL
## Extra Base Packages
grub
mkinitcpio-nfs-utils
os-prober
pkg-config
squashfs-tools
sudo
syslinux
>openrc nfs-utils-openrc
>systemd nfs-utils

## Compression Codecs
lzop
unarj
unrar
unzip
xz
zip

## encrypt support
ecryptfs-utils
>openrc rsync-openrc
>systemd rsync
lsof

## needed by cli-installer
# dialog
# dmidecode
# gptfdisk
# parted
# pv
# tcpdump
wget

## efi support (only x86_64)
>x86_64 gummiboot
>x86_64 prebootloader
>x86_64 refind-efi

## Filesystem Packages
btrfs-progs
dmraid
dosfstools
ecryptfs-utils
testdisk
nilfs-utils
nfs-utils
ntfs-3g

## Fonts
terminus-font
ttf-bitstream-vera
ttf-dejavu
ttf-inconsolata
ttf-indic-otf
ttf-liberation

## Network
b43-fwcutter
dhclient
dnsmasq
iptables
ipw2100-fw
ipw2200-fw
iw
mobile-broadband-provider-info
modemmanager
nbd
KERNEL-ndiswrapper
ndiswrapper-utils
rp-pppoe
usb_modeswitch
>openrc wpa_supplicant-openrc
>systemd wpa_supplicant
zd1211-firmware

## Laptop power management
>openrc acpid-openrc
>systemd acpid
>openrc cpupower-openrc
>systemd cpupower
ethtool
>openrc hdparm-openrc
>systemd hdparm
sdparm
smartmontools
wireless_tools

## ucode for new cpus
intel-ucode

## Documentation
manjaro-documentation
~~~

New "tags" would be ">openrc", ">systemd", we both store already in profile.conf.
">multilib" and ">nonfee" could be new switches in profile.conf.

**Comment by udeved** [comment]
Packages-Xorg:
~~~
## Xorg Drivers
>free_uni xf86-video-apm
>free_uni xf86-video-ark
>free_uni xf86-video-ati
>free_uni xf86-video-chips
>free_uni xf86-video-dummy
>free_uni xf86-video-fbdev
>free_uni xf86-video-glint
>free_uni xf86-video-i128
>free_uni xf86-video-i740
xf86-video-intel
>free_uni xf86-video-mach64
>free_uni xf86-video-neomagic
>free_uni xf86-video-nouveau
>free_uni xf86-video-nv
>free_uni xf86-video-openchrome
>free_uni xf86-video-r128
>free_uni xf86-video-rendition
>free_uni xf86-video-s3
>free_uni xf86-video-s3virge
>free_uni xf86-video-savage
>free_uni xf86-video-siliconmotion
>free_uni xf86-video-sis
>free_uni xf86-video-sisusb
>free_uni xf86-video-tdfx
>free_uni xf86-video-trident
>free_uni xf86-video-tseng
>free_uni xf86-video-vesa
>free_uni xf86-video-vmware
>free_uni xf86-video-voodoo

## Bumblebee Support
bumblebee
primus
KERNEL-bbswitch
>multilib lib32-primus

## Network Support
KERNEL-broadcom-wl
KERNEL-rt3562sta
KERNEL-r8168

## Proprietary Drivers
>nonfree_uni catalyst-utils
>nonfree_uni KERNEL-catalyst
>nonfree_uni nvidia-utils
>nonfree_uni KERNEL-nvidia
>nonfree_uni nvidia-340xx-utils
>nonfree_uni KERNEL-nvidia-340xx
>nonfree_uni nvidia-304xx-utils
>nonfree_uni KERNEL-nvidia-304xx
>nonfree_multilib lib32-catalyst-utils
>nonfree_multilib lib32-nvidia-utils
>nonfree_multilib lib32-nvidia-304xx-utils
>nonfree_multilib lib32-nvidia-340xx-utils
>nonfree_multilib lib32-gcc-libs
>nonfree_multilib lib32-zlib

## Virtualbox Drivers
>free_uni virtualbox-guest-utils
>free_uni KERNEL-virtualbox-guest-modules

## Xorg Packages
libxaw
libxpm
libxvmc
pangox-compat

## Xorg x86_64 Packages
>multilib lib32-libxvmc

## VMWare Support
open-vm-tools
xf86-input-vmmouse
~~~

**Comment by philmmanjaro** [comment]
Sure, why not. This we can use for Manjaro 0.9.x and upward. For 0.8.x release I'll keep it the old way as it is now. Lets make that happen first, then we can go crazy again.

**Comment by udeved** [comment]
I am about to push a new branch for both manjaro-tools and iso-profiles where you can test the changes.
Just the pkg loaders need some fine tuning, which is what I am doing right now. :)

**Comment by Kirek** [comment]
We could eliminate some useless tags too.
The whole thing would be:
Remove: 
>free_uni (same as no tag)
>free_x64 (same as x86_64/multilib)
>dvd (not used)
>kde (not used)
Rename: 
>x86_64 to >multilib
>nonfree_uni to >nonfree
>nonfree_x64 to >nonfree_multilib
New:
>openrc
>systemd

This will give us this tags
>i686
>multilib
>openrc
>systemd
>nonfree
>nonfree_multilib
>blacklist
>cleanup
KERNEL

**Comment by udeved** [comment]
Thanks kirek, I was gonna ask this, if we could drop tags.

**Comment by excalibur1234** [comment]
how will "multilib" work in the future?

assume, i have no lib32 on my 64bit system: i have "multilib" switched off in my profile.conf.
how is it possible to install a package only on 64bit ISOs?
which tag do i have to use?

in my opinion, using "x86_64" makes sense.

**Comment by udeved** [comment]
tags:
~~~
>i686
>x86_64
>multilib
>nonfree_default
>nonfree_multilib

>openrc
>systemd
~~~

**Comment by excalibur1234** [comment]
i have another idea:

how about cleaning up the "Packages-net/xfce/..." file?
the following packages always looked out of place. here the beginning of the "Packages-net" file:
~~~
## Xorg Packages
inxi
libdnet
mesa-demos
>x86_64 lib32-mesa-demos
uriparser
xf86-input-acecad
xf86-input-aiptek
xf86-input-evdev
xf86-input-joystick
xf86-input-keyboard
xf86-input-mouse
xf86-input-synaptics
xf86-input-void
xf86-input-wacom
xinetd
xorg-server
xorg-server-utils
xorg-twm
xorg-utils
xorg-xinit

## Basic packages
dconf
desktop-file-utils

## Packages for Sound and Audio
manjaro-alsa
~~~

the ## Xorg Packages could be pushed to the "Packages-xorg" file. 
## Basic packages and ## Packages for Sound and Audio could be pushed to the "Packages" (manjaro-alsa installs lib32 packages!) file.

how do you like this idea?

**Comment by Esclapion** [comment]
Packages-Xorg is a file common to all DEs. It means that all files pushed there must be -absolutely- necessary for them.

**Comment by Kirek** [comment]
@excalibur1234 it would be much better to open a new issue for this.
So do that and we can discuss it there.

**Comment by philmmanjaro** [comment]
We might need another tag > **nonfree_i686** as I want to disable some proprietary drivers for minimal profiles so we still hit CD-size in that architecture.

**Comment by udeved** [comment]
Do we need a >nonfree_x86_64 too?
Wouldn't hurt I guess?

**Comment by philmmanjaro** [comment]
Why not, see 63c00d3bc811fb3c3262fdad976b10c73ad57570 and adjust as needed ...

**Comment by udeved** [comment]
Hmm, I think with your changes we don't need additional tags or code changes.

**Comment by philmmanjaro** [comment]
Are you sure? I assumed you used nonfree for something. With my changes those proprietary drivers get always installed on i686. Even if nonfree was not enabled. Therefore we might still need at least **nonfree_i686**.

**Comment by udeved** [comment]
I had the bowser window too small and didn't see your comments. ;)

Changes are pushed.

**Comment by philmmanjaro** [comment]
The usual. I didn't read it all ;)

**Comment by udeved** [comment]
I have had to idea we merge the 
    shared/Packages-Custom.template 
for every profile when loading
      Packages-$custom.
It means we would use the template as a common base list for DEs.
Worth the effort, or should every profile simply add the template packages to the 
      Packages-$custom
?

**Comment by philmmanjaro** [comment]
But how. Do you want to add flags for each possible DE? I think that package list might be the only one we don't symlink to shared.

**Comment by udeved** [comment]
The true individual file would remain, we would just join the to files in one var before loading

**Comment by udeved** [comment]
Update:

I have some working test code to join a static template in shared, and the profile's Packages-Desktop.
I cleaned out for test the stuff already in the Packages-Custom, I get a joined list sorted and only unique entires to sed.

Do we want this?
It would reduce the list in the profile, and we had some sort of common base packages for desktop image.

**Comment by philmmanjaro** [comment]
Let's give it a try. Remember we have to document it after all so our maintainers can work with it. It should not be so complicated to setup a profile, though.

**Comment by udeved** [comment]
Good point.
I started some sort of doc in the profiles readme, I can expand it.
I can push the changes then. :)

**Comment by udeved** [comment]
Any thoughts on Packages-Custom?
I move mobile broadband stuff there because it pulls polkit, which causes problems with polkit-consolkit if polkit is already on root-image.
Can you review?

**Comment by excalibur1234** [comment]
is it possible to move "manjaro-documentation" from "Packages" (at the bottom) to "Packages-lxqt/xfce/..."?

i see manjaro-documentation as manjaro-welcome and manjaro-artwork: the ISO profile creator/maintainer should be able to easily remove it, if he chooses to do so.

**Comment by udeved** [comment]
@excalibur1234 

I see no reason not to move it, since pdf files are usually opened anyway in a desktop env.
Good call.

**Comment by excalibur1234** [comment]
manjaro lxqt tries to use connman instead of networkmanager by defaut. networkmanager is more reliable, though. the latest release does not, but i do not know why.
moving networkmanager to Packages-Custom would make it harder for manjaro-lxqt. on the other hand, it will probably simplify things for (almost) all other ISOs.

i see networkmanager already in Packages-livecd. i like this, because it ensures a stable internet connection on the livecd and during the installation. but it also increases ISO size a little.

in my opinion, you should either allow a custom Packages-Custom file in the ISO profile (and move networkmanager to Packages-Custom) or do not move networkmanager to Packages-Custom.

**Comment by udeved** [comment]
I decided to leave NM for individual profile config.
Some people may want to use connman or wicd.
I personally switched to NM.
