### ISSUE TITLE
move packages from "Packages-net/xfce/..." to "Packages-xorg" and "Packages" files?

### ISSUE THREAD

**Issue by excalibur1234** [manjaro/manjaro-tools-iso-profiles#32]
as already mentioned in #30:

how about cleaning up the "Packages-net/xfce/..." file?
the following packages always looked out of place. here the beginning of the "Packages-net" file:
~~~
## Xorg Packages
inxi
libdnet
mesa-demos
>x86_64 lib32-mesa-demos
uriparser
xf86-input-acecad
xf86-input-aiptek
xf86-input-evdev
xf86-input-joystick
xf86-input-keyboard
xf86-input-mouse
xf86-input-synaptics
xf86-input-void
xf86-input-wacom
xinetd
xorg-server
xorg-server-utils
xorg-twm
xorg-utils
xorg-xinit

## Basic packages
dconf
desktop-file-utils

## Packages for Sound and Audio
manjaro-alsa
~~~

the ## Xorg Packages could be pushed to the "Packages-xorg" file. ## Basic packages and ## Packages for Sound and Audio (manjaro-alsa installs lib32 packages) could be pushed to the "Packages" file.

how do you like this idea?

how important are these packages? are there any ISO profiles NOT using these packages? why were they included into the "Packages-net/xfce/..." file in the first place?

**Comment by philmmanjaro** [comment]
No, those are correct there. Packages-Xorg is just for the overlay and are not installed on the CD/DVD at all.
