### ISSUE TITLE
Review /etc/skel

### ISSUE THREAD

**Issue by Dietr1ch** [manjaro/manjaro-tools-iso-profiles#35]
I was thinking that the default /etc/skel directory may need some love.

Should the default shell be changed?
  * Some shells offer good sh/bash compatibility, so using bash may not be a requirement.
  * Default settings are usually bad, for instance, prezto makes zsh much better than the default.

Maybe you have another annoyance to add
  * Default .gitignore, ackrc, etc...

Do you think that improving the 1st experience is worth more than the few extra megabytes that it costs?

**Comment by philmmanjaro** [comment]
Well, we are always open for suggestions. Fork our profiles and send in some pull-requests.
