### ISSUE TITLE
CLI tools missing

### ISSUE THREAD

**Issue by Dietr1ch** [manjaro/manjaro-tools-iso-profiles#36]
Some handy cli tools are missing.
  * tree / ranger
  * htop / iotop / powertop
  * tmux
  * nethogs / nmap
  * ack / rpl (currently not on community (better than sed))
  * parallel
  * git
  * vim / emacs
  * cowsay / fortune mod (ok, no :sob:)
  * xclip

Maybe other annoyance or must that I missed

**Comment by philmmanjaro** [comment]
Well, it always depends on the profile we release. Most of those tools are for experts. If you want them to be added, profiles like i3 or openbox are those to go. On mainstream profiles like Xfce and KDE those are mostly optional to be installed later on ...

**Comment by oberon2007** [comment]
Some of them are already in i3-profile, will check about the rest.
Not a big deal anyway about size but of course very handy when preinstalled :)

**Comment by oberon2007** [comment]
Just gettings to know tree. That one is awesome! :) I agree that it should be on every release. Given that the size is close to zero... ... Not completely convinced about talking cows, yet, though... :D

**Comment by Dietr1ch** [comment]
Maybe we can build some meta-packages for those kind of tools, but how should we group them?

**Comment by oberon2007** [comment]
Not sure how useful this is bc when you'd make for example a package for system monitoring it will include alternative applications for the same task and most of the time people will just have their favourite tool and just need one or two of them.
What would make sense I think would be a (maybe minimal) building package for AUR installations including maybe ```autoconf
automake
binutils
bison
fakeroot
flex
>i686 gcc
>x86_64 gcc-multilib
libconfig
libtool
m4
make
patch
>x86_64 subversion
git
yaourt```
