### ISSUE TITLE
Should we standardize Package lists?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#4]
Should be standardize pkglists?

Eg that root-image doesn't have xorg stuff for example?

**Comment by manjaro** [comment]
Soon or later we have to do it anyway.

**Comment by udeved** [comment]
I agree.

But what branch do we work in by default?

**Comment by manjaro** [comment]
What do you mean by branch. ISO-images default to stable branch. PKGs we normally build in unstable.

**Comment by udeved** [comment]
I mean the git branch.

It seem both devel and master are used, but I see no clear line there.

**Comment by manjaro** [comment]
Hmm, we should maybe create one stable one we only push final stables to. Master is the current code and in devel we break stuff ...

**Comment by udeved** [comment]
Thats an interesting idea I had for pkgbuild repos with manjaro packages.
Should we organize them according to the repo branches?
The advantage would be that we were able to maintain more than one version of packages.
eg I could have NM-ck 1.0.0 in unstable, but 0.9.10 in git testing.

**Comment by manjaro** [comment]
Or so. stable, testing, unstable. Makes sense.

**Comment by udeved** [comment]
The procedure would be then similar to boxit snapshots I think.

**Comment by manjaro** [comment]
yes. we sould "snap" (merge) it then over.

**Comment by aadityabagga** [comment]
Finally built an ISO with manjaro-tools that worked (Phew!).

On the standardization part: @udeved can we agree on a common Packages-OpenRC?
Currently what you do is to replace systemd packages with OpenRC ones, and what I do is add OpenRC packages, I propose a hybrid, where we comment out systemd packages, and under a separate heading list the OpenRC packages added.

I got a bug in the ISO generated about cli-installer.desktop not being executable
<a href="http://i.imgur.com/ovlv8SB.png">
  <img src="http://imgur.com/ovlv8SBl.png" />
</a>

P.S.
Can someone re-add me back to manjaro-tools-iso-profiles

**Comment by udeved** [comment]
I don't qute understand the Packages part you propose.
I use a nolib32 Packages symlinked from shared.

The standardization already happened except for your profiles, since they use their own Packages file. It was mainly about getting rid of xorg depends for root-image.
So I think, you should simply integrate the profile list in the shared structure and symlink.
If I look through your list, you use some non manjaro repo packages for pekwm and the others, so why not put a Packages-Openrc-Arch or something like that you can symlink?

The point is, as soon as you have a reusable list, put it in shared. As long as these files are consistently named, I don't see a problem to have multiple pre defined lists in shared folder.

I changed and migrated some functions yesterday from cli installer to manjaro-tools, so cli installer may be broken currently. My attention was lately on getting calamares going, since Phil said, cli-installer will be deprecated soon.

**Comment by udeved** [comment]
PS: I also think your profiles don't need a custom livecd overlay just because of the cli-installer entry.
For reference, try my lxqt profile and see how well a dynamic menu works, and that cli installer entry is available in live session. Just login OB session, or switch desktop behavior in lxqt session to have OB menu like interface.

**Comment by aadityabagga** [comment]
If you look closely there are three items in my custom overlay:

* local.d for restarting lxdm
* custom openbox menu (what you mention)
* custom xfce menu

**Comment by udeved** [comment]
Well, its basically your choice.

As for lxdm, I still think something pam is not working properly with the lxdm-ck version.

I don't understand why you need a custom xfce menu for live session? Shouldn't menucache(or something like it) take care of this dynamically?

**Comment by aadityabagga** [comment]
Because official xfce iso uses:

* pamac (i use octopi)
* lightdm (i use lxdm)
* thus/calamares (cli only)

These entries differ in the menu.

**Comment by udeved** [comment]
Sure, but why would you need a custom livecd-overlay for this to realize?
This is what I don't understand.

**Comment by udeved** [comment]
@aadityabagga 
I can't add users, only repo owner can.

**Comment by udeved** [comment]
aaditya,
the curiosity is simply what specific menu do you need for xfce in live session?
I thought xfce handles menus dynamically too?
Take OB dynamic menu, I deploy it in lxqt-overlay.
Just curious here.

**Comment by aadityabagga** [comment]
Hi artoo,

The Xfce menu used is whiskermenu, which has favourites tab in which i need to change for octopi rather than pamac, and also has a switch user button, which is needs to be configured for lxdm rather than lightdm.

**Comment by udeved** [comment]
Hmm, can't we do a whisker package then with the alternative config?
I assume whisker has static settings in some file somewhere?

**Comment by aadityabagga** [comment]
Using packages for config files and installer is making work harder for me, as I cant use manjaro-tools because of broken cli-installer package. Even if I build this package on my own it does not matter as the package is pulled from the repo.

**Comment by udeved** [comment]
Huh?

cli installer is fixed in latest git source.
The advantage of a package is, that it is reusable.

**Comment by aadityabagga** [comment]
Ah, but I cant use git package as while building iso it gets package from repos which is the old one.

I found editing files simpler, it meant that did not have to wait for packages.

**Comment by udeved** [comment]
I don't understand....

**Comment by aadityabagga** [comment]
What I mean is that while building ISO near the end, it downloads the cli-installer package from the repos and installs it to the ISO, so git version I built locally I cannot use.

**Comment by udeved** [comment]
Why don't use versioned unstable llivecd and put it in local repo for testing?

**Comment by manjaro** [comment]
Currently we build all in unstable branch. Also I recommend to use netzspielplatz as server. It gets package updates the fastest. I'm about to move another set of packages to testing. Have to move the current once first to stable.

**Comment by aadityabagga** [comment]
Got it.

I was just demonstrating to artoo that in some cases using files in git can be easier than making packages.

**Comment by manjaro** [comment]
Yes, sometimes are files easier ...
