### ISSUE TITLE
error: "mount: wrong fs type"

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#40]
Since today it seems impossible to build any of the profiles. Esclapion and I have tried several. They all give this error: "mount: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error"
The reason seems definitely to be somewhere in the shared files. I haven't changed anything on my system or my profile since i3 successfully built two days ago.
Is this maybe related to nfs-utils and squashfs-tools having been removed (commit b0c08350bc9bd50f0a952c5f266947cd104d8e11)?

**Comment by udeved** [comment]
Did you enablle overlayfs?

**Comment by Esclapion** [comment]
It's a new thing. I use 3.18. How to know if it's enabled, and howto ?

**Comment by udeved** [comment]
overlayfs is by default disabled in manjaro-tools.conf.

Post your build command with -qv option please.

Can you try kernel 3.19+ on host?

Builds fine for me with either aufs(default) or overlayfs.

**Comment by Esclapion** [comment]
http://pastebin.com/rHWCf48H

**Comment by oberon2007** [comment]
it seems to be kernel related. apparenlty just building successfully with 4.0. 3.18 gave the error.

**Comment by udeved** [comment]
My guess is that you need to use a higher kernel both on host and on iso.

**Comment by Esclapion** [comment]
I try to build a net with the 4.1...

**Comment by Esclapion** [comment]
Works, apparently, in VBox. I will ty to build a lxqt.

**Comment by Kirek** [comment]
If you update your kernel you need to restart to aufs to work.

**Comment by oberon2007** [comment]
host 4.0 plus 3.18 on ISO builds works

**Comment by Esclapion** [comment]
It means than we need a 4.x to build the ISOs, now ? I thought 3.18 was right ?

**Comment by udeved** [comment]
3.19 should be enough for aufs, 4.0+ is needed for overlayfs.

**Comment by Esclapion** [comment]
How do you use overlayfs ? Something to do to activate that ?

**Comment by Kirek** [comment]
Add 
use_overlayfs="true"
in manjaro-tools.conf

**Comment by Esclapion** [comment]
Hmm, OK, thanks.

I read on the net than 3.18 has overlayfs.

**Comment by udeved** [comment]
I have added use_overlay in /etc/manjaro-tools/manjaro-tools,conf
If you use a user config in your home dir, you need to update this config.

**Comment by Kirek** [comment]
We need multiple lower layers support, so even if 3.18 and 3.19 have overlayfs, only 4.0+ support multiple lower layers.

**Comment by Esclapion** [comment]
I use the new system with package-custom integrated, and....
![net](https://cloud.githubusercontent.com/assets/3512979/8392993/96d90b3e-1cfc-11e5-9b3a-d2a74612b4f7.png)

**Comment by excalibur1234** [comment]
thanks.

i have just added this piece of information to the wiki:
https://wiki.manjaro.org/index.php?title=Build_Manjaro_ISOs_with_buildiso#Prerequisites

**Comment by Esclapion** [comment]
It's false ? 3.18 also includes overlayfs.

**Comment by Kirek** [comment]
Already answered that: "We need multiple lower layers support, so even if 3.18 and 3.19 have overlayfs, only 4.0+ support multiple lower layers."

**Comment by Esclapion** [comment]
So the 3.19 is bad for that too.

**Comment by Kirek** [comment]
I doubt it will be backported to 3.18 and 3.19, also, who cares? If we need to use those kernel we can continue to use aufs as always.

**Comment by philmmanjaro** [comment]
@oberon2007: first of all, we need to know how you enabled overlayfs, as it is by default disabled in **manjaro-tools 0.9.9**. Linux40 is minimum needed. This we noted also in the profile.conf, as we need multiple lower layers support within overlayfs to work with our ISO images. To use overlayfs also the host kernel has to be 4.0 as minimum. Aufs on the other hand will always work. So it is always good to post the output of **-qv** to get to the problem faster.

**Comment by Esclapion** [comment]
-We- have not enabled overlayfs, we only used the 0.9.9, and a generation who was good with 0.9.8 has stopped working with a 3.18 in the host.

**Comment by philmmanjaro** [comment]
@Esclapion: please post the output ```buildiso -qv``` so we see the full print. You get the error only if you have **overlayfs** enabled and using a kernel lower than 4.0. So please post your complete log to analyse your issue with **linux318**.

**Comment by philmmanjaro** [comment]
@Esclapion: ok. ```use_overlayfs: false``` is set on your end. Did you reboot your machine yet? If you update a kernel you update also the version of Aufs. To claim an issue, please always post the full terminal output.

**Comment by Esclapion** [comment]
I posted that above, but again : 

http://pastebin.com/rHWCf48H

In my opinion, something in manjaro-tools 0.9.9 activate now by default overlayfs during generation.

And an change in manjaro-tools.conf is only for the -target- machine.

**Comment by philmmanjaro** [comment]
Overlayfs is disabled by default. You do that with your **profile.conf**. We can't enable it by default, as not all kernels support it. So your issue might be related to overlayfs or to Aufs during a kernel upgrade. So if you want to know what the issue currently is, please reboot into your **linux318** session and re-run your task. If you hit an error again, please post the whole log.

**Comment by oberon2007** [comment]
Here is the -qv of both kernel 4.0 and 3.18 http://pastebin.com/Pb4EBvbt
Both are showing overlayfs disabled but building with 3.18 still gives: "mount: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error"

**Comment by Esclapion** [comment]
Pastebin of buildiso -p lxqt -a i686 -i  :

http://pastebin.com/u0wwqNgm

**Comment by philmmanjaro** [comment]
Ok, you both claim this error:
<pre> -> mount [livecd-image] on [lxqt-image]
mount: wrong fs type, bad option, bad superblock on overlay,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.</pre>

Let me add more useful information, so we can debug it.

**Comment by philmmanjaro** [comment]
Actually this is an **manjaro-tools** issue and not an **profiles** issue. I added now more details: https://github.com/manjaro/manjaro-tools/commit/43878d23eafdd775dd1c601718619f2788f1c9e4. The error-msg seems that overlayfs is involved somehow.

**Comment by philmmanjaro** [comment]
I added now more information in **manjaro-tools-iso-git-r1477.e9e6b80-1**. Will run one set myself now.

**Comment by oberon2007** [comment]
http://pastebin.com/JfQJ9bVw "We are using overlayfs" !!

**Comment by philmmanjaro** [comment]
Yep. Some is wrong. Have to figure out now why.
```
[phil@manjaro manjaro-tools-iso-profiles]$ buildiso -qv
  -> We are using overlayfs ...
  -> We are using overlayfs ...
==> manjaro-tools
  -> version: r1477.e9e6b80
  -> user_config: /home/phil/.config/manjaro-tools.conf
==> ISO SETTINGS:
  -> iso_label: MJRO090D
  -> iso_name: manjaro
  -> iso_publisher: Manjaro Linux <http://www.manjaro.org>
  -> iso_app_id: Manjaro Linux Live/Rescue CD
  -> iso_compression: xz
  -> iso_checksum: md5
  -> use_overlayfs: false
```

**Comment by philmmanjaro** [comment]
Issue is fixed now. I'll backport it to 0.9.9 now:
```
[phil@manjaro manjaro-tools-iso-profiles]$ buildiso -qv
  -> We are using aufs ...
==> manjaro-tools
  -> version: r1479.b7c4ab3
  -> user_config: /home/phil/.config/manjaro-tools.conf
==> ISO SETTINGS:
  -> iso_label: MJRO090D
  -> iso_name: manjaro
  -> iso_publisher: Manjaro Linux <http://www.manjaro.org>
  -> iso_app_id: Manjaro Linux Live/Rescue CD
  -> iso_compression: xz
  -> iso_checksum: md5
  -> use_overlayfs: false
```

**Comment by Esclapion** [comment]
A request, btw :-)

Can you add a test of the return code, please ? It's not necessary to continue if the mounting is bad. ;)

**Comment by philmmanjaro** [comment]
@Esclapion: please test if **manjaro-tools 0.9.9-2** fixes your issue. And yes, I've to reopen https://github.com/manjaro/manjaro-tools/issues/78

**Comment by philmmanjaro** [comment]
**manjaro-tools-base 0.9.9-3** automatically disables **overlayfs** if host or iso-kernel don't match the minimum pre-requirements.

**Comment by Esclapion** [comment]
Seems good, but i try til the end :

http://pastebin.com/YRZkf1aF

**Comment by Esclapion** [comment]
I generated an ISO now, tried in VBox, and it works. :-)

Off-topic : can you verify if you already have sound in VBox ? (speaker-test -c 2)

**Comment by philmmanjaro** [comment]
**manjaro-tools 0.9.9-4** fixes it now properly. It checks now for host-kernel and for each kernel you have in profile:
```
==> ISO SETTINGS:
  -> iso_label: MJRO090D
  -> iso_name: manjaro
  -> iso_publisher: Manjaro Linux <http://www.manjaro.org>
  -> iso_app_id: Manjaro Linux Live/Rescue CD
  -> iso_compression: xz
  -> iso_checksum: sha1
  -> use_overlayfs: true
==> BUILD QUEUE:
 --> Profile: [xfce-minimal]
  -> work_dir: /var/lib/manjaro-tools/buildiso/xfce-minimal/i686
  -> iso_file: manjaro-xfce-minimal-0.9.0-dev-i686.iso
  -> is_custom_pac_conf: false
  -> initsys: systemd
  -> mount system: aufs
  -> displaymanager: lightdm
  -> autologin: true
  -> nonfree_xorg: true
  -> kernel: linux318
  -> efi_boot_loader: grub
  -> efi_part_size: 31M
  -> pxe_boot: false
  -> plymouth_boot: true
  -> plymouth_theme: manjaro-elegant
  -> hostname: manjaro
  -> username: manjaro
  -> password: manjaro
  -> addgroups: video,audio,power,disk,storage,optical,network,lp,scanner,wheel
  -> start_systemd: bluetooth cronie ModemManager NetworkManager org.cups.cupsd tlp tlp-sleep
  -> start_systemd_live: livecd mhwd-live pacman-init
```

**Comment by philmmanjaro** [comment]
@Esclapion: off-topic: yes, boths speakers are working also in VBox.
