### ISSUE TITLE
profile.conf bad groups

### ISSUE THREAD

**Issue by papajoker** [manjaro/manjaro-tools-iso-profiles#41]
Hi,

in profiles, i can view : 

    #addgroups="video,audio,power,disk,storage,optical,network,lp,scanner,wheel"

if you read arch wiki this groups are not good with systemd. source : https://wiki.archlinux.org/index.php/Users_and_groups#Pre-systemd_groups

**Comment by udeved** [comment]
Nothing wrong using traditional linux/unix groups.
These traditional and evil unix groups will eat your children too, papajoker. :laughing:

**Comment by nam1962** [comment]
Nothing wrong ?
U sure ?

"It is not necessary to add your user to groups (sys, disk, lp, network, video, audio, optical, storage, scanner, power, etc.) for most use cases with systemd. The groups can even cause some functionality to break. For example, the audio group will break fast user switching and allows applications to block software mixing."  
Source --> https://wiki.archlinux.org/index.php/SysVinit#Migration_to_systemd

U can check papajoker's link : the groups configuration user in manjaro happens to be deprecated & potentially problematic... :/

**Comment by udeved** [comment]
Problematic? Why?
Groups are not deprectaed, its just that Archlinux declares them deprecated.
Work fine on gentoo, and if problems occur, we can fix it by recompiling the package thats broke.
I consider it broke, if a package requires systemd specific groups.

**Comment by udeved** [comment]
I will colse this, as there is no point, addGroups override string in profile.conf can contain any valid groups.

**Comment by nam1962** [comment]
I don't get your point : this evolution & it's impact on groups is a Systemd evolution, not something designed by arch devs, just a Systemd evolution. It doe not impact other distros which run under other init systems kike Openrc.
Papajoker post is there to alert on the fact that all of this evolution has not been taken into account in Arch as we still see default groups that are not needed anymore and can break...

**Comment by udeved** [comment]
There is no problem currently. Show me an explicit example where something breaks please.
We support besides systemd openrc too.
