### ISSUE TITLE
KDE: systemd package rename

### ISSUE THREAD

**Issue by ryanvade** [manjaro/manjaro-tools-iso-profiles#44]
kcmsystemd is now systemd-kcm. Should be renamed.

**Comment by Kirek** [comment]
Already done https://github.com/manjaro/manjaro-tools-iso-profiles/commit/30cb0c753f3f167567aefc32ee7f1ae19e7a0f2a

**Comment by ryanvade** [comment]
@Kirek okay. I pulled 0.9.11 earlier and it wasn't fixed yet. :+1:
