### ISSUE TITLE
Removing userChrome.css from the shared firefox profile

### ISSUE THREAD

**Issue by Kirek** [manjaro/manjaro-tools-iso-profiles#45]
The file userChrome.css in shared/etc/skell/.mozilla/9shb6xj3.default/chrome/ effects the theming in the default firefox profile.
Currently this is tailored for the Menda theme, but not all profiles uses that theme, so I think it shouldn't be there as default.
So everyone that wants this extra theme integration with Menda their profile should copy this file to their overlay/ directory, because I want to remove it soonish from shared.

It would be even a better option if someone can integrate it in Menda theme, like vertex-theme https://github.com/horst3180/Vertex-theme/tree/master/extra/Firefox/Vertex/chrome, so we don't have to put this file in the user profile at all.

**Comment by philmmanjaro** [comment]
Yes, remove it. Ask one of the artwork team to adopt it in menda. Else I can grant you rights so you can do it also.

**Comment by udeved** [comment]
Hi Phil,

ich mal mal einen 4.1er kernel mit audit gebaut.(linux41-audit).
Muss noch die modules machen.
Nu die Frage, soll ich den kernel in unstable packen?
Die Idee ist einfach mal die Nutzer testen zu lassen, mit systemd, ohne, 
container zeug usw.
Wenn es keine Meldungen gibt, kann das ja vielleicht dann in den 
normalen kernel rein.
Ich hab noch mal rumgelesen, ich habe keine Probleme wegen audit 
gefunden. Auch im kernel die Hilfe sagt nix zu, außer daß audit auch für 
SELinux gebraucht wird.

Gruß Marcus
