### ISSUE TITLE
upower-pm-utils problem with xfce4-power-manager

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#50]
https://forum.manjaro.org/index.php?topic=25227.msg216962#msg216962
Would this be an option to remove upower-pm-utils from Packages-Desktop?

**Comment by philmmanjaro** [comment]
**xfce4-power-manager** uses **upower**. Currently version **0.99.3-1**.

**Comment by philmmanjaro** [comment]
**upower-pm-utils** is openrc only. So please ask Artoo to fix it.

**Comment by udeved** [comment]
Ck2 and pm utils are good now with upower, on kde.
I need to test for lxqt too, xfce also seems fine with standard upower version.

I just need to have a reliable ck2 with groups version.
It works in vobox and on a laptop, but it somehow doesn't work on my dev box.

**Comment by udeved** [comment]
@oberon2007, @aadityabagga 
Have you tried xfce with upower only and the new ck?
It should work on xfce, but I was too quite, it doesn't with kde.
https://erickoegel.wordpress.com/

**Comment by oberon2007** [comment]
ck plus upower without upower-pm-utils has been working in the past in i3 and fluxbox. You mean re-check now with newer versions of which packages? Or is this only about xfce now? I don't have an xfce installed atm...

**Comment by udeved** [comment]
Does suspend work for flux and i3? I mean with upower and pm-utils.

I don't use xfce, perhaps aaditya knows more.

**Comment by oberon2007** [comment]
I will check with i3 later (that one has xfce4-power-manager installed).
Fluxbox now has pm-utils only (no upower) and suspend via dbus works fine.

**Comment by udeved** [comment]
Ok, but the interesting ones are the real desktop environments with some power module..

Direct dbus calls are quite expensive btw..

**Comment by oberon2007** [comment]
What does expensive mean? ;)

**Comment by oberon2007** [comment]
and ... I don't know of an alternative under Openrc... ??

**Comment by udeved** [comment]
Resource hungry calls. ;)

No alternative for the puritan stuff, except you start to write a power api, like full DEs have.

**Comment by oberon2007** [comment]
While my system goes to sleep I am not so much concerned about the recources... ;) So I guess it's fine :D 
And meanwhile I can tell you that in i3 suspend works with upower-pm-utils. Not with upower only.

**Comment by udeved** [comment]
Yes, lxqt also need upower-pm-utils.
So we can't drop it yet.

**Comment by oberon2007** [comment]
So you will add it to shared packages and no need to add it to i3, right?

**Comment by udeved** [comment]
IIrc, its already in shared.
The question is, if we should move it from shared to the profle.
I still don't really know the problem with xfce.

**Comment by oberon2007** [comment]
I thought so, too, but it appears to have vanished! The i3 ISO has been built yesterday with the latest profiles and it has no upower-pm-utils installed!

**Comment by udeved** [comment]
Perhaps aaditya has removed it.

**Comment by oberon2007** [comment]
I just see that this was committed by accident from my branch when I removed it for the fluxbox-release locally 3 weeks ago, I am sorry. Will re-add it now.

**Comment by aadityabagga** [comment]
Hi @artoo,

Yup it has worked as far as I tested it, and have been shipping it on the xfce-openrc 0.9.0 ISOs since the previous two releases.

**Comment by oberon2007** [comment]
Hm. This is weird! I have uninstalled upower-pm-utils again now and suspend is still working... Don't understand what the problem can have been before I installed it.
Will do a fresh install again tomorrow...

**Comment by oberon2007** [comment]
Ok. I figured it out now: i3 did not have pm-utils installed. So for suspend I need upower and pm-utils, but it works without upower-pm-utils :) So, do we remove it again?

**Comment by oberon2007** [comment]
I guess logically pm-utils should go to shared/ then instead. Xfce-openrc has it listed, too.
