### ISSUE TITLE
Gnome doesn't finish booting it locks up

### ISSUE THREAD

**Issue by killhellokitty** [manjaro/manjaro-tools-iso-profiles#54]
Remove slice user-slice-1000 
is the last item on the boot screen.  After that nothing happens it just sits there.  I have tried on multiple laptops and no difference.  I tried nomodest=0 and no differance.
Please fix this issue.
-Josh

**Comment by philmmanjaro** [comment]
Well, which **manjaro-tools** did you use to build your ISO? Currently all our developers use **manjaro-tools-git** package to build our 15.09-RCs. Also we didn't take a look at the profile currently as we are concentrating on KDE and XFCE profiles for now. Gnome is a community edition and has low priority.

**Comment by killhellokitty** [comment]
Manjaro-tools-git produces a no efi-loader error at boot.  Thought you might like to know.  I understand gnome is not at the top of your list for fixing just be aware it is broken the community edition is broken also and I suspect other community editions have the same problems.  It is to bad this wont be fixed in the near future I was using Manjajro gnome for my class project of building an OS.  I suppose now I am stuck with Ubuntu since its gnome works.  Very disappointing since I am an arch user myself. (we have to have a gui installer with the iso) so arch is out of the question, Im not that talented.  Thank you for your time and I wish you well on getting out xfce and kde mate is so a decade ago, yuck.
-josh

**Comment by Kirek** [comment]
Do you have manjaro-tools-efiboot installed?

**Comment by killhellokitty** [comment]
Yes i do. Not a git version if there is one(couldn't find one)

**Comment by Kirek** [comment]
I just made a quick test of the current Gnome profile and works just fine.
Did you made any modifications?
Also use dd to write the image to an usb (imagewriter should work fine too)

**Comment by killhellokitty** [comment]
I made a current Gnome profile and made no changes or mods.
I used dd and installed to flash and I get no efi-loader.  I did it twice.  I will re-download the profiles and start fresh and see if i can get it.  I do appreciate your time and energy in assisting me.  Thank You!
I will let you know if i am successful or not.

**Comment by killhellokitty** [comment]
I have all the manjaro-tools installed i installed the manjaro-tools-git i re-downloaded the iso-profiles and made no changes to any configs.  I still get 'no efi-loader found'  I also used dd to install to flashdrive.  (virtualBox installs just fine).  Should I remove the manjaro-tools-git? But that may put me right back at the begining of this post.  This is become frustrating especially when you tell me you built it with no problems.  I have to go to class now.  I'll take this up again later.  thanks Again!
-Josh

**Comment by philmmanjaro** [comment]
Well, just a side-note. **efi** is only supported with **x86_64** architecture ...

**Comment by killhellokitty** [comment]
I have have and am building with x86-64

**Comment by killhellokitty** [comment]
I tried to rebuild again I used 'sudo buildiso -p gnome -a x86_64 -b stable' and for DD ' sudo dd bs=4M if='/var/cache/manjaro-tools/iso/manjaro-gnome-15.09-rc2-x86_64.iso' of=/dev/sdb && sync'
I still get 'loader.efi not found'
Is it possible I did something wrong when installing Manjaro-tools-git? I did make sudo make isntall and installed its docbook dependency.  Should I install it as 'su'?

**Comment by killhellokitty** [comment]
Also I have 'Manjaro-tools-git' 'manjaro-tools-base' 'manjaro-tools-efiboot' 'manjaro-tools-iso' 'manjaro-tools-pkg' installed.  Is it possible I have a conflict?

**Comment by philmmanjaro** [comment]
**manjaro-tools-git** replaces the normal versions. The latest stable release of **manjaro-tools** just hit **testing**. The git version we normally use with our **unstable** branch.

**Comment by killhellokitty** [comment]
When you say normal version do you mean:  'manjaro-tools-base' 'manjaro-tools-efiboot' 'manjaro-tools-iso' 'manjaro-tools-pkg'  all of them?

**Comment by philmmanjaro** [comment]
The latest stable release is currently:
```
manjaro-tools-base 0.9.12-2
manjaro-tools-efiboot 225-1
manjaro-tools-iso 0.9.12-2
manjaro-tools-pkg 0.9.12-2
```

**Comment by killhellokitty** [comment]
I installed the testing manjaro-tools as you suggested and I still get loader.efi not found.
I can't for the life of me figure out what is going wrong

**Comment by philmmanjaro** [comment]
Did you tried any of our install medias I create? I only test those in Virtualbox as I've no EFI hardware. You can also ask our sister project [Sonar Linux](http://sonargnulinux.com/) as they release only Gnome based iso-images.

**Comment by philmmanjaro** [comment]
My current **XFCE 15.09-rc3** build just booted fine with EFI in Virtualbox. I see no issue here ...

**Comment by killhellokitty** [comment]
I built the xfce 15.09-rc3 to test it and it worked great in virtualbox until I enabled efi.  Then I got the loader.efi not found.

**Comment by killhellokitty** [comment]
I apologize that was rc2 its the only one in git.

**Comment by philmmanjaro** [comment]
Well, you can try my [build](http://sourceforge.net/projects/manjarotest/files/15.09/xfce/15.09-rc3/). It works on my end so far.

**Comment by Esclapion** [comment]
Fyi, It seems than my last lxqt ISO 64 has the same problem, but I have no UEFI so i can only follow this subject.

**Comment by killhellokitty** [comment]
I tried your build of xfce 15.09-rc3 and everything works as it should.  Efi bootloader works in virtualbox and on flashdrive with dd. And it completes the boot screen and loads into xfce desktop(nice work btw).  What has changed that this version works and the others don't?

**Comment by philmmanjaro** [comment]
Well, please check the buildlogs I provide. I always document the settings and cmds I'm using to produce those install medias.

**Comment by killhellokitty** [comment]
I have used your buildlogs to match and removed those items giving error messages(there were about 10).  No I am stuck with 'overlayfs' issues.  I added [code]overlay /merged overlay noauto,x-systemd.automount,lowerdir=/lower,upperdir=/upper,workdir=/work 0 0[/code] per the Arch wiki's instructions, I even tried changing 'overlay' to 'overlayfs' but I continue to receive this error [code]mount: can't find system=overlayfs in /etc/fstab
Too many arguments[/code]
I am not sure how to handle this, I have never dealt with overlayfs before.  Do you have any insights that may help?

**Comment by Kirek** [comment]
If you have trouble with overlayfs and your current kernel is 4.1 or higher, update your system and do a complete reboot.

**Comment by killhellokitty** [comment]
Okay, I think I have the standard kernel installed 3.6 or something like that.  I'll goa ahead and follow you instructions now and see what happens. 
Thank You

**Comment by killhellokitty** [comment]
I tried it and still get the error <code>mount: can't find system=overlayfs in /etc/fstab
Too many arguments</code> When I try to run buildiso.  Any ideas?

**Comment by killhellokitty** [comment]
in fstab its still listed as 'overlay' not 'overlayfs' if that makes any differance

**Comment by killhellokitty** [comment]
If I change in the gnome profile <code>mount_system="overlayfs"</code> the error recieved is <code>Too many arguments</code>

**Comment by killhellokitty** [comment]
It is using overlayfs instead of aufs in the build now. The error message remains  <code>to many arguments</code> and when it get to <code>installing nts</code> the entire system goes into a hard freeze, no getty no nothing.  Hard reboot is the only way out.

**Comment by Kirek** [comment]
Try doing that:
Install kernel 4.1, using mhwd-kernel or manjaro-settings-manager.
Reboot with this kernel.
Save https://github.com/manjaro/packages-extra/blob/master/manjaro-tools-git/PKGBUILD file to some directory and build and install it with "makepkg -sfi"
You now will be running buildiso with the latest git.

Overlayfs in the kernel is just "overlay" this is fine.

Remove mount_system from the gnome profile, this config option doesn't exist. 
To select aufs or overlay you should modify the file in ~/.config/manjaro-tools.conf (I its not there copy the one in /etc/), and change "use_overlayfs" to false (to use auf) or true (to use overlay, the default).

**Comment by killhellokitty** [comment]
You are gonna love this.  I have kernel 4.1 installed. I downloaded the PKGBUILD and ran "makepkg -sfi" and I recieve this error <code>error: '/home/jo-shva/Documents/manjaro-tools-base-git-r1583.ea57a2a-1-any.pkg.tar.xz': could not find or read package
==> WARNING: Failed to install built package(s).</code>  The package in question is labeled "manjaro-tools-base-git-r1583.ea57a2a-1-x86_64.pkg.tar.xz" It apears that the x86_64 part isnt expected in the package build.  Btw, I already have the testing versions of manjaro-tools installed.
I will remove the gnome profile option.

**Comment by killhellokitty** [comment]
And the computer OS still hard freezes at "installing ntp"!

**Comment by Kirek** [comment]
Just install all the generated *.pkg.tar.xz generated files manually then. (pacman -U filename)

**Comment by Kirek** [comment]
What command do you use to generate the iso and paste the output generated if you append "-vq" to the end of that command?

**Comment by Kirek** [comment]
Also the output of "uname -r"

Also now I read you said: "I added overlay /merged overlay noauto,x-systemd.automount,lowerdir=/lower,upperdir=/upper,workdir=/work 0 0" where you added that?? If you modified /etc/fstab with this remove it...

**Comment by killhellokitty** [comment]
<code> manjaro-tools
  -> version: 0.9.12
  -> manjaro_tools_conf: /etc/manjaro-tools/manjaro-tools.conf
==> PROFILE:
  -> buildsets: community|default|official|openrc
  -> buildset_iso: gnome
  -> is_buildset: false
==> OPTIONS:
  -> arch: x86_64
  -> branch: stable
  -> chroots_iso: /var/lib/manjaro-tools/buildiso
==> ARGS:
  -> clean_first: true
  -> images_only: false
  -> iso_only: false
==> PATHS:
  -> sets_dir_iso: /etc/manjaro-tools/sets/iso
  -> cache_dir_iso: /var/cache/manjaro-tools/iso
==> DIST SETTINGS:
  -> dist_name: Manjaro
  -> dist_release: 15.9-rc2
  -> dist_codename: Bellatrix
  -> dist_version: 2015.09
==> ISO SETTINGS:
  -> iso_label: MJRO159R
  -> iso_name: manjaro
  -> iso_publisher: Manjaro Linux <http://www.manjaro.org>
  -> iso_app_id: Manjaro Linux Live/Rescue CD
  -> iso_compression: xz
  -> iso_checksum: sha1
  -> use_overlayfs: true
==> BUILD QUEUE:
 --> Profile: [gnome]
Too many arguments
  -> work_dir: /var/lib/manjaro-tools/buildiso/gnome/x86_64
  -> iso_file: manjaro-gnome-15.9-rc2-x86_64.iso
  -> is_custom_pac_conf: false
  -> initsys: systemd
  -> mount system: overlayfs
  -> multilib: true
  -> displaymanager: gdm
  -> autologin: true
  -> nonfree_xorg: true
  -> kernel: linux41
  -> efi_boot_loader: grub
  -> efi_part_size: 31M
  -> pxe_boot: true
  -> plymouth_boot: true
  -> plymouth_theme: manjaro-elegant
  -> hostname: manjaro
  -> username: manjaro
  -> password: manjaro
  -> addgroups: video,audio,power,disk,storage,optical,network,lp,scanner,wheel
  -> start_systemd: bluetooth cronie ModemManager NetworkManager org.cups.cupsd tlp tlp-sleep
  -> start_systemd_live: livecd mhwd-live pacman-init
  -> disable_systemd: </code>
still hard freeze 5x with"install ntp"

**Comment by killhellokitty** [comment]
4.1.6-3-MANJARO
yes I modified fstab with the above command  line.  buildiso ept complaining that it couldn't find overlay in /etc/fstab so I followed Arch's instructions.  Are you sure you want me to remove it?

**Comment by Kirek** [comment]
Of course, you add entries in fstab if you want to mount a overlay fs every time you boot your system. This is absolutely not needed for manjaro-tools.

Check also that you have enough space to create an ISO, the current gnome profile needs at least around 9gb, you can check free space with "df -h /var"

**Comment by killhellokitty** [comment]
I will remove from fstab.  I have 60G of free space

**Comment by Kirek** [comment]
Also remove the whole "/var/lib/manjaro-tools/" directory, just in case, and try building another profile, like the "xfce" one.

**Comment by killhellokitty** [comment]
I will give that a try later.  I have to get to class soon.  Again though ntp hard froze my computer, I beginning to hate ntp
Thank you for all your help!!!
I'll try removing the folder and building xfce when I get back.

**Comment by killhellokitty** [comment]
Sorry I have been offline for a few days(internet connectivity issues).  I did as you suggested and built xfce testing and I appear to have no problems with the buils.  Ntp hard froze my machine again with building xfce and gnome.  What is going on?  There is an error message about avahi not being able to create avahi user before the ntp freeze.  Unfortunatly because of the freeze I am unable to transcribe that error message.

**Comment by killhellokitty** [comment]
I should be more accurate.  It installs Ntp and then hard freezes.  Ntp is the last item it installs.

**Comment by Kirek** [comment]
Remove ntp* from `/var/cache/pacman/pkg/` maybe the file is corrupt (unlikely...)

Remove from  `shared/Packages-Desktop` file this line `>systemd ntp`

**Comment by Kirek** [comment]
What I'm thinking is that issue is somehow related to your computer, all this profiles builds fine for me and other developers.

**Comment by killhellokitty** [comment]
Where do i find shared/Packages-Desktop?
It might be my install I had to install the 3.14version of manjaro gnome and upgrade to 3.16 as the latest 3.16 version would freeze during boot(confirmed with friends and multiple laptops).  Should I maybe install the xfce-rc3 and try building within it?

**Comment by Kirek** [comment]
shared/Packages-Desktop is in the manjaro-tools-iso-profiles directory

2015-09-23 11:46 GMT+02:00 Joshua Brown-Williams <notifications@github.com>:

**Comment by killhellokitty** [comment]
building

**Comment by killhellokitty** [comment]
Now it hard freezes at polkit.  What flavor/version of Manjaro would you recommend I install to build.  I'm out of steam with trying in Gnome(I think you are right it must be an issue with the install).

**Comment by Kirek** [comment]
Try with the manjaro-xfce-15.09-rc4-x86_64 https://sourceforge.net/projects/manjarotest/files/15.09/xfce/15.09-rc4/

**Comment by killhellokitty** [comment]
Thank you for the suggestion. I am downloading now and will install over this gnome.  And see where this gets me.   
I cant thank all of you for your help and support!  I am impressed and grateful!  Hopefully this will work out(crossing my fingers)
Thank You - Josh

**Comment by killhellokitty** [comment]
Okay, I tried to install xfce-rc4, and xfce-rc3 both had trouble installing grub2 and were not bootable.  So I installed the default Xfce and upgraded the kernel to 4.1, I also installed the git versions of Manjaro-tools.  I still recieve the error after Ntp installs. The error says something about wrong permissions in .../xfce/etc are 700 should be 755 and the desktop hard freezes.  Not making much headway here ;-(

**Comment by killhellokitty** [comment]
I should point out the Grub2 was to efi boot

**Comment by killhellokitty** [comment]
I think you guys need to do more testing in the wild.  Like I have been doing for you.  I think its pretty obvious that the buildiso has issues that need to be addressed.  It may work on a devs computer that is prepared specially to perform these functions, but on a fresh install on another computer it simply doesnt work.  The Efi support is another good example of it not working in the wild.  Grubs folder is placed in the Efi partition but only the x86_64 binary is installed to the folder, therefore grub fails with efi.  I hope all my testing can be looked at as valuable or at least usefull.  But I really believe you need to consider the issues are on your end.  Do more testing in the wild.
