### ISSUE TITLE
[openrc] cgmanager-openrc

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#55]
This should go in shared/Packages-Desktop.

**Comment by udeved** [comment]
I am gonna move them.

**Comment by Esclapion** [comment]
Not EOL at end of the new Packages-Desktop, care.

**Comment by oberon2007** [comment]
Just fixed that with my last commit https://github.com/manjaro/manjaro-tools-iso-profiles/commit/1d609f08089331cccec52c3230691bff1831bb7e
