### ISSUE TITLE
[15.09] Date for tag?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#56]
When do we want to tag 15.09?

**Comment by philmmanjaro** [comment]
current release is [0.9.13.2-1](https://github.com/manjaro/manjaro-tools-iso-profiles/tree/0.9.13.2-1).

**Comment by excalibur1234** [comment]
this issue can be closed.
obsolete.

**Comment by udeved** [comment]
I reopen, because I think we should use the version scheme for the iso-profiles in the repo.
