### ISSUE TITLE
g_power by default

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#61]
Are there any concerns about adding this by default?
https://github.com/manjaro/manjaro-tools-iso-profiles/blob/master/i3/i3-overlay/etc/sudoers.d/g_power
I would like to be able to call those pm-scripts from exit-scripts under Openrc without password..
Under Systemd those powergroup-rules will not hurt since pm-utils is not present anyway and reboot doesn't require su-rights in the first place...
It's just in a way overriding the pm-util's author's intention....
Just at the same time I see that systemctl never had those concerns about a normal user suspending, rebooting etc...

**Comment by udeved** [comment]
Have you tried a consolekit call instead?
See the ck rules how to call.

**Comment by oberon2007** [comment]
Yes. At the moment I have this: https://github.com/manjaro/packages-community/blob/master/i3exit/i3exit
But it doesn't seem to work for everyone: https://forum.manjaro.org/index.php?topic=26629.msg225259#msg225259
