### ISSUE TITLE
kernel.sysrq=1

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#63]
**/etc/sysctl.d/99-sysctl.conf** has been pre-installed in flux and i3 for a while. I think it is quite useful to have the magic keys enabled.
Now there has been a [request](https://forum.manjaro.org/index.php?topic=26237.msg226591.0) on the forum about this feature in general.
Are there any objections to moving the file to the shared folder?

**Comment by philmmanjaro** [comment]
I'm fine with it. If it improves our OS, why not.

**Comment by Esclapion** [comment]
I have that since 1 year in my ISOs, no problem.

**Comment by Kirek** [comment]
I'm checking the default in other distros
OpenSUSE Tumbleweed -> 184 (128, 32, 16, 8)
Ubuntu 15.04 -> 176 (128, 32, 16)
Debian 8 -> 438 (256, 128, 32, 16, 4 , 2)

It seems they are avoiding "64 - signalling of processes (term, kill, oom-kill)"
Maybe we should go to the debian default?

**Comment by Kirek** [comment]
So, what we do? Go for the debian default, just activate everything with kernel.sysrq=1?

**Comment by Ste74** [comment]
For me is ok to activate for all profile
Il 09/ott/2015 12:19, "Ramon Buldó" <notifications@github.com> ha scritto:

**Comment by philmmanjaro** [comment]
Yes, go for it.
