### ISSUE TITLE
xterm not in shared packages

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#66]
On my experimental build of deepin I just realized that the CLI installer requires xterm and it was not provided by default in this build.
I think it should be a dependency of the installer or listed in Packages-Livecd.
Or is it normally provided from elsewhere? Or just another oddity of deepin that it needs xterm? ;)

**Comment by philmmanjaro** [comment]
**xterm** is only needed as backup terminal for not supported editions by **manjaro-welcome**. Check **manjaro-terminal** script for which editions I've the terminal detection script enabled.

**Comment by oberon2007** [comment]
Ok, I see. Thank you.

**Comment by oberon2007** [comment]
Uhm. Could you just point me to the destination of that script?

**Comment by Esclapion** [comment]
Btw xterm is also a dependency to remove in octopi, if possible. Anyway, octopi search for an available terminal.

**Comment by anika200** [comment]
Also, I have run into a problem with livecd and Gnome not having an xterm available. Can we just start including xterm on the livecd? This would have the benefit of solving three problems at once without much fuss. :-]

**Comment by Esclapion** [comment]
xterm is gtk3, not Qt.Why not add that in your packages list ?

**Comment by philmmanjaro** [comment]
The magic all happens within [manjaro-welcome-terminal](https://github.com/manjaro/manjaro-welcome/blob/master/src/manjaro-welcome-terminal). Currently we support KDE, Gnome, XFCE and LXDE.

**Comment by Ste74** [comment]
Right observation Eclapion

**Comment by udeved** [comment]
xterm is present on livecd, if you have octopi in any pkg list.
