### ISSUE TITLE
fail to build ISO with linux318 

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#67]
I just tried building an i3 ISO with kernel 318. No errors during build but when launching in vb I get [this](http://i.imgur.com/O1BrBgd.png)
Host was 4.1 and I tried again building with host 3.18 - same result.
I have not changed anything in the profile that just built ISOs with kernel 4.1 successfully.
Tools are the newest version as of today.

**Comment by Esclapion** [comment]
Maybe a problem of aufs bad supported ? 3.18 is at the limit, and to run the livecd it's used.

overlayfs ?

**Comment by Kirek** [comment]
It seems support for lz4 in squashfs where added in linux319, I will fix it so it won't be used in mhwd-image in lower kernels.

**Comment by oberon2007** [comment]
Ok. great, thank you. It is still helpful obviously for some people to have ISOs with 318 available. Some still have problems with 4.1

**Comment by Kirek** [comment]
Fixed https://github.com/manjaro/manjaro-tools/commit/16f8d87dcd6d172d4be4b29fd7525a77cfc31e87

**Comment by oberon2007** [comment]
wow, that was quick! :) Thank you! @Kirek !
