### ISSUE TITLE
We have a lot of different sizes of our 'profiles'

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#70]
Here are the sizes of our official profiles:

```
188K	./kde-next
580K	./xfce-minimal
540K	./xfce
152K	./kde-minimal
3,3M	./shared
32K	    ./net
544K	./kde
5,3M	.
```
And here we go for our community profiles:

```
20K	    ./sysmenu
692K	./netbook
2,2M	./deepin
76K	    ./gnome
29M	    ./fluxbox
1,1M	./lxde
212K	./cinnamon
44K	    ./net-minimal
1,9M	./lxqt
3,5M	./pantheon
3,4M	./enlightenment
28M	    ./i3
48M	    ./bspwm
3,0M	./openbox
3,5M	./lxqt-minimal
8,9M	./mate
880K	./budgie-minimal
133M	.
```

And those of openrc profiles:

```
92K	    ./net-openrc
3,0M	./xfce-openrc
3,0M	.
```

So all in mega byte sizes should check what might be wrong. I assume they ship with themes and other files making their profiles to fat. Remember, contact any of our packages and get those themes packed up as regular packages.

**Comment by oberon2007** [comment]
I would say it's mostly the wallpapers. As soon as you supply 4 different you're quickly at 2M just for that ...

**Comment by philmmanjaro** [comment]
I rather think cache files of **firefox** and **palemoon** ...

**Comment by oberon2007** [comment]
oh! that's baaad! :fearful: Will look into that!

**Comment by oberon2007** [comment]
gone. ;)

**Comment by oberon2007** [comment]
moved the wallpapers away now :)
```
612K	./i3
532K	./fluxbox
312K	./deepin
```

**Comment by philmmanjaro** [comment]
Looks fine. Keep it up my friend ;)

**Comment by Esclapion** [comment]
768	lxqt

I prefer to keep -one- wallpaper, but without, I will be lighter ;)

**Comment by oberon2007** [comment]
If anyone would like to move their wallpapers to a package you can just create your own github-repo, call it $profile-wallpapers and create a folder /backgrounds there.
Like that we can use [this template PKGBUILD](https://raw.githubusercontent.com/manjaro/packages-community/master/i3-wallpapers/PKGBUILD). You only have to edit the first three variables. 8)
What we have to bear in mind though is, that when you change the content of the package for a new release then we have to rename the package (like 'i3-wallpapers-1512') because otherwise people who have installed on older ISO will have their favourite backgrounds removed :open_mouth: ;)

**Comment by udeved** [comment]
238k here for lxqt-minimal.
Perhaps some profiles could be cleaned up and indeed a wallpaper package introduced.

**Comment by Ste74** [comment]
The wallpaper in HD resolution  need more Mb .. pantheon have a HD wallpaper , budgie no .. if you want maintain less space in profile the wallpaper want add in a repo yes ..

**Comment by Ste74** [comment]
hi @oberon2007 but when the pkgbuild is ok where push it ?

**Comment by oberon2007** [comment]
Just make a pull request in packages-community then I can build them.

**Comment by Ste74** [comment]
ok :)

**Comment by udeved** [comment]
I am no image expert, and gimp is at war with me, but can't be image size reduced eg  png --> jpeg while keeping size?

**Comment by oberon2007** [comment]
sure. just open them with any picture editor and save as .jpg with quality set to 95% and the size will be a fraction of the original! ;)

**Comment by udeved** [comment]
I don't want to do this in foreign profiles, but mate, jwm and bswm would need this.
I don't know any of these DE.

**Comment by Ste74** [comment]
In our internal forum Holmes suggest a script from aur to reduce Image and
trasform in png format.
Il 15/dic/2015 00:20, "udeved" <notifications@github.com> ha scritto:

**Comment by Ste74** [comment]
Found .. aur pkg is optipng
Il 15/dic/2015 07:29, "Stefano Capitani" <capitani74@gmail.com> ha scritto:

**Comment by holmeslinux** [comment]
hi guys, if you want can remove the profile the JWM of the Manjaro git. i prefer to keep in my git.

vlw fwi, Holmes :)

**Comment by Chrysostomus** [comment]
I tried using jpg for the lockscreen picture, but i3lock does not seem to accept it. Any ideas how to make i3lock use jpg pictures?

**Comment by Chrysostomus** [comment]
Did it for backgrounds though. Bspwm should now get smaller. I'll try to package the lockscreen picture to fursther dimish the size.

**Comment by Chrysostomus** [comment]
Ok, pics deleted, now just need the package to replace them...
