### ISSUE TITLE
All profiles shipping 'openrc-eudev' should been reviewed

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#74]
By checking several openrc profiles I noticed some 3rd-party repository, which [creates issues](https://forum.manjaro.org/index.php?topic=27578.0) with our [current update](https://forum.manjaro.org/index.php?topic=27567.0):

```
[openrc-eudev]
SigLevel = PackageOptional
Server = http://downloads.sourceforge.net/project/archopenrc/$repo/$arch
```

For now at least following install medias are effected due this:
* [net-openrc 15.09](http://sourceforge.net/projects/manjaro-openrc/files/15.09/net/)
* [xfce+ob-openrc 15.09](http://sourceforge.net/projects/manjaro-openrc/files/15.09/xfce%2Bob/)

**Comment by philmmanjaro** [comment]
Current fix would be `sudo pacman -R openresolv-openrc` before trying to update. Also it is recommended to disable this repository **openrc-eudev**.

**Comment by udeved** [comment]
Who to ask for a wiki account?
Its not how I planned the monday night, but I would like to edit the wiki.

**Comment by philmmanjaro** [comment]
Sorry @udeved. I didn't plan it either. I'll create you an account for your @manjaro email. Sending you the password ...

**Comment by beardedragon2** [comment]
@philm mind if I join this conversation?  I'd like to get back to testing and I was first to discover this problem.

**Comment by philmmanjaro** [comment]
@beardedragon2: thx for that. Well, **testing** is currently the same status as within **stable**. @udeved is currently pushing some stuff to **unstable**.

**Comment by udeved** [comment]
I have added some udev-openrc depends to make sure it gets pulled in, even if manjaro-system fails due to the trouble packages on xfce and net iso.
Also fixed a netifrc package error, discovered limitations in split PKGBUILD.

**Comment by beardedragon2** [comment]
@philm Thanks, I now have testing and stable running.  I will keep you up to date.
