### ISSUE TITLE
Introduce comprehensive XFCE keyboard shortcuts for increased productivity

### ISSUE THREAD

**Issue by MagnusOxlund** [manjaro/manjaro-tools-iso-profiles#75]
I want to propose extensive implementation of keyboard shortcuts in the XFCE release.

Currently, the combination of Manjaro and XFCE offers an interface that in certain areas is still largely mouse-based and hence could be made more productive for experienced users by supporting keyboard shortcuts for the most common, if not all, tasks.

The following is a list of shortcuts that I suggest be implemented. However, I am sure that the list could be extended greatly if more users take interest in this issue and offer their inputs on which shortcuts could improve UI productivity.

* Panel item launching and selection
* Desktop item selection/highlighting
* Keyboard access to the desktop's context menu features
* Window tiling shortcuts assigned by default (they are currently unassigned by default)
* The ability to navigate all start menu items with the arrow keys and tab
* Desktop peek à la Windows

Panel item shortcuts could be implemented with Super+1 ... 0 where multiple open instances of the same application would be accessible by tapping the given number key additional times while holding down the Super key. This is how Windows implements this shortcut and I personally find it very intuitive. Additionally, it would be great to be able to navigate the panel with the left and right arrow keys. Currently, the arrows keys are used to navigate the desktop, but tab could be tied to jumping between navigating the desktop and navigating the panel.

Desktop item selection/highlighting could be achieved either in the style of Thunar where you begin typing the name of an item to highlight it or in the style of Windows where you hit the key corresponding to the first character in the name of an item to highlight it. Thunar's method allows you to home in on an item immediately, but requires a search input field and potentially knowing entire item names. The Windows method only requires hitting one key and knowing the first character of the item's name, but can be slow in a case of many items with names beginning with the same character.

Keyboard access to the desktop's context menu could be implemented with traditional access keys or by tying unique key combinations to the functions in the menu.

A suggestion for a default window tiling shortcuts is Super+arrow keys for top, down, left, and right tiling.

Windows' desktop peek is tied to Super+space and works fine for me personally. Implementation of this feature could be pushed out to the "Show desktop" panel item/applet.

Manjaro is among the fastest-growing Linux distributions out there and the combination of it and XFCE offers a beautiful and fast user experience. I post this enhancement request here despite the fact that it's arguably more related to the XFCE project because Manjaro focuses strongly on speed and efficiency and I figure my chances of catching developer interest would be bigger here because of that. I'm also not aware of which of the two projects exactly I should attribute the things I see in the Manjaro XFCE release to, but I know you're the last ones in the production pipeline.

I will be glad to elaborate on my suggestions if you decide to move forward with any of this. 

Again, sorry for the premature submission.

**Comment by philmmanjaro** [comment]
What exactly do you have in mind?

**Comment by MagnusOxlund** [comment]
I updated the body of the issue, in case you didn't get a notification.

**Comment by MagnusOxlund** [comment]
Is there any particular reason why you're closing this issue?

**Comment by udeved** [comment]
The last activity was 4 months ago, its not really clear what the issue is, and I thought it died off.

**Comment by MagnusOxlund** [comment]
Alright. It's an enhancement request for shortcuts across the XFCE desktop, menu, and window manager, akin to those available in Windows.

It may seem insignificant, or it may not, but being able to navigate the environment using the keyboard is a real advantage.

I guess this isn't the most appropriate repo, but maybe you could point me in the right direction?

**Comment by udeved** [comment]
Yes, please look here...
https://github.com/manjaro/desktop-settings

The settings stuff has moved in a separate repo.
