### ISSUE TITLE
depreciate openrc profiles

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#78]
Following profiles are obsolete as all other given profiles are now also possible to build with **openrc**:

* [net-openrc](https://github.com/manjaro/manjaro-tools-iso-profiles/tree/master/net-openrc)
* [xfce-openrc](https://github.com/manjaro/manjaro-tools-iso-profiles/tree/master/xfce-openrc)

Are they even maintained and adopted to the latest **manjaro-tools** changes?

**Comment by udeved** [comment]
I don't know, is Aaditya still around?

**Comment by udeved** [comment]
I would adopt a net-minimal openrc, but at the cost of dropping kde-minimal.

**Comment by Ste74** [comment]
@udeved : if you think is possible i can try to adopt the kde-minimal .. i don't know openrc but i like kde

**Comment by aadityabagga** [comment]
Hi,

I was busy for a while, and may get busy again.

I tried to update the deprecated net-openrc and xfce-openrc profiles, but I am not sure if they work because my Manjaro VM does not work since the OpenRC update.

Can send a pull request if needed.
https://github.com/manjaro/manjaro-tools-iso-profiles/compare/master...aadityabagga:master

**Comment by philmmanjaro** [comment]
Hi @aadityabagga this question is more or less to drop those profiles as the other profiles can be now used also for **openrc**. The only reason to keep them would be, if they are needed and the other profiles won't support **openrc** properly. Also we have to talk about your 3rd-party **openrc-repository**. All needed **openrc** packages should be maintained within Manjaro and not in a 3rd-party repo. We had some issues with your install medias lately. So it would be best to drop these and adopt the upstream changes by using the **openrc** switch build-in of **manjaro-tools**. Ask @udeved for the changes and how we build **openrc** install medias now.

**Comment by aadityabagga** [comment]
Ok. I dropped the custom repo and package, will test once I have a working Manjaro OpenRC VM.

**Comment by philmmanjaro** [comment]
That is great. Please test and give me feedback on the profiles. If not needed anymore we can drop them. **openrc** is a big topic on **Manjaro** so we started to update all profiles to be **openrc** compatible. It only depends who is maintaining which **profile**. So there should be always two maintainers, one for **systemd**, the other for **openrc**. Sometimes it is the same maintainer for both branches. Thx for the **openrc** support so far @aadityabagga

**Comment by philmmanjaro** [comment]
@aadityabagga: I adopted your "fixes". However when we decide it is **depreciated** then we will remove them. For now I made them [work](https://github.com/manjaro/packages-extra/commit/67ad8e40ab9d8ccdc0e1f2e3194e2cc9eaf3ec0d). This is more to find out if they are still needed or not. Did you tried any other profile yet to build for **openrc**?

**Comment by aadityabagga** [comment]
I only tried to build the deprecated ones which failed (your fix would probably work there). Did not check any other profile.

**Comment by philmmanjaro** [comment]
Well, you have to move the profiles again out of the **deprecated** folder to get them work. In the current way it won't work at all. The bigger question is now. Are they still needed or did you tried any of the other given profiles yet?

**Comment by aadityabagga** [comment]
I dont know Phil. I may not get the time to check either.

**Comment by philmmanjaro** [comment]
Ok, simply question then. Can we remove them? The other profiles work as the are now with **openrc**. This is just your customization in regard of joining XFCE and OpenBox in one profile.

**Comment by aadityabagga** [comment]
I have no objection to removing them. It is present on my system (and git) in case it needs to be revived in future.
