### ISSUE TITLE
Calamares check point for installation

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools-iso-profiles#82]
Hi Team , ( sorry ringo i lost your link ) 
what is the reason because calamares need 1Gb of ram to start install ? 
If an user want install a light de in a old pc with less of 1 Gb calamares stop installation and if user not know other two possibility ( thus and cli ) think manjaro is impossible to install.

**Comment by philmmanjaro** [comment]
You can [configure](https://github.com/calamares/calamares/blob/master/src/modules/welcome/welcome.conf) that. Default is:

```
requirements:
    requiredStorage:    5.5
    requiredRam:        1.0
```

**Comment by philmmanjaro** [comment]
Same goes kinda for [thus](https://github.com/manjaro/thus/blob/master/thus/check.py). Default is:

```
MIN_ROOT_SIZE = 6000000000
txt = _("has at least {0}GB available storage space. (*)").format(MIN_ROOT_SIZE / 1000000000)
```

**Comment by Ste74** [comment]
Hi Philip , yes is the same condition but i try now in a vbox with 756Mb of ram . Thus complete the installation ; calamares stop the installation at the check point . If you not have 1Gb of ram calamares not work .

**Comment by philmmanjaro** [comment]
Edit the **welcome.conf** file and write some like **0.6** in it for RAM. Then try again. You can also remove **- ram** from **required**.

**Comment by udeved** [comment]
We could add options to manjaro-tools.conf, but I think it may be clever to wait until we only have one installer?

**Comment by Ste74** [comment]
Hi udeved .. you read my think ..

**Comment by philmmanjaro** [comment]
@Ste74: for now add a customized **welcome.conf** to your overlay if you want to have some changes to **calamares**. We will think if we add some options for it as @udeved suggested ...

**Comment by Ste74** [comment]
Hi @philmmanjaro ok .. for me can close this
