### ISSUE TITLE
[JWM] needs to be stripped down

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#84]
This community profile has themes, wallpapers and other unneeded stuff in the overlay. This has to be removed and packed as packages!

**Comment by udeved** [comment]
Bspwm is also quite big, about 6MB.

**Comment by udeved** [comment]
Currently, we got:

official: 700 KB
community 75.2 MB
community-minimal 1.6 MB

**Comment by holmeslinux** [comment]
hi guys, if you want can remove the profile the JWM of the Manjaro git. i prefer to keep in my git.

vlw fwi, Holmes :)
