### ISSUE TITLE
[shared] What's your thoughts?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#85]
I packaged the shared folder for 15.12 as manjaro-iso-profiles-base.
What if we made profiles symlink to a always installed /usr/share/manjaro-tools/iso-profiles/shared?
Ie we make manjaro-tools-iso depend on manjaro-iso-profiles-base and move the shared folder in git repo into separate git repo.

We could then have a script that generates a basic iso profile structure for beginners.

How could this play out with sonar and netrunner?

**Comment by udeved** [comment]
For example, we have manjaro-tools-iso simply accept shared directory package providers?

**Comment by philmmanjaro** [comment]
What would we gain out of it? Sonar and Netrunner have differnt files, at least for their **isolinux** folder and some branding options. I introduced shared to reduce double files and to get it maintained easier. If we have files which are shared by all projects yes. However we need kind a overlay function so the projects can still use their themes brandings as they are used to ...

**Comment by udeved** [comment]
A little headache is keeping shared folder in the sister repos in sync with development.

The point gain would be to eliminate shared in git in favor of a package. 
I just thought about how we could achive a more default run_dir for buildiso, instead of having basically a moving target. It'd would be cool to a have a default location, since shared is kind iof toolbox to create profiles.

**Comment by philmmanjaro** [comment]
I agree with that. Would that be a v1.0 topic? As with the current situation everybody is using the git-repos for fast development. In a later state packages for profiles would make sense as no big changes are expected. Also it would be good to do more packages in regard of styles and themes. As of now, everything is in the profiles. When we would have packages like **manjaro-settings-xfce 16.03** everybody would be able to install that package to have the latest skel files on his machine. As of now it is only possible to extract them from the profiles. A lot of other things can be then stripped out of the profile to a bare skeleton everybody can use ...

**Comment by udeved** [comment]
I would file it under 0.10.0, and I was thinking 0.9.16(only bugfixes and deployiso work) will be last of 0.9.x

**Comment by philmmanjaro** [comment]
Ok, makes sense.

**Comment by udeved** [comment]
Yep, ideally we end up with very small profiles and probably a profile generator for beginners.

**Comment by philmmanjaro** [comment]
Sounds like a plan.

**Comment by udeved** [comment]
Do we have guys fit with gimp and this stuff to package themes and stuff in optimized formats?

**Comment by philmmanjaro** [comment]
I always recommend **jpegoptim & optipng**. Ask Jonathon. He had optimized a lot for our beginners guide. Some info about it [here](http://www.maknesium.de/optimize-your-pngjpeg-images-with-no-quality-in-minutes).

**Comment by udeved** [comment]
So how would we proceed "packageizing" and image optimizing profile parts?

**Comment by oberon2007** [comment]
Regarding wallpapers I had suggested [this](https://github.com/manjaro/manjaro-tools-iso-profiles/issues/70#issuecomment-147196668) a while ago ;)

**Comment by udeved** [comment]
We perhaps need Mr AJ involved in discusssion, after all, its the sister repo that create headache, but what will work for netrunner, will also work for sonar. If we had community profiles separate, it would be same headache.

**Comment by udeved** [comment]
http://s27.postimg.org/w5hkap46b/isop_possible.png

Profiles like this would be possible with always installed iso-profiles-base provider.
I just built a working iso.

It would only be read "locally" in the profile what exists as file/dir, while dirs must have *-overlay appended. Symlinks, basically the default requirements come from /usr/share/manjaro-tools/iso-profiles/shared

We don't lose any feature we currently have, but profiles would always be sane as well, since requirements are guaranteed. I think its beginner friendlier than before, may also suit sonar guys well.

**Comment by philmmanjaro** [comment]
Let the ideas fly ...

**Comment by udeved** [comment]
Statically symlinking to /usr/share/manjaro-tools/... doesn't play out well with git without some user/groups changes.

What if we still made it mandatory install to /usr/share but one buildiso run, the shared folder is being copied(if not existent) to $HOME/.local/manjaro-tools/... ? Fixed location, we could move shared out of git profiles in favor of a package.
Or, we have a manjaro-tools user dir, non xdg compliant, but all in one place.

**Comment by udeved** [comment]
Or, possibly the best thing we can do, integrate sonar and netrunner in the profiles repo, find a nice solution to shared overrides and keep it as it is.

**Comment by AJSlye** [comment]
I heavily modify the shared folder I use for Netrunner, it's not just isolinux, but just about every aspect of it from what's in the overlays to what packages are installed via the packages files. for instance we have our own netrunner-release package that replaces manjaro-release as these would conflict.

**Comment by udeved** [comment]
Yes, but nothing prevents us from eg implementing >netrunner or >sonar tags in pkglist.
For example the isolinux folder could be deployed as a package, or done in the profile as overlay.

**Comment by AJSlye** [comment]
The issue would be that I edit all of the files under shared and it's sub-folders including packages-Desktop. Which right now is impossible to even put under netrunner/kde-netrunner as it's a hard link inside the manjaro-tools code.

**Comment by udeved** [comment]
But why would you edit shared if you can do overlay in profile? Thats what I didn't get.
If you had a >netrunner tag to mark netrunner specific packages, you could edit along with manjaro.
Same mechanism as for systemd and openrc packages I suggest, easy to expand load function. Overlay copying could be changed, since we now have catagories to run specific code eventually.

**Comment by AJSlye** [comment]
Again, Since I edit Packages-Desktop and it is hard linked in the code, how would I be able to edit this file if it's generated on the fly. Keepingthings in sync with Manjaro has never been an issue for me, ever. The shared folder is one of the easier ones when you consider I keep in sync with calamers-manjaro, verious pkgbuilds like kinfocenter, etc. Also, If it isn't broke why are we fixing it.

**Comment by udeved** [comment]
Well, its a pain in the *** from devel pov having to deal with 3 different repos that hold profiles.
It'd be much simpler if profiles had one default location.

**Comment by AJSlye** [comment]
Then remove shared and put these back under the various profiles where they used to be. That makes more sense than making it more complicated with >netrunner, >systemd tags, etc.

**Comment by udeved** [comment]
I have never moved shared out of profiles, that was a structure I have taken over from manjaroiso.
In my view, shared has valid reasons to exist, proiding a toolbox to create profiles.
Anyway, shared sucks if its 3 times cloned and modiefied, it failed to serve the itended purpose.
Eliminating shared in not so bad, but having shared in the profiles increases profile size, so we need a different solution tahn each profile having "shared" in it.

**Comment by AJSlye** [comment]
Your talking about two overlays and their packages-Xxxx files, yes. All in all what 2 to 5 megs in size, really. Anything more than that should be put in a package to begin with.

**Comment by udeved** [comment]
You need to see your one profile vs manjaro ~20 profiles.
And right, in your case, you could completely move all in your profile instead of symlinking, as long as you only have one profile. The trouble starts for you if you add profiles, and you would want a shared toolbox for symlinks.
We could eliminate Packages-Desktop, or make it only read if its symlink or file in the profile.

**Comment by AJSlye** [comment]
Fixing the situation with Packages-Desktop is a step in the right direction. As far as having shared in the way you suggest, this would be fine as well, as long as there is a way to bypass it (turn this off) and just use files and folders right in the main profile instead.

**Comment by udeved** [comment]
This file/folders option has long been present, but most profiles simply don't use it.
Thats what I wondered, why you modified all the shared stuff instead of doing it in profile.

**Comment by AJSlye** [comment]
See now, I didn't know that. lol :)
Well, I guess with the exception of the hard link to Packages-Desktop that is.

**Comment by udeved** [comment]
This one can be addressed with Packages-desktop,
I did it this way, in order to enforce a certain standard set pf packages for community profiles, so we have clean root-image without much xorg stuff.

Just trying to find some good solution, where we could merge all in one profile repo, it probably also had some synergy effects. I just think that much of the shared customizations in netrunner and sonar are basically not necessary, and it really nothing prevents us from having one profile repo, after all, its all built with buildiso and manjaro as base.

**Comment by AJSlye** [comment]
Yep, that sounds about right to me. ;)

**Comment by udeved** [comment]
I try to overcome the profile_repo variable problem a bit.
It sucks very much how much little changes are needed to test build netrunner or sonar.

**Comment by AJSlye** [comment]
Wait, so adding a Packages-desktop file in the main profile without the capital D bypasses the link to shared/Profile-Desktop?

**Comment by udeved** [comment]
Btw, I plan to rename the folders in shared, I think "overlay" is very misleading, in the sense that overlays are usually in the profile as directory.
My idea was 
overlay --> rootfs
overlay-livecd --> livefs
or something like that

**Comment by AJSlye** [comment]
And kdefs, etc.? Now, that does make a lot more sense.

**Comment by udeved** [comment]
What kdefs?

And nope @non capitatl d, no way to bypass atm, but as said, no problem to change it.

**Comment by udeved** [comment]
With your permission, I would like to do a demo branch including your netrunner.

**Comment by AJSlye** [comment]
There isn't one, that was just following the example, if overlay becomes rootfs then kde-overlay should also be kdefs, for continuity sake. 

A demo branch would be fine with me.

**Comment by udeved** [comment]
I see what you mean, yes, we should name it consistently.

This would target manjaro-tools-0.10.x so perhaps already next version, if 0.9.15 appears to be stable and no big bugs encountered.

**Comment by udeved** [comment]
@AJSlye 

Look at devel branch. This would be your profile integrated, neglect Packages-Desktop, this will be addressed perhaps with >netrunner tag in pkglist.
If you were adding eg lxqt-netrunner, you could have simply a isolinux-netrunner in shared, and symlink it.

**Comment by AJSlye** [comment]
That look and sounds good to me.

**Comment by udeved** [comment]
I am reorganizing shared, there will be manjaro, sonar, and netrunner that hold the overlay folders, to either be symlinked or copied.

**Comment by AJSlye** [comment]
Sounds good. :)

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles/tree/devel/shared

I think clean solution. sonar and netrunner would get tags for package lists.

**Comment by AJSlye** [comment]
Looks good, I'll have to check over the rest of it. missing a lot from my isolinux when it was moved to isolinux-overlay, but I can add that back in on my end.

**Comment by AJSlye** [comment]
Well an lxqt version was just an Idea I was kicking around, and more than likely will never happen.
I don't havethat kind of power at Blue Systems. ;)

**Comment by udeved** [comment]
Its good for testing the build process, because its small profile. Its a copy of my lxqt-minimal.

You should think about a netrunner manjaro-tools pkg addon that provides your pacman.conf and stuff.
Btw, can't you provide a mirrorlist to include, even if it only has one server?

**Comment by AJSlye** [comment]
Maybe, I'll need to look into how to do that.

**Comment by udeved** [comment]
I don't think something is missing in ..shared/netrunner/isolinux-overlay
First isolinux gets copied, then isolinux-overlay copied over

**Comment by AJSlye** [comment]
Yea, I build my syslinux (isolinux) myself from my grfxboot sources:
https://github.com/netrunner-rolling/artwork-gfxboot

If you look in the po folder you'll see these have been edited as well for Netrunner.

**Comment by udeved** [comment]
Ah, ok, just drop them in the overlay, or create isolinux folder in shared/netrunner and use the symlink instead and remove isolinux-overlay. Up to you, you basically got your own space in shared now.

**Comment by AJSlye** [comment]
Like I said, nothing I can't fix on my end. ;)

**Comment by udeved** [comment]
isolinux is now a package and depend of manjaro-tools-iso package.

You'd need a netrunner-isolinux package in your netrunner repo.

**Comment by AJSlye** [comment]
Thanks for the pkgbuild, that's definitely above and beyond.

These changes will not be required untill the next update to manjaro-tools-xxx, right?

**Comment by udeved** [comment]
manjaro-tools-0.10.0 will have it.

I am not sure if I can skip last planned 0.9.16, but I tend towards skipping.

Atm, its manjaro-tools next branch and iso-profiles devel branch working.

**Comment by AJSlye** [comment]
I use what ever is released to the unstable branch, so I should be good for
now, but I'm building this pkg now anyway.

**Comment by udeved** [comment]
If you want to test current, all the PKGBUILD you need are in packages-extra.

**Comment by AJSlye** [comment]
Yea, I did that for a while during the 2015.11 build cycle. It had become a bit too much for me to keep track of with all the other diversions I have to keep track of and update regularly.

**Comment by udeved** [comment]
I personally believe, manjaro kde and netrunner should join forces. Same stuff twice.

**Comment by AJSlye** [comment]
As you can see from my above links, we at Netrunner do a lot of diverting and modifying of the default Plasma code.

**Comment by udeved** [comment]
I meant packages, eg manjaro using netrunner kde, but styled manjaro.

**Comment by AJSlye** [comment]
Actually, the reverse is true now. We use the Manjaro packages and just add our diversions and settings, etc. on top. The only other differences are manjaro-tools related, like our own netreunner themed isolinux and grub menu entries, etc.

**Comment by udeved** [comment]
I see, one more reason to use a shared iso-profiles repo, it helps a lot. 
I can think about your dilemma with conf files of manjaro-tools.
But if it is as you say, why don't manjaro host the few netrunner packages, and we have shared server for pacman.conf?

**Comment by AJSlye** [comment]
Well, I only work for Netrunner and can't make a decisions like that. They like having their packages separated from upstream.
