### ISSUE TITLE
backport all changes in master to devel

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#87]
For **manjaro-tools v0.10** all changes made to **master** need to been backported before merge. I suggest to do so in January 2016.

**Comment by udeved** [comment]
I can do it, but easier is to rename the stuff in master this time.
I don't  think its as easily scripted as last time.

Just thought it would be good to have it after 15.12 in master, because people tend to have time between christmas and new year. In my view, 0.10 needs testing more than 0.15, because 0.9.15 was half step.
I didn't want to do all this in one go.

**Comment by philmmanjaro** [comment]
I know that. However we have to let the people deal with the changes of **v0.9.15** first. I'll help you to backport, but this we do in January. Now they have to create there ISOs first, with the given structure in master branch.

**Comment by udeved** [comment]
Well, I have necver said, I want to merge before 15.12 iso has not been released. Pointless.
I just don't see a problem, with earlier merge, because the 15.12 would be a branch.
I mean, its git checkout profiles/15.12, but do as you wish.

**Comment by ringo32** [comment]
its mayby bit overcall (does is speak this in english?) hehhhmm. just talked some concern more not..
it only for future, because, after the Pre was the structure of iso-profiles changed.. And for 0.10 will see.. moment i use a sourceforge repo for some little stuf... just for needed some mate-desktop settings..does not do for straight intoo the profile...i think cinnamon needs it too but i ddont know, has todo with glib-comple-schemas whatever it calls.. lock screen livecd is anoying will set a seporate thing for that...

**Comment by philmmanjaro** [comment]
When we do this with branches like **15.12** and so on we have to communicate that to our community first. As of now the master branch is for our users for the current stable release of **manjaro-tools**. In other projects you use master for your development and use branches for your stable releases like we do with **msm**. Sure we can do that even earlier but we should discuss that as a team as more people are using this repository ...

**Comment by udeved** [comment]
I know, but I doubt standard branch approach works out, since community not being able to meet release dates likely. So manjaro-tools development would always have to wait until community released their stuff, which is kind of annoying.

**Comment by philmmanjaro** [comment]
Well, we have this situation now, as we changed the structure of the profiles. Even I had no time yet to test the newest structure yet. Most likely the development speed will even drop after this release. However there is a small break needed between these changes. **0.9.15** was not complete done, I get that. 

The community will always push their changes to master and ask the developers when something doesn't work out. Getting them to devel was a great step so far. But we also have to coordinate it a little more. Nobody wants to have a slowdown here. However even I need a little time to test and review the latest changes. We will find a proper solution for this, but not now.

**Comment by udeved** [comment]
We agree basically, I guess that was my point with the threads trying to get a discussion and perhaps a more workable model going.

What I suggest is, community would be informed, that after official release, they would have to checkout the branch of the month to do their release, and we then merge the next month the previous month branch in master. Ie, the community would push to master, always, except they can't meet the official release date, and they'd push for rest few days of month to monthly branch.
Lets get a discussion going, not saying my idea is best or something, just what I believe to be satisfying everybody.

**Comment by philmmanjaro** [comment]
Sure, but if we change always the structure the task https://github.com/manjaro/manjaro-tools-iso-profiles/issues/70 will take forever ... There is some kind or pressure for the community maintainers when we officially release our official ISOs. Some even make the date of release. It always depends on organization. We have a release plan they can rely on. However even I delayed rc2 for some reasons due the C++11 ABI bump. With time we will find a perfect solution for this, but together.

**Comment by udeved** [comment]
I don't plan any further changes in structure. I kind of like it now, I think its clean, consistent, and shared is easily expandable, if there was say "mysupermanjarobased-distro" sibling.
Its why I'd like us as team to think about, if we can do a better coordination for community releases which don't push the break, should we ever have the need to some some structure stunts again..
Its been a quite long way from original manjaroisoi profiles, puh. :laughing:

**Comment by philmmanjaro** [comment]
Then it is easy. I don't think that there are to many commits during the holidays. If we keep track on **master** it should be easy to "backport" those changes to **devel**. I still recommend January for the switch, though ...

**Comment by philmmanjaro** [comment]
Note: **devel** includes all changes up to **Commits on Dec 17, 2015**. I also see some **backports** already. However we should check everything else also before the merge.

**Comment by udeved** [comment]
I already tested yesterday a merge, which of course creates conflicts.
As long as the desktop overlays are uptodate, and eventual other real folder overlays, after merge we only have to delete defunct symlinks that create conflicts.

**Comment by philmmanjaro** [comment]
Yep, I see no biggy there either. It is always the problem to find the proper time slot to do so ;)

**Comment by udeved** [comment]
At least for me, christmas up to 6 of jauary is usually very busy, 4 birthdays, along the with  rest.

**Comment by philmmanjaro** [comment]
Yes, busy in your private life. That is why I recommend to delay the merge.
