### ISSUE TITLE
which branch to use now for latest manjaro-tools-git?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#89]
master or devel?

**Comment by philmmanjaro** [comment]
Currently master is working with **manjaro-tools v0.9.15**, so you go for **devel**.

**Comment by oberon2007** [comment]
thanks

**Comment by udeved** [comment]
If you look inside the .buildiso file, you find the version_min requirement. 
Its new file and serves as repo identifier.
