### ISSUE TITLE
boot-screen

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#90]
My first experiment with **manjaro-tools  r1802.5df64bb** plus deepin-profile in devel branch gives me this boot-screen:
![bootscreen](https://cloud.githubusercontent.com/assets/11800714/11950653/9efe1646-a88a-11e5-90dd-b50d8f99c2e0.png)
When I enter 'start' there everything else appears to be normal.
What's wrong here?

**Comment by philmmanjaro** [comment]
It is in the error. It can't setup gfxboot. Did you installed the package **manjaro-isolinux**, which is needed for the devel-branch?

**Comment by oberon2007** [comment]
No. I had expected that any necessary package will be lists in the new **shared** files.
Do I have to install it locally? If so it should be a dependency of the new tools, don't you think?

**Comment by philmmanjaro** [comment]
Well, it is a new package and the **PKGBUILD** for the **manjaro-tools-git** is not fully updated yet. Install it locally and remove the **build.make_isolinux** file from your **var/lib/manjaro-tools** build dir. Restart the process with the **-c** switch to complete your ISO.

**Comment by oberon2007** [comment]
ok. thanks
