### ISSUE TITLE
[Openbox] Profile files that make up is too small

### ISSUE THREAD

**Issue by fu-sen** [manjaro/manjaro-tools-iso-profiles#92]
When I tried openbox, it has issued the following error:
```
[balloon@manjaro ~]$ buildiso -p openbox
==> Start building [openbox]
 --> Profile: [openbox]
==> ERROR: Profile [/run/media/balloon/ManjaroWORK/work/manjaro-tools-iso-profiles/community/openbox] sanity check failed!
[balloon@manjaro ~]$ 
```
Other profile is operating normally.
file that is included in the openbox is clearly less than the other.
It is I suspect the cause.

**Comment by oberon2007** [comment]
The openbox-profile has not been maintained for a while. Maybe you can use a similar but up-to-date profile, like for example fluxbox as a model to bring openbox into shape? :)

**Comment by fu-sen** [comment]
Thank oberon2007 for the quick reply. I will try other WM.

**Comment by oberon2007** [comment]
どう致しまして！ :)

**Comment by oberon2007** [comment]
I just saw that we have a brand-new xfce-openbox-openrc available. Maybe that could be of interest for you, too: https://sourceforge.net/projects/manjaro-openrc/files/15.12/xfce+ob/

**Comment by fu-sen** [comment]
Thank you for the additional information. 
Since I ISO build was the purpose, it was not looking that far.
it is the other users who are concerned about will attention.

**Comment by fu-sen** [comment]
I understand that it reflects this in the subsequent forum:
https://forum.manjaro.org/index.php?topic=29727.msg246920;topicseen#msg246920

Great information! Thank you very much! :)

**Comment by oberon2007** [comment]
We now have a working openbox profile again in the [devel branch](https://github.com/manjaro/manjaro-tools-iso-profiles/tree/devel/community/openbox)
You have to use **manjaro-tools-git** to build it.

**Comment by Ste74** [comment]
OT : Bernhard but how version use on mt git? Last time i used not run
because isolinux not working.
Il 05/gen/2016 13:02, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by oberon2007** [comment]
It has been fixed meanwhile. **isolinux** was [added as a dependency](https://github.com/manjaro/packages-extra/commit/886f6fd5faebef4272983e6b2f7d75b43f9c50f9) meanwhile :) So the tools built with this [manjaro-tools-git PKGBUILD](https://github.com/manjaro/packages-extra/tree/master/manjaro-tools-git) should work fine with the profiles in devel branch. I've built everything like that recently!

**Comment by Ste74** [comment]
Ok... thank you new ISO`s switch on devel ;-)
Il 05/gen/2016 13:26, "Bernhard Landauer" <notifications@github.com> ha
scritto:
