### ISSUE TITLE
[desktop-settings] we need a plan

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-iso-profiles#95]
We want to move towards reusable skel packages.
We need to think about a structure and rules what goes and what doesn't.
Reason is, some skels use same files or folders, ie we have to make them conflict with each other, which is perhaps not really desirable.

**Comment by philmmanjaro** [comment]
Why not create some basic skel packages we can re-use with others?

**Comment by udeved** [comment]
Yes, thats what I am pointing out, we have to incredibly atomize the skels.
If you take a look at the skels currently, the packages would all have to conflict with each other.
Say some firefox skel package is needed and so on.

**Comment by philmmanjaro** [comment]
For the beginning I'd suggest to pack the skels for each desktop as they are now. We have to simply analyse which files are double and if they are actually the same. Then it might be best to put it into the shared skel package or basic package, what ever we call it. We simply have to start somewhere. Tweaking and optimizing can come later ...

**Comment by udeved** [comment]
Yep, we can update the desktop-settings repo after profiles merge, the PKGBUILD already exists in extra repo to build up on that.

**Comment by philmmanjaro** [comment]
Preparation is always key ;)

**Comment by udeved** [comment]
My preparations are usually not very noisy, but they are there.

https://github.com/manjaro/packages-extra/blob/master/desktop-settings/PKGBUILD

https://github.com/manjaro/desktop-settings

I like preparations. :)

**Comment by coffeeking** [comment]
hi
I love this idea. I'd love to have sonar settings for both gnome and 
mate which are installed system wide, and can be easily updated. This 
would largely prevent the need to re-install in order to get changed or 
added keyboard shortcuts or desktop icons, which is currently necessary. 
How might this be done? I don't know much about dconf, but is there a 
system location for these binary files? If so, where might they be 
stored? If I can get this info, I'll upload a sonar-settings profile or 
package, whichever is needed.
Thanks
Kendell clark

**Comment by ringo32** [comment]
is the skell only packaged ?? not like something as /usr/share/glib-2.0/schemas/ ? to take te override especially for mate ? just curius...

**Comment by udeved** [comment]
At the monmet, its only the skel.
But, you can put your schema also in skel/.local/

We can think about to package schema files, but they must not be provided by any other package.

**Comment by oberon2007** [comment]
https://github.com/manjaro/desktop-settings/issues/1#issuecomment-170653830

**Comment by philmmanjaro** [comment]
Seems some file conflicts already occur: https://github.com/manjaro/desktop-settings/issues/4
