### ISSUE TITLE
[sonar] optimize profiles

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-iso-profiles#96]
Currently we have some big **sonar** profiles. We have to analyse them and optimise them.

**mate**
```
2,0M	./usr/share
2,0M	./usr
8,00K	./etc/lightdm
12,0K	./etc/xdg
12,0K	./etc/speech-dispatcher
128K	./etc/purple
8,00K	./etc/calamares
1,9M	./etc/skel
16,0K	./etc/pulse
12.0K	./etc/profile.d
2,1M	./etc
4,0M	.
```

**gnome**
```
2,1M	./usr/share
2,1M	./usr
12,0K	./etc/xdg
12,0K	./etc/speech-dispatcher
128K	./etc/purple
8,00K	./etc/calamares
1,8M	./etc/skel
16,9K	./etc/pulse
2,0M	./etc
4,1M	.
```

**Comment by philmmanjaro** [comment]
Deeper analysis. Seems there are some unneeded settings for **libreoffice** ...

**gnome**

```
776K	./usr/share/sounds
44,0K	./usr/share/backgrounds
8,00K	./usr/share/themes/Adwaita
12,0K	./usr/share/themes
36,0K	./usr/share/sonar
504K	./usr/share/fonts/TTF
508K	./usr/share/fonts
8,00K	./usr/share/icons/default
12,0K	./usr/share/icons
744K	./usr/share/calamares/branding
748K	./usr/share/calamares
2,1M	./usr/share
2,1M	./usr
8,00K	./etc/xdg/surfraw
12,0K	./etc/xdg
8,00K	./etc/speech-dispatcher/modules
12,0K	./etc/speech-dispatcher
60,0K	./etc/purple/logs/irc
64,0K	./etc/purple/logs
12,0K	./etc/purple/certificates/x509
16,0K	./etc/purple/certificates
128K	./etc/purple
8,00K	./etc/calamares
28,0K	./etc/skel/.local/share
32,0K	./etc/skel/.local
12,0K	./etc/skel/Desktop
1,8M	./etc/skel/.config/libreoffice
8,00K	./etc/skel/.config/pulseaudio-ctl
8,00K	./etc/skel/.config/autostart
16,0K	./etc/skel/.config/dconf
1,8M	./etc/skel/.config
1,8M	./etc/skel
16,0K	./etc/pulse
2,0M	./etc
4,1M	.
```

**mate**

```
8,00K	./usr/share/mate-panel/layouts
12,0K	./usr/share/mate-panel
776K	./usr/share/sounds
244K	./usr/share/backgrounds/lightdm
48,0K	./usr/share/backgrounds/mate
376K	./usr/share/backgrounds
36,0K	./usr/share/sonar
744K	./usr/share/calamares/branding
748K	./usr/share/calamares
2,0M	./usr/share
2,0M	./usr
8,00K	./etc/lightdm
8,00K	./etc/xdg/surfraw
12,0K	./etc/xdg
8,00K	./etc/speech-dispatcher/modules
12,0K	./etc/speech-dispatcher
60,0K	./etc/purple/logs/irc
64,0K	./etc/purple/logs
12,0K	./etc/purple/certificates/x509
16,0K	./etc/purple/certificates
128K	./etc/purple
8,00K	./etc/calamares
36,0K	./etc/skel/.local/share
40,0K	./etc/skel/.local
12,0K	./etc/skel/Desktop
12,0K	./etc/skel/.config/menus
1,8M	./etc/skel/.config/libreoffice
8,00K	./etc/skel/.config/pulseaudio-ctl
8,00K	./etc/skel/.config/autostart
24,0K	./etc/skel/.config/dconf
1,8M	./etc/skel/.config
1,9M	./etc/skel
16,0K	./etc/pulse
12,0K	./etc/profile.d
2,1M	./etc
4,0M	.
```

**Comment by philmmanjaro** [comment]
Seems the **libreoffice** settings got introduced with this: https://github.com/manjaro/manjaro-tools-iso-profiles-sonar/commit/a476bfdc0b4ea78b0e39926b6206de52e46a126e

**Comment by coffeeking** [comment]
hi


The /etc/purple folder is a pidgin config. This is done so that if the 
user clicks on the "ask for help online" desktop icon, pidgin starts 
configured to connect to our irc channels, #talkingarch and #sonar on 
irc.netwirc.tk, with sound enabled. This is done in a separate location 
so that a new user doesn't have to configure pidgin before they can use 
it, which a new user might not know how to do. It was designed so that 
if someone has problems during installation they can click that and 
immediately get help. This is where my ignorance comes in. I basically 
set up pidgin to connect to our profile on a live image, configured 
sounds, then copied the resulting .purple folder into /etc/skel. I hope 
there's a better way to do it but that was a temporary way.

Thanks
Kendell clark

**Comment by coffeeking** [comment]
hi
No,  the libreoffice  config is necessary. Without this, if a user opens 
a readonly document, they can't read it with orca until they go into the 
settings and enable the caret in readonly documents. This is easily 
done, but I'm trying to make this as plug and play as possible. That 
being said, there could easily be some unneeded temporary files or cache 
files that aren't needed. I don't know which file is the actual 
libreoffice config file, which is the only file needed.
Thanks
Kendell clark

**Comment by philmmanjaro** [comment]
@coffeeking: I'll check what file is needed and will test it myself. Most likely we can remove some. Since both editions use this config file, it is double anyway and can be placed into shared. For now we let it be as it is. First we have to get a working ISO once again.
