### ISSUE TITLE
root-overlay vs. live-overlay/root ?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-iso-profiles#97]
I gather from the new dir **root-overlay** that everything in **<profil>-overlay/root** should now be superfluous. Sometimes it appears to be useful for me to have stuff for root in live different from root in the final install (it is not essential, but nice, and it's more also a theoretical question here).
So will stuff in **live-overlay/root** still override **root-overlay**, or not?

**Comment by udeved** [comment]
No, root-overlay is respective to the root-image, which corresponds to the Packages-Root.
root-overlay/root is the user home of user root on the target filesystem.

**Comment by oberon2007** [comment]
That means that the user home of root in the live env still resides in **live-overlay/root** ?

**Comment by philmmanjaro** [comment]
Documentation is key here ;)

**Comment by udeved** [comment]
@oberon2007 

Basically, the iso is assembled in several steps, in layers, realized with either overlayfs or aufs.

It goes like this:

1. root-image
2. custom-image
3.live-image
4. mhwd-image
5. boot stuff
6. squash 1-4 and compress to iso file

The overlayfs will join the 4 aprts into one filesystem like you have on your local system.

**Comment by oberon2007** [comment]
![image](https://cloud.githubusercontent.com/assets/11800714/12181781/94805d1c-b584-11e5-8c27-051529406c06.png)

**Comment by udeved** [comment]
In essence, it doesn't really matter if you have say, i3-overlay/root or root/overlay/root
It both ends up in target system, i3-overlay will be copied after root-overlay, and will be on a different image within the iso, in another layer. i3 layer.

**Comment by oberon2007** [comment]
Yes, that's all perfectly fine :laughing: My question was just, where do I place stuff that I want only for the user root in the live-environment. An example would be the i3 config with shortcuts for the installers. I don't need them in the target install but would like to have them available for root in the live - which they are not when only placed in live-overlay/etc/skel. So I guess I can put that in live-overlay/root, correct? :)

**Comment by udeved** [comment]
live-overlay/root, can be either symlink or override folder in the profile.

**Comment by udeved** [comment]
You are not forced to use symlinks from shared, you can pretty much build a profile without any shared symlink. The only think that would come from shared was Packages-Desktop

**Comment by oberon2007** [comment]
Yesyes, I know. Thank you :)
@philmmanjaro now that we have be honored with a 'question'-tag, do I keep this issue open? Or close it anyway?

**Comment by philmmanjaro** [comment]
As any other issue. When it is solved you can close it. I just marked it so we know later that it is just more reasonable.
