### ISSUE TITLE
buildiso not working

### ISSUE THREAD

**Issue by tulliana** [manjaro/manjaro-tools-iso-profiles#98]
Hi guys,

buildiso not working after the last works (manjaro-tools-iso-profiles)

OUTPUT:
[tulliana@tulliana-pc manjaro-tools-iso-profiles]$ sudo buildiso -p xfce
[sudo] password for tulliana: 
==> ERROR: /home/tulliana/manjaro-tools-iso-profiles is not a valid iso profiles directory!

**Comment by udeved** [comment]
What's the content of your $HOME/.config/manjaro-tools/ ?

**Comment by tulliana** [comment]
[tulliana@tulliana-pc manjaro-tools]$ ls
build.conf  manjaro-tools-iso-profiles.conf

files content:
run_dir=/home/tulliana/manjaro-tools-iso-profiles

**Comment by udeved** [comment]
Please output of

    buildiso -p xfce -qv

**Comment by tulliana** [comment]
[tulliana@tulliana-pc manjaro-tools-iso-profiles]$ buildiso -p xfce -qv
[sudo] password for tulliana: 
==> ERROR: /home/tulliana/manjaro-tools-iso-profiles is not a valid iso profiles directory!

**Comment by udeved** [comment]
git iso profiles?

What manjaro-tools version? 0.10.0?

Please post your $HOME/.config/manjaro-tools/manjaro-tools.conf

**Comment by tulliana** [comment]
manjaro-tools-base  0.9.15-4
manjaro-tools-iso  0.9.15-4

$HOME/.config/ under build.conf and manjaro-tools-iso-profiles.conf files

No manjaro-tools.conf

manjaro-tools.conf on /etc/manjaro-tools/

######################################################
################ manjaro-tools.conf ##################
######################################################

# default branch
# branch=stable

# default arch: auto detect
# arch=$(uname -m)

# cache dir where buildpkg, buildtree cache packages/pkgbuild, builiso iso files
# cache_dir=/var/cache/manjaro-tools

# build dir where buildpkg or buildiso chroots are created
# chroots_dir=/var/lib/manjaro-tools

# custom build mirror server
# build_mirror=http://mirror.netzspielplatz.de/manjaro/packages

################ buildtree ###############

# manjaro package tree
# repo_tree=('core' 'extra' 'community' 'multilib' 'openrc')

# host_tree=https://github.com/manjaro

# default https seems slow; try this
# host_tree_abs=git://projects.archlinux.org/svntogit

################ buildpkg ################

# default pkg buildset; name without .set extension
# buildset_pkg=default

################ buildiso ################

# the iso-profiles directory name/git repo name
# profile_repo='manjaro-tools-iso-profiles'

# default iso buildset; name without .set extension
# buildset_iso=default

# unset defaults to given value
# dist_name="Manjaro"

# unset defaults to given value
# dist_release=15.09

# unset defaults to value sourced from /etc/lsb-release
# dist_codename="Bellatrix"

# unset defaults to given value
# dist_branding="MJRO"

# unset defaults to given value
# iso_name=manjaro

# iso publisher
# iso_publisher="Manjaro Linux <http://www.manjaro.org>"

# iso app id
# iso_app_id="Manjaro Linux Live/Rescue CD"

# compression used, possible values xz (default, best compression), gzip, lzma, lzo, lz4
# lz4 is faster but worst compression, may be useful for locally testing isos
# iso_compression=xz

# valid: md5, sha1, sha256, sha384, sha512
# iso_checksum=md5

# experimental; use overlayfs instead of aufs
# requires minimum 4.0 kernel on the build host and on iso in profile.conf
# use_overlayfs="false"

################ deployiso ################

# the server url
# remote_url=sourceforge.net

# the server project
# remote_project=manjaro-testing

# the server home
# remote_target=/home/frs/project

# the server user
# remote_user=[SetUser]

# set upload bandwidth limit in kB/s
# limit=100

**Comment by udeved** [comment]
You need manjaro-tools-0.10.0 for the profiles.
0.9.15 does not work.

Or use manjaro-tools-git in packages-extra.

**Comment by tulliana** [comment]
I think problem with https://github.com/manjaro/manjaro-tools-iso-profiles under last works.

I guess I have to wait?

**Comment by tulliana** [comment]
where is manjaro-tools-git package ? (unstable repos?)

**Comment by udeved** [comment]
https://github.com/manjaro/packages-extra/tree/master/manjaro-tools-git

;)

**Comment by udeved** [comment]
Or you do

    pacman -U <mirror>/unstable/manjaro-tools*.xz

**Comment by tulliana** [comment]
I installed this packages:
manjaro-tools-base  0.10.0-1
manjaro-tools-iso  0.10.0-1

same error:
[tulliana@tulliana-pc manjaro-tools-iso-profiles]$ sudo buildiso -p xfce -qv
[sudo] password for tulliana: 
==> ERROR: /home/tulliana/manjaro-tools-iso-profiles is not a valid iso profiles directory!

**Comment by udeved** [comment]
It is no bug, something is wrong with your configuration, or you don't have uptodate git profiles

**Comment by tulliana** [comment]
I installed this packages:
manjaro-tools-base 0.10.0-1
manjaro-tools-iso 0.10.0-1
 
and

git clone git@github.com:manjaro/manjaro-tools-iso-profiles.git

manjaroiso now working. Thank you so much ;)
