### ISSUE TITLE
[request] Include chroot tool in all Manjaro's ISO's flavours

### ISSUE THREAD

**Issue by FadeMind** [manjaro/manjaro-tools-iso-profiles#99]
All Manjaro ISO's should including tool `mhwd-tool` [described here](https://wiki.manjaro.org/index.php/Restore_the_GRUB_Bootloader#Chroot_into_your_existing_Manjaro_Installation)

Regards

**Comment by oberon2007** [comment]
link is not working for me ...

**Comment by FadeMind** [comment]
I fixed typo  right now.

**Comment by oberon2007** [comment]
mhwd-chroot you mean? that is now already part of manjaro-tools-base :) Invoke it with ``manjaro-chroot -a``

**Comment by philmmanjaro** [comment]
Well, we have two tools doing the same thing. **manjaro-chroot** and **mhwd-chroot**. However, the use not the same code. Most likely **mhwd-chroot** will be dropped soon.

**Comment by FadeMind** [comment]
@philmmanjaro but IMO ISO's should include chroot tool.
I followed manjaro wiki, so I thought mhwd-chroot is  main chroot tool (not included in ISO),

**Comment by philmmanjaro** [comment]
**mhwd-chroot** is a [community package](https://raw.githubusercontent.com/manjaro/packages-community/master/mhwd-chroot/PKGBUILD) created by our french maintainer **Esclapion**. Our official developer tools **manjaro-tools** gained also a [**chroot** tool](https://raw.githubusercontent.com/manjaro/manjaro-tools/master/bin/manjaro-chroot.in), which is developed since late 2014. **mhwd-chroot** was added to our repositories by @Kirek in June 2015. We will see which one we might ship in our next ISOs.

**Comment by udeved** [comment]
manjaro-choort has wee bit more advanced mounting.

~~~
$ manjaro-chroot -a
[sudo] password for devtux: 
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
==> Detected systems:
 --> 0) Arch
 --> 1) Gentoo
==> Select system to mount [0-1] : 
0
==> Mounting (Arch) [/dev/sda13]
  -> mounted: /build/manjaro-tools/manjaro-chroot
  -> mounted: /build/manjaro-tools/manjaro-chroot/boot
  -> mounted: /build/manjaro-tools/manjaro-chroot/boot/efi
  -> mounted: /build/manjaro-tools/manjaro-chroot/home
  -> mounted: /build/manjaro-tools/manjaro-chroot/build
[root@manjaro-openrc /]# pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra                                      1765.4 KiB   951K/s 00:02 [#######################################] 100%
 community                                     3.1 MiB  1018K/s 00:03 [#######################################] 100%
:: Starting full system upgrade...
 there is nothing to do
[root@manjaro-openrc /]# exit
exit
~~~

**Comment by udeved** [comment]
In all fairness, systemd-nspawn is also available for systemd users by default.

**Comment by Esclapion** [comment]
mhwd-chroot works also in terminal, and is especially tested for clean unmounting (if you will do several call). For example, i update with it all my manjaro installlations, without leaving the current.

/boot/efi is not handled for the moment (can be easily added). mounting /build is really necessary ?

Is /dev/pts managed by manjaro-chroot ?

This error on /run/lvm/lvmetad.socket is annoying for both, i think (never seen, i don't use lvm).

**Comment by udeved** [comment]
manjaro-chroot handles complete mounting, it uses the mounting libs that buildpkg and buildiso use to mount chroots.

**Comment by Esclapion** [comment]
swap is also managed by mhwd-chroot.

**Comment by udeved** [comment]
sqap is already handles in live session, the fstab swap entry gets ignored.
If you run it from installed system, it usually also has swap already.
I thought about ignoring /home too for chroot fstab.

**Comment by Esclapion** [comment]
I have been annoyed by /dev/pts... do you manage differences between 32 and 64 bits installations ? For example, if you do a chroot from a 64 to a 32, you change the arch ?

**Comment by udeved** [comment]
yes, its your idea that was integrated.
I just made it fit here and there. :)

**Comment by FadeMind** [comment]
Requirements

Root privilege.
* Another Linux environment, e.g. a LiveCD or USB flash media, or from another existing Linux distribution.
* **Matching architecture environments; i.e. the chroot from and chroot to. The architecture of the current environment can be discovered with: uname -m (e.g. i686 or x86_64).**
* Kernel modules loaded that are needed in the chroot environment.
* Swap enabled if needed:
`# swapon /dev/sdxY`
* Internet connection established if needed.

[sauce](https://wiki.archlinux.org/index.php/change_root#Requirements)

**Comment by philmmanjaro** [comment]
Most likely we won't add a **chroot** option to our install medias, but we will see.
